### ISSUE TITLE
Private key to file error

### ISSUE THREAD

**Issue by krystalflame** [SamKirkland/FTP-Deploy-Action#105]
**Bug Description**
Sending key through a secret appears to not work.

**My Action Config**
```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
        
    - name: Create SSH deploy key
      run: echo ${{ secrets.KEY }} >> "$HOME/.ssh/ftp_publish_key"

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://${{ secrets.HOST }}/
        ftp-username: ${{ secrets.USERNAME }}
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        local-dir: ~/minecraft/
        git-ftp-args: --key "$HOME/.ssh/ftp_publish_key"
        # add the following line instead  if your certificate is setup incorrectly
        # git-ftp-args: --insecure
```

**My Action Log**
```
https://github.com/krystalflame/minecraft-server/actions
I don't know how to post GH Actions logs, sorry
```
