### ISSUE TITLE
Issues getting only changed files to upload - Gatsby website

### ISSUE THREAD

**Issue by ddiiorio** [SamKirkland/FTP-Deploy-Action#112]
I have tried as many different config variations as I can think of with no success, every time I run the workflow I get the message `No changed files, but different commit ID. Changed files ignored or commit amended.` and it proceeds to upload every file again.

I have tried fetch-depth 2, 40, and 0. Same result every time, whether I change 1 file or 0 files and push. Gatsby websites put build files in `public` directory, and I have `!public/` in my .git-ftp-include file. I've tried `local-dir: public` with and without a trailing / (readme says to include trailing slash, but React example doesn't show it).

Any help is appreciated!!

**My Action Config**
```
name: New deployment

on:
  push:
    branches:
      - test-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Gatsby Cache Folder
      uses: actions/cache@v1
      id: gatsby-cache-folder
      with:
        path: .cache
        key: ${{ runner.os }}-cache-gatsby
        restore-keys: |
          ${{ runner.os }}-cache-gatsby

    - name: Gatsby Public Folder
      uses: actions/cache@v1
      id: gatsby-public-folder
      with:
        path: public/
        key: ${{ runner.os }}-public-gatsby
        restore-keys: |
          ${{ runner.os }}-public-gatsby

    - name: Install dependencies
      run: npm ci

    - name: Build
      run:  npm run build --if-present --log-pages
      env:
        GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
        GATSBY_WORDPRESS_URL_DEV: ${{ secrets.GATSBY_WORDPRESS_URL_DEV }}
        GATSBY_CONCURRENT_DOWNLOAD: 20
        GATSBY_SCHEMA_TIMEOUT: 10000
        GATSBY_GA_TRACKING_ID: ${{ secrets.GATSBY_GA_TRACKING_ID }}

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public/
        git-ftp-args: --dry-run
```

**Part of My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@3.1.1
  with:
    ftp-server: ***
    ftp-username: ***
    ftp-password: ***
    local-dir: public/
    git-ftp-args: --dry-run
/usr/bin/docker run --name e5c357e2dabd7e4a943ad98592f6b2073f6a5_f38484 --label 1e5c35 --workdir /github/workspace --rm -e INPUT_FTP-SERVER -e INPUT_FTP-USERNAME -e INPUT_FTP-PASSWORD -e INPUT_LOCAL-DIR -e INPUT_GIT-FTP-ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/sif-2.0/sif-2.0":"/github/workspace" 1e5c35:7e2dabd7e4a943ad98592f6b2073f6a5
Uploading files
  /usr/bin/git ftp push --force --auto-init --verbose --syncroot=public/ --user=*** --passwd=*** --dry-run ***
  Mon Oct 12 22:42:19 UTC 2020: git-ftp version 1.5.1 running on Linux 1878a93a705b 5.4.0-1026-azure #26~18.04.1-Ubuntu SMP Thu Sep 10 16:19:25 UTC 2020 x86_64 GNU/Linux
  Mon Oct 12 22:42:19 UTC 2020: Forced mode enabled.
  Mon Oct 12 22:42:19 UTC 2020: Auto init if needed.
  Mon Oct 12 22:42:19 UTC 2020: Using syncroot public/ if exists.
  Mon Oct 12 22:42:19 UTC 2020: Running dry, won't do anything.
  Mon Oct 12 22:42:19 UTC 2020: Host is 'ftp.southislandfireplace.com'.
  Mon Oct 12 22:42:19 UTC 2020: User is '***'.
  Mon Oct 12 22:42:19 UTC 2020: Password is set.
  Mon Oct 12 22:42:19 UTC 2020: CACert is ''.
  Mon Oct 12 22:42:19 UTC 2020: Insecure is '0'.
  Mon Oct 12 22:42:19 UTC 2020: Proxy is ''.
  Mon Oct 12 22:42:19 UTC 2020: Path is ''.
  Mon Oct 12 22:42:19 UTC 2020: Syncroot is 'public/'.
  Mon Oct 12 22:42:19 UTC 2020: The remote sha1 is saved in file '.git-ftp.log'.
  Mon Oct 12 22:42:19 UTC 2020: Check if curl is functional.
  Mon Oct 12 22:42:19 UTC 2020: Retrieving last commit from ***ftp.southislandfireplace.com/.
  #=#=#                                                                         
  ##O#- #                                                                       
                      
  
  ######################################################################## 100.0%
  Mon Oct 12 22:42:36 UTC 2020: No changed files, but different commit ID. Changed files ignored or commit amended.
  Mon Oct 12 22:42:36 UTC 2020: Including all files in public/ for upload.
  Mon Oct 12 22:42:36 UTC 2020: Having files to sync.
  Mon Oct 12 22:42:36 UTC 2020: 2096 files to sync:
  removed list of every single file
  Mon Oct 12 22:42:43 UTC 2020: Uploading commit log to ***ftp.southislandfireplace.com/.git-ftp.log.
  Mon Oct 12 22:42:43 UTC 2020: Last deployment changed from ee9c2fabc2b0a6f9efa4716bdaf9786bc11ec8e9 to 87dced2b3bccd04b3cbf1c0d94ead8ca88d07b93.
```
