### ISSUE TITLE
How to deploy from subdir into root?!?!

### ISSUE THREAD

**Issue by ewerybody** [SamKirkland/FTP-Deploy-Action#115]
**Bug Description**
Pcheeew. This was my **very first time** setting up an action. I had the problem that my HUGO repository
- built into a `public` sub-directory and
- I wanted this to end up in the root (or a test folder).
- But the action kept loading it into another  `public` directory on the server!

Well... actually it is solved. It just took me ages to fiddle around with the slashes, quotation marks and arguments :(

I now believe that it is the `/` at the end of the `local-dir:` path. But actually: I have no clue! It just works and I'm really scared to touch anything.

I was also playing around with the `git-ftp-args: --remote-root` until I saw @SamKirkland 's comment somewhere to just use the `ftp-server:` directly 👍 

- maybe this could have another example?
- examples for what the `./` actually does?
- use cases for `git-ftp-args: --remote-root` and examples?

**My Action Config**
```yaml
on:
  push:
      ...
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
          ftp-server: ${{ secrets.SERVER }}/domain.com/
          ftp-username: ${{ secrets.USER }}
          ftp-password: ${{ secrets.PW }}
          local-dir: public/
```

**Comment by sampletext32** [comment]
Hi, here is a little suggestion.
I use the following piece of yml.
Assume that your previous CI steps produced an artifact, named ```build```

```
upload:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Artifact 'build'
        uses: actions/download-artifact@master
        with:
          name: 'build'
          path: '${{ github.workspace }}/build'      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: '${{ secrets.FTP_SERVER }}'
          ftp-username: '${{ secrets.FTP_USERNAME }}'
          ftp-password: '${{ secrets.FTP_PASSWORD }}'
          local-dir: 'build/'
          git-ftp-args: '--all'
```
Create ```.git-ftp-include``` file in the root of your repo with the following content
```
!build/
```
everything should work out of the box.
