### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by Luzemin** [SamKirkland/FTP-Deploy-Action#116]
YML code:
```
name: Publish Website
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 3
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://47.95.206.69/docs/
        ftp-username: ftpuser
        ftp-password: ${{ secrets.FTP_PASSWORD }}
```
LOG:
```
git-ftp version 1.5.1 running on Linux bc11cf5be3b7 5.4.0-1031-azure #32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020 x86_64 GNU/Linux
Forced mode enabled.
Auto init if needed.
Using syncroot ./ if exists.
Host is '47.95.206.69'.
User is 'ftpuser'.
Password is set.
CACert is ''.
Insecure is '0'.
Proxy is ''.
Path is 'docs/'.
Syncroot is './'.
The remote sha1 is saved in file '.git-ftp.log'.
Check if curl is functional.
Retrieving last commit from ***47.95.206.69/docs/.
...
...
curl: (55) Send failure: Connection reset by peer
Mon Nov  9 15:15:22 UTC 2020: Check if ***47.95.206.69 is accessible.
```

But I can access my ftp server via explorer.exe or IE browser. Please help me, thank you very much!
