### ISSUE TITLE
exclude setting fails with array

### ISSUE THREAD

**Issue by AlexMayol** [SamKirkland/FTP-Deploy-Action#118]
**Bug Description**
I'm trying to add an array of globs to the `exclude` setting as stated in the docs.
I'm getting a YAML parse error every time. I've tried the following: 

```yaml
exclude: [".git*",".git*/**", "posts/**","node_modules/**", "node_modules/**/*", "documentation/**", ".vscode/**",".github/**"]
```

```yaml
  exclude: '[".git*",".git*/**", "posts/**","node_modules/**", "node_modules/**/*", "documentation/**", ".vscode/**",".github/**"]'
```

```yaml
  exclude: 
    - .git* 
    - .git*/** 
    - posts/** 
    - node_modules/** 
    - node_modules/**/* 
    - documentation/** 
    - .vscode/**
    - .github/**
```

It works when you pass a single file as a string, but that's not enough on this case.

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
   name: ⚡️ Build the assets and deploy project via FTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: 🏄‍♂️ Get latest code

      - uses: actions/setup-node@v2-beta
        name: 🤖 Setup Node.js 12
        with:
          node-version: "12"

      - name: 🔮 Build the project
        run: |
          npm install
          npm run prod

      - uses: SamKirkland/FTP-Deploy-Action@4.0.0
        name: 📂 Deploy files via FTP with FTP-Deploy-Action
        with:
          server: x
          username: xx
          password: xxx
          exclude: [".git*",".git*/**", "posts/**","node_modules/**", "node_modules/**/*", "documentation/**", ".vscode/**",".github/**"]

          log-level: verbose
          security: loose
          dry-run: true
```

**My Action Log**

Fails while parsing the `.yml` file, it never gets to execute the action.

Thank you very much!
