### ISSUE TITLE
Excluding files does not work

### ISSUE THREAD

**Issue by vvye** [SamKirkland/FTP-Deploy-Action#12]
I seem to be having trouble excluding files from the upload.

What I'd like to exclude is the .git and .github folders, as well as .htaccess. I also want to upload only the files that were changed in the commit. For the former I did as the Readme suggested, and the latter looks like it should be the default behavior now.

However, the action keeps uploading all of the files - even those I wanted to exclude, and even those that weren't changed.

Here's what my `main.yml` looks like:
```
on: push
name: Publish Website
jobs:
  fTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@master
      env:
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        ARGS: --exclude-glob=**/.git*/** --exclude-glob=**/.git** --exclude-glob=**/.htaccess
```
I also tried `--exclude=.git`, `--exclude=.htaccess` and `--only-newer` at various points, with no apparent effect.

There's probably something I'm doing wrong as I have no experience with lftp, but so far I'm clueless to what it could be.

Thanks for making this by the way, it's really helpful!
