### ISSUE TITLE
Can't upload sync-state file - getting 553 error

### ISSUE THREAD

**Issue by treetrum** [SamKirkland/FTP-Deploy-Action#120]
**Bug Description**
After the action successfully uploads all my files, it attempts to create the sync-state file, but fails and gives a 553 error saying:

```
Error 553 FileNameNotAllowed, you don't have access to upload that file
```

This happens when giving a custom file name as well.

I have tested in a traditional FTP client (Transmit) that I am able to create and edit a file with attempted filename and path. So it doesn't seem to be a permission issue with the credentials I am using.

**My Action Config**
```yaml
name: PROD Deploy

on:
  push: 
    tags: 
      - 'prod-*'

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:

    - name: Get latest code
      uses: actions/checkout@master

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: EXCLUDED_FOR_SECURITY
        local-dir: web/wp-content/themes/THEME_NAME/
        server-dir: wp-content/themes/THEME_NAME/
        username: ${{ secrets.PROD_FTP_USER }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        state-name: sync-state.json
```

**My Action Log**
```
| 🎉 Sync complete. Saving current server state to "wp-content/themes/THEME_NAME/sync-state.json"
| Error 553 FileNameNotAllowed, you don't have access to upload that file
| FTPError: 553 Can't open that file: No such file or directory
|     at FTPContext._onControlSocketData (/actions/SamKirkland-FTP-Deploy-Action@4.0.0/dist/index.js:3760:39)
|     at Socket.<anonymous> (/actions/SamKirkland-FTP-Deploy-Action@4.0.0/dist/index.js:3601:44)
|     at Socket.emit (events.js:203:13)
|     at addChunk (_stream_readable.js:294:12)
|     at readableAddChunk (_stream_readable.js:271:13)
|     at Socket.Readable.push (_stream_readable.js:210:10)
|     at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
|   name: 'FTPError',
|   code: 553
| }
| FTPError: 553 Can't open that file: No such file or directory
|     at FTPContext._onControlSocketData (/actions/SamKirkland-FTP-Deploy-Action@4.0.0/dist/index.js:3760:39)
|     at Socket.<anonymous> (/actions/SamKirkland-FTP-Deploy-Action@4.0.0/dist/index.js:3601:44)
|     at Socket.emit (events.js:203:13)
|     at addChunk (_stream_readable.js:294:12)
|     at readableAddChunk (_stream_readable.js:271:13)
|     at Socket.Readable.push (_stream_readable.js:210:10)
|     at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
|   name: 'FTPError',
|   code: 553
| }
```
