### ISSUE TITLE
Exclude parameter does not accept array

### ISSUE THREAD

**Issue by matthiasqu** [SamKirkland/FTP-Deploy-Action#122]
**Bug Description**
The readme says that for excluding files from being uploaded, an array has to be passed to the 'exclude' argument. The argument, however, takes a string. From the source it is obvious that a single string has to be passed that gets split by ' - ' chars. The following does not work.

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🚀 Deploy website every commit
    exclude: ['.git, *.txt] #expects a string instead
```

# Proposed solutions

Either add the string splitting to the readme (I'd be happy to do that) or change the source to expect an array instead of a string.
