### ISSUE TITLE
Exclude Array Fails to Deploy

### ISSUE THREAD

**Issue by PaulGeorgeTPJ** [SamKirkland/FTP-Deploy-Action#125]
**Bug Description**
Hi, can someone please explain how I can use an array of excluded files please? I've tried so many times and can only exclude one file at a time, not an array.

Below I'm just using the example and it fails to deploy everytime.

Thank you.

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.tpjcloud.co.uk
        username: videojs
        password: ${{ secrets.password }}
        exclude: [.git*, .git*/**, node_modules/**, node_modules/**/*]
```

**My Action Log**
```
Invalid workflow file
The workflow is not valid. .github/workflows/main.yml (Line: 17, Col: 18): A sequence was not expected
```
