### ISSUE TITLE
"Server sent FIN packet unexpectedly" Error when trying to deploy

### ISSUE THREAD

**Issue by TehMightyPotato** [SamKirkland/FTP-Deploy-Action#137]
Hi!
I'm trying to deploy a hugo project to a "webspace" aka. shared hosting (provider [ionos.de](https://ionos.de) in Germany).
The action fails with the same error every time I've tried it.
The secrets are 100% correct, I checked them multiple times while troubleshooting this.

I also tried some other actions available but they also failed for different reasons.

Any help would be appreciated!

My action.yaml looks like this:
```
name: publish
on:
  push:
    branches:
      - main # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.79.0
          extended: true

      - name: Build
        working-directory: ./tehmightypotato
        run: hugo --minify

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftphostname }}
          username: ${{ secrets.ftpusername }}
          password: ${{ secrets.ftppassword }}
          local-dir: tehmightypotato/public/
          port: 22
          dry-run: true
          log-level: verbose
```

The stacktrace:
```
Error: Server sent FIN packet unexpectedly, closing connection.
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3602:56)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
