### ISSUE TITLE
Can't Open data Connection in passive mode

### ISSUE THREAD

**Issue by sravan-kumar-sowlab** [SamKirkland/FTP-Deploy-Action#138]
// This is my script
```yaml
on: 
  push:
    branches: main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.sowlab.xyz
        username: ******************************
        password: **********************************
        port: 21
        protocol: ftp
        local-dir: ./
        server-dir: ./
```

// The Error I am getting was :
Error: Can't open data connection in passive mode: connect ETIMEDOUT 162.0.235.24:12065
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '162.0.235.24',
  port: 12065
}

# Please help me out as soon as possible

**Comment by SamKirkland** [comment]
Hello,

I've edited your comment to remove your credentials. Keep in mind these issues are public, so please update your ftp login username/password asap.

Because you provided your credentials I went ahead and ran a dry-run test against it. I had no issues using the following config on a github action. I'm going to go ahead and close this issue. Please re-test and if this issue occurs again we can reopen this issue.

```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.sowlab.xyz
        username: ******************************
        password: **********************************
```

**Comment by sravan-kumar-sowlab** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/72847001/100830233-2f14fa80-3489-11eb-98a6-2599defb1fc0.png)
Even me too can see the changes but most of the files are not uploading after the error with the attachment above persists.

**Comment by SamKirkland** [comment]
Hmmm it appears to be this issue: https://github.com/patrickjuchli/basic-ftp/issues/133

Currently I do not have support for setting the transfer mode of this action in an attempt to keep the config options as simple as possible.

I can look into adding it but no promises.

**Comment by cjdeclaro** [comment]
Hello! I am having the same issue as well. Is there a way around this?

```
on:
  push:
    branches:
      - master
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: my.ftpserver.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /staging/
```

Thanks a bunch!
