### ISSUE TITLE
so slow while copy a mount of files to server

### ISSUE THREAD

**Issue by serfend** [SamKirkland/FTP-Deploy-Action#140]
**Bug Description**
it seems very slow while project contains many file
i wonder if it can pack all file before upload,and unpack it on server
**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
     - name: deploy by ftp # i use `SamKirkland/FTP-Deploy-Action@4.0.0` for ftp deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0 # you can referer to github.com/SamKirkland/FTP-Deploy-Action for more infomation
        with:
          server: ${{ secrets.FTP_HOST }} # `${{arg}}` is a template from which you set in `secrets` menu
          username: ${{ secrets.FTP_USERNAME }} # as `yml` file is follow .git upload to github ,`secrets` is to prevent your sensitive infomation from exposed to public
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /app/wwwroot/
```

**My Action Log**
```
   # Paste Log here
   # you may want enable verbose logging with   log-level: verbose
```
