### ISSUE TITLE
FTP Failing

### ISSUE THREAD

**Issue by BenCoden** [SamKirkland/FTP-Deploy-Action#142]
**Bug Description**
When the FTP job runs it is failing almost instantly. I can not figure it out. I updated the secrets just to be sure and reran but it still failed. I can FTP just fine with FileZilla.

![image](https://user-images.githubusercontent.com/42153520/101558922-fcd63200-398d-11eb-8f65-2a7de721ee6e.png)

**My Action Config**
```yaml
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/

```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@4.0.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge

----------------------------------------------------------------
---------------  🔥🔥🔥 A error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  Full Error below  ----------------------
Error: getaddrinfo EAI_AGAIN *** (control socket)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: '***'
}
Error: Error: getaddrinfo EAI_AGAIN *** (control socket)
```
