### ISSUE TITLE
FTPS upload fails - action not failing

### ISSUE THREAD

**Issue by ChrisDoernen** [SamKirkland/FTP-Deploy-Action#144]
Hi there!

First of all, thanks for providing this great tool to the community! 
When using with FTP, all is good. This issue occurs when specifying FTPS as protocol, which I really want to do.

**Bug Description**
With the configuration below, the secure connection is established, a few files are uploaded, directories created but then the deploy fails after getting FTPError 450 three times. The deploy however is considered successful as the status of the action is green. I see the same behavior constantly when re-running the action, either with files or an empty directory on the server. I can connect to the server via FileZilla with explicit FTP over TLS and it works fine.

There are 2 parts to this:

1. I don't know why the upload fails and whether I can do anything to fix it - maybe it is a server issue.
2. As a user I'd like to have the deployment marked as failed in this situation, if that is possible.

Any help is appreciated - I hope I did not overlook something obvious.

**My Action Config**
```yaml
name: 🚀 Deploy website on push
on:
  push:
    branches:
      - development
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Append commit hash to version
      run: sed -i "5s/$/-$(git rev-parse --short HEAD)/" style.css

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }} 
        username: ${{ secrets.FTP_USER_CI_DEV }}
        password: ${{ secrets.FTP_PASSWORD_CI_DEV }}
        protocol: ftps
        log-level: verbose
```

**My Action Log**

[4_📂 Sync files.txt](https://github.com/SamKirkland/FTP-Deploy-Action/files/5676134/4_.Sync.files.txt)
