### ISSUE TITLE
Deleting Files tries to use `local-dir` on remote server

### ISSUE THREAD

**Issue by Luehrsen** [SamKirkland/FTP-Deploy-Action#145]
**Bug Description**
Deleting a file with `local-dir` defined does not actually delete the file. The script tries to delete the remote file with the `local-dir` prepended.

**My Action Config**
```yaml
      - name: 🚢 Deploy to Devserv
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.xxxxxxx.de
          username: xxxxx-xxxxx
          password: ${{ secrets.password }}
          local-dir: ./trunk/
          log-level: verbose
```

**My Action Log**
```
  file replaced
removing to-be-deleted.php...
> DELE ./trunk/to-be-deleted.php
< 550 Could not delete ./trunk/to-be-deleted.php: No such file or directory

  could not remove file. It doesn't exist!
  completed
```

The file `./trunk/to-be-deleted.php` obviously does not exist, the file should be `./to-be-deleted.php`.
