### ISSUE TITLE
Error: Error: EACCES: permission denied, open './_site/.ftp-deploy-sync-state.json'

### ISSUE THREAD

**Issue by hasko** [SamKirkland/FTP-Deploy-Action#146]
**Bug Description**
I'm running the ftp deploy action after a jekyll action. The directory and all files created by the previous action are owned by `root.root` and have `755` permission. I believe this is the default behavior of actions now. However, because of this, the ftp deploy action fails.

I've tried both the v4.0.0 and v4.0.1-patch versions of the action.

**My Action Config**
```yaml
- name: Deploy site
        uses: SamKirkland/FTP-Deploy-Action@4.0.1-patch
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password:  ${{ secrets.ftp_pw }}
          protocol: ftps
          local-dir: ./_site/
          server-dir: /something/
          dry-run: true 
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@4.0.1-patch
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy version 1.0.0. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Error: Error: EACCES: permission denied, open './_site/.ftp-deploy-sync-state.json'
```

**Comment by BourgeoisBenjamin** [comment]
I have the problem too

**Comment by llyorshch** [comment]
Quick'n'dirty workaround: 

Create in your repo a .ftp-deploy-sync-state.json file and set the state-name to `../.ftp-deploy-sync-state.json`

**Comment by kevquirk** [comment]
+1 here - also having this problem.

> Create in your repo a .ftp-deploy-sync-state.json file and set the state-name to `../.ftp-deploy-sync-state.json`

@llyorshch can you clarify what the contents on that file would look like for someone not familiar with json please?

**Comment by kevquirk** [comment]
Managed to get the upload to work by adding a file called `.ftp-delpoy-sync-state.json` in the `_site` folder with the following contents:

```
{ 
  "..." :  "../.ftp-deploy-sync-state.json"
}
```

**Comment by kevquirk** [comment]
Ignore my last comment, just add the following to your yml build file:

```
state-name: ../.ftp-deploy-sync-state.json
```

**Comment by llyorshch** [comment]
> +1 here - also having this problem.
> 
> > Create in your repo a .ftp-deploy-sync-state.json file and set the state-name to `../.ftp-deploy-sync-state.json`
> 
> @llyorshch can you clarify what the contents on that file would look like for someone not familiar with json please?

@kevquirk , I guess you already realized about it but just for the record. I think that it doesn't matter the contents of the file. In fact, I created an empty file. Probably, creating the file is only needed because the action cannot do it due to the permissions of the containing folder. I hope it helps.

**Comment by SamKirkland** [comment]
Hello,

I believe this is a duplicate of issue #145 which was resolved with the release of v4.1.0
Can someone on this thread test out v4.1.0 and verify the issue is resolved?

Thanks.

**Comment by vivi90** [comment]
@SamKirkland No, version `4.1.0` did not helped.
Instead this works fine: https://github.com/SamKirkland/FTP-Deploy-Action/issues/146#issuecomment-755294269

**Comment by nilsleiffischer** [comment]
I also have this issue with version 4.1.0, and the workaround https://github.com/SamKirkland/FTP-Deploy-Action/issues/146#issuecomment-755294269 fixed it.

**Comment by richardherbert** [comment]
I had the same issue but the following works for me. 

Context:

I am using the Static Site Generator (SSG) Eleventy (11ty) to process my source files into HTML with the action https://github.com/TartanLlama/actions-eleventy and then deploying the built files to my host using `FTP Deploy`. The following is my action:

```
name: Build and Deploy
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          args: --input ./src/
          install_dependencies: true

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_CONNECTION }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
          server-dir: ./public_html/
          state-name: ../.ftp-deploy-sync-state.json
```

Explanation:

For my 11ty project, all the config is in the root of the repo and the source files are located in the `./src/` directory hence the `--input` switch for `actions-eleventy`. By default, 11ty outputs the processed files into the `_site` directory and creates it if it doesn't exist. 

I think this point is critical as, for whatever reason (@SamKirkland ?), `FTP Deploy` tries to write it's `state-name` file (`.ftp-deploy-sync-state.json` by default) to the `local-dir` location which was created by the `actions-eleventy` process not the `FTP Deploy` process, hence the permissions write failure reported. The solution, as others have reported, is to set the `state-name` to the level above `local-dir` which exists as a result of the original repo checkout. Therefore setting the `state-name` value to `../.ftp-deploy-sync-state.json` resolves the write error. Unfortunately, it causes another issue for others.

With the `state-name` pointing to a level above the current working directory, this is also applied to the `server-dir` value. If the root of your FTP account is the directory that serves the website (webroot) you will not have write access to the level above, hence the error others have seen. The only solution is to have an FTP account with the root being a level above the webroot which, for me, is the `public_html/` directory. Therefore you need to specify `./public_html/` as the `server-dir` value to deploy your HTML to the right location to render your website to your visitors.
