### ISSUE TITLE
Stuck at "Uploading files..."

### ISSUE THREAD

**Issue by Salzian** [SamKirkland/FTP-Deploy-Action#15]
I tried your action, however the workflow always get's stuck at "Uploading files..." No error whatsoever even after 15 minutes. Just stuck.

See:
https://github.com/Salzian/website/runs/243656013

**Comment by SamKirkland** [comment]
Well that's not good!

Can you add the `--verbose` flag (see readme for directions) and re-run the script? It's likely having problems connecting with those FTP credentials.

Once you've added that flag I can take a look :smiley:

**Comment by Salzian** [comment]
The linked run above has the verbose flag. That's why I was wondering why I get no logs or error message.

**Comment by SamKirkland** [comment]
Can you respond with a copy of your yaml (.yml) file. Thanks

**Comment by Salzian** [comment]
```Yaml
name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: FTP deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@master
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: src
          REMOTE_DIR: staging
          ARGS: --delete --verbose
```

**Comment by Salzian** [comment]
I am using the SFTP protocol though. Not sure if that's the cause of the problem?

**Comment by SamKirkland** [comment]
> I am using the SFTP protocol though. Not sure if that's the cause of the problem?

Ah that's probably why. I haven't had a chance to test SFTP or FTPS yet. In theory FTPS will work fine, however SFTP is an entirely different protocol.
I'll look into it an see if I can get a solution working. In the meantime anyway you can use FTP for now?

My initial guess is the command line is prompting to accept an SSL cert and waiting for user input :(

**Comment by Salzian** [comment]
Good guess. I've beed looking at the repo and on the base you're just using lftp which should support SFTP by just changing the server url to `sftp://`.

Now that I got a clue ill try to find a solution as well and update you when I got something.

**Comment by SamKirkland** [comment]
yep `sftp:auto-confirm` as well

**Comment by Salzian** [comment]
I've now done quite a bit of testing with my own fork but I cannot get it to work. Locally it runs fine but on GitHub the action always gets stuck and doesn't run the lftp command.

**Comment by SamKirkland** [comment]
Well I threw a few hours at it and got it working. I've made a branch `SFTP_Beta` for testing it, i'll be removing this branch in the future when I merge these changing into `master`

Try the following.
```yaml
on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@SFTP_Beta
      env:
        FTP_SERVER: example.com
        FTP_USERNAME: usernameExample
        FTP_PASSWORD: password123
        PORT: 7822
        METHOD: sftp
        REMOTE_DIR: /home/teacherssalaries/teachers-salaries.com/sftp-git-action 
        ARGS: --verbose
```

**Comment by Salzian** [comment]
thank you very much for looking into this. I spend countless tries trying different syntaxes for lftp. I even looked into the command line `sftp` but that would've possibly required to switch from alpine to ubuntu. Judging by your commits on the branch it really didn't seem that trivial to get it to work. I will try your solution later and let you know how it went.

**Comment by Salzian** [comment]
https://github.com/Salzian/website/runs/247654133

Oh yes! Thank you so much! The beta branch works like a charm. I was going mad tryin to fix it myself but looking at the Dockerfile it seems that some additional packages where required. I guess for the secure connection. Thanks for your effort!

**Comment by SamKirkland** [comment]
I'm glad it's working.

I'll test the changes a bit more and then merge into `master`. I'd like to remove this branch eventually so I'll message you when I've merged the changes and you can switch back to `@master`

**Comment by Salzian** [comment]
Would be good to have a new version tag for this addition then. I like updating manually to avoid breaking updates.

**Comment by SamKirkland** [comment]
> Would be good to have a new version tag for this addition then. I like updating manually to avoid breaking updates.


I've merged into master and created a release v2.0.0
Since you aren't using the other branch I'll remove it.

**Comment by Salzian** [comment]
I saw it by chance today and already migrated the version tag into my workflows. Thank you very much for helping me out again. I got desperate getting it to work myself 😅

**Comment by SamKirkland** [comment]
Awesome!

Haha I was getting desperate aswell. As you can see I wasn't able to recreate on my local either so I had to make dozens of checkins.
Once I realized I had white-listed that server on my local it was pretty straightforward.

**Comment by gradisarjoze** [comment]
I'm having the same issue (stuck at Uploading files...). I've included `--verbose` to debug, but it's not outputting anything. I am using default ftp protocol. Any clues?

**Comment by SamKirkland** [comment]
> I'm having the same issue (stuck at Uploading files...). I've included `--verbose` to debug, but it's not outputting anything. I am using default ftp protocol. Any clues?

Hello! Can you reply with your configuration? Thanks.

**Comment by gradisarjoze** [comment]
> > I'm having the same issue (stuck at Uploading files...). I've included `--verbose` to debug, but it's not outputting anything. I am using default ftp protocol. Any clues?
> 
> Hello! Can you reply with your configuration? Thanks.

Hey. Below is my configuration.

```
on: 
  push:
    branches: 
      - master
name: Publish to test
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Installing dependencies
      run: |
        npm install
    - name: Building project
      run: |
        npm run build:prod
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: dist
        REMOTE_DIR: dist
        ARGS: --delete --dry-run --verbose --exclude=.ftpquota --exclude=.well-known
```
