### ISSUE TITLE
Include folder/files with version 4

### ISSUE THREAD

**Issue by kevinblackdesk** [SamKirkland/FTP-Deploy-Action#156]
Since version 4 doesn't use `.git-ftp-exclude` and `.git-ftp-include` anymore, is there a way to include files (ex: `dist` folder) to be uploaded when the `dist` folder is in the `.gitignore`?

I saw there was a way to exclude in the readme, but not to include.

How can you include files/folders in version 4?

**Comment by kevinblackdesk** [comment]
@SamKirkland

**Comment by SamKirkland** [comment]
Kevin sorry for the late reply.

v4 has no way to include a specific folder/file. v4 syncs everything that is in the working action folder to the server. Keep in mind this script doesn't read `.gitignore` at all. So it'll deploy whatever is in the working folder, in your case dist will be deployed as long as you create it.

**This is probably what you are doing**
For example if all you do is checkout your code it will upload exactly what's in source control
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    # At this point we got the latest code from source control. So we will upload exactly that
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.ftp_password }}
```


**This is what you want to be doing**
If you want to upload a `dist/` folder you should build that folder in the action before running the deploy action
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
    # Creates a dist folder
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    # Because we created the dist folder in the last step, the deploy action will see it and deploy it
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.password }}
```
