### ISSUE TITLE
Issue EXCLUDING folder from deploy

### ISSUE THREAD

**Issue by smtierney** [SamKirkland/FTP-Deploy-Action#157]
I am having issues excluding an entire folder from the repo as files are deployed.  I can ignore files/folders within it, but not the folder itself.  It lives at the root of the repo.  For example:

# deploy files to stage server via ftp
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 
          port: 21
          protocol: ftp
          username: 
          password: 
          local-dir: ./
          server-dir: deploytest/
          dry-run: false
          exclude:  /PRECOMP
            - config.codekit3
            - README.md
            - .git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*

That first exclude item, "PRECOMP", is never excluded and always winds up on the server.  I have tried:

./PRECOMP
/PRECOMP
PRECOMP/
PRECOMP/**

Any ideas?  I am probably missing something simple but I figured it was time to ask as I have wasted enough time troubleshooting.

**Comment by damianryann** [comment]
```
  - name: FTP Deploy
    uses: SamKirkland/FTP-Deploy-Action@4.0.0
    with:
      server: 
      port: 21
      protocol: ftp
      username: 
      password: 
      local-dir: ./
      server-dir: deploytest/
      dry-run: false
      exclude:  
        - PRECOMP/**
        - config.codekit3
        - README.md
        - .git*
        - .git*/**
        -  **/.git*/**
        - node_modules/**
        - node_modules/**/*
```

I think it might be how your listing, not tried but worth a shot
