### ISSUE TITLE
Files not deleting at the FTP

### ISSUE THREAD

**Issue by hmdshfq** [SamKirkland/FTP-Deploy-Action#162]
**Files not deleting at the FTP**
When I delete a file on the GitHub repository it doesn't get deleted at the ftp server.

**My Action Config**
```yaml
name: 🚀 Deploy website on push

on: 
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.****
        username: ****
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /wp-content/themes/my-theme/
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - node_modules/**
          - node_modules/**/*
          - .vscode/**
```
