### ISSUE TITLE
Error: getaddrinfo ENOTFOUND ftp.**********.cn (control socket)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {

### ISSUE THREAD

**Issue by Monster-hash** [SamKirkland/FTP-Deploy-Action#163]
My Action Config：

```
- name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.***********.cn
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pwd }}
          
          local-dir: ./build/
          server-dir: www/wwwroot/www.***********.cn/my-website/build/
 ```

My Action Log

```
----------------------------------------------------------------
---------------  🔥🔥🔥 A error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------
The server "ftp.***********.cn" doesn't seem to exist. Do you have a typo?

----------------------------------------------------------------
----------------------  Full Error below  ----------------------
Error: getaddrinfo ENOTFOUND ftp.***********.cn (control socket)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ftp.***********.cn'
}
Error: Error: getaddrinfo ENOTFOUND ftp.***********.cn (control socket)     
```
