### ISSUE TITLE
.ftp-deploy-sync-state.json doesn't update

### ISSUE THREAD

**Issue by crawler364** [SamKirkland/FTP-Deploy-Action#165]
**Bug Description**
On deploy, after deleting any file and folder .ftp-deploy-sync-state.json stops updating. And ftp deploy always do old actions on new deploy. Deleting .ftp-deploy-sync-state.json resolve the problem till next delete folder-file.

**My Action Config**
```yaml
on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: ${{ secrets.SERVERDIR }}
          exclude: .git*
            - .git*/**
            - node_modules/**
            - node_modules/**/*
            - .github/**
            - package-lock.json
            - .gitignore
            - .git-ftp-ignore
            - webpack.config.js
            - README.md
            - .babelrc
            - package.json
            - package-lock.json
            - postcss.config.js
```
