### ISSUE TITLE
Exclude files based on contents of the file

### ISSUE THREAD

**Issue by segdeha** [SamKirkland/FTP-Deploy-Action#167]
I’d love the ability to exclude or include files based on the contents of the file. What would work for me would be simple regex pattern matching such as:

    include:
        /#public/
    exclude:
        /#private/

Not even sure if this is possible, but I appreciate your consideration!

**Comment by SamKirkland** [comment]
This isn't possible today and I don't think I will be adding this feature.

However you can accomplish something similar by deleting the files prior to running the sync action. This action simply syncs the local folder to the server. So if you make a modification prior to running the action it will upload/not upload those changes.


Note: Untested example code below
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

   - name: Delete files I don't want to upload
     run: rm path/filename
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.ftp_password }}
```

You could modify this example code to [delete only files with specific content](https://superuser.com/questions/585391/on-linux-how-can-i-find-all-files-that-contain-a-string-and-delete-them)
