### ISSUE TITLE
bug: files are not uploaded in case content is big

### ISSUE THREAD

**Issue by webcat12345** [SamKirkland/FTP-Deploy-Action#171]
**Bug Description**
I tried to use this action for small projects like react.js and others and it's working well. But if I try with PHP legacy codebase, because it is legacy, we need to upload `vendor` folder to the server. Once we upload `vendor` the first time, I added `vendor` folder to exclude the list. Expectation was upload success without any issue, but only folders are uploaded and they are just empty.

**My Action Config**
```yaml
name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [prod]

jobs:
  bulid:
    name: Production Deployment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: .git*
            - .git*/**
            - vendor/*
          local-dir: "./"
          server-dir: "test_folder/"
          options: ""

      - name: Slack Notify
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

```

**My Action Log**

Action result is success - exit code 0. No logs here.
