### ISSUE TITLE
Error 550 when uploading sync-state file

### ISSUE THREAD

**Issue by yobson1** [SamKirkland/FTP-Deploy-Action#173]
**Bug Description**
The initial deployment went fine and everything was uploaded with these same settings. But now the sync-state file does not upload and fails with an access denied error. It still uploads the changes successfully, only the state file fails meaning it uploads the same changes it already uploaded along with any new ones every time but never updates the state file.

**My Action Config**
```yaml
on:
  push:
    branches:
      - master
name: 🚀 FTP Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: redacted
        port: 8855
        server-dir: /redacted/
        username: redacted
        password: ${{ secrets.ftp_password }}
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - .github/**
          - .gitignore
          - README.md
```

**My Action Log**
```
🎉 Sync complete. Saving current server state to "/redacted/.ftp-deploy-sync-state.json"
FTPError: 550 Access Denied.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3759:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3600:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Couldn't find file
FTPError: 550 Access Denied.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3759:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3600:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
```
