### ISSUE TITLE
3.1.1 - SFTP does not work

### ISSUE THREAD

**Issue by FlopRe** [SamKirkland/FTP-Deploy-Action#176]
I have tried using v3.1.1 as you suggested but I get error below, I can also see that your SFTP test run is failing in your readme - is this why my setup is failing? I have checked everything about 10 times now, watched tutorials, scrubbed through forums but everything looks to be right; yet it doesn't work. 
Of course I also tried running it without --insecure, or any args for that matter - it produces the same result. 
I very much appreciate your work and any help you may provide.

```
Uploading files
  /usr/bin/git ftp push --force --auto-init --verbose --syncroot=./public/ --user=*** --passwd=*** --dry-run --insecure sftp://***
  Fri Mar 19 10:37:11 UTC 2021: git-ftp version 1.5.1 running on Linux d75af2b7f84d 5.4.0-1040-azure #42-Ubuntu SMP Fri Feb 5 15:39:06 UTC 2021 x86_64 GNU/Linux
  Fri Mar 19 10:37:11 UTC 2021: Forced mode enabled.
  Fri Mar 19 10:37:11 UTC 2021: Auto init if needed.
  Fri Mar 19 10:37:11 UTC 2021: Using syncroot ./public/ if exists.
  Fri Mar 19 10:37:11 UTC 2021: fatal: Unrecognised option: sftp://***
Error: The process '/usr/bin/git' failed with exit code 3
```

main.yml:
```
on: push
name: 🚀 Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      
      - name: 📂 Sync GitHub files to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://***
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          git-ftp-args: --dry-run --insecure
```
