### ISSUE TITLE
Question: Upload w/o Sync

### ISSUE THREAD

**Issue by ryanfitzer** [SamKirkland/FTP-Deploy-Action#177]
First of all, thanks for the work on this action. Works pretty seamlessly.

My question is that I'm not seeing a way to disable the sync feature. Am I misreading the docs? Or is this not a feature?

My use case is to add source files without deleting any on the target (other than overwriting files with the same name). I'm uploading versioned directories:

```
server-dir/
    v1.0.0/
    v1.1.0/
    v2.0.0/
    [...]
```

The action only runs when a new version is released. The built `server-dir` only contains the most recent version, which I'd like to push to the server.

**Comment by SamKirkland** [comment]
Currently this action doesn't have a _upload only_ option. However if you modify the server deploy path you can recreate what you are looking for.

Assuming you [tag](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-tags) each version you can modify the folder you are deploying to!


#### Note - untested action below, This probably wont work without modifications:
```yaml
on:
  push:
    tags:
      - v*
name: 🚀 Deploy tagged version
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.password }}
        server-dir: ${GITHUB_REF##*/} # Not sure the correct way to get the tag name...
```
