### ISSUE TITLE
Transfers alle files without --transfer-all

### ISSUE THREAD

**Issue by riker187** [SamKirkland/FTP-Deploy-Action#18]
Hi,

i started to use this tool for deployment via SFTP. But even without the arg --transfer-all it always transfers ALL files and not just the changed ones. 

Jens

**Comment by SamKirkland** [comment]
Hello. It's unfortunately a known issue right now (see Issue #16)
As a temporary fix you can ignore times by adding `--ignore-time` to your ARGS

**Comment by riker187** [comment]
Works for me :) Thanks for the fast response. I love this plugin.

**Comment by SamKirkland** [comment]
Thanks! Glad you like it 😄

**Comment by Androjaner** [comment]
Hi @SamKirkland :)

I just would like to know, if there are any new solutions for this problem.
I tried the argument `--ignore-time` but it's still uploading all files :(

- Goran

**Comment by SamKirkland** [comment]
Hey @Androjaner

I've been working on a solution, I've had some early success uploading differences only using my rewrite of the project, I've been working on it under this fork: [FTP-Deploy-Action-Typescript](https://github.com/SamKirkland/FTP-Deploy-Action-Typescript)

I've had success on my websites but FTP is a finicky protocol and i'm a bit worried about FTP timezone issues. If you could give it a shot and let me know the results that would be very helpful.
Note: the typescript rewrite currently doesn't have SFTP support.

```yaml
on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action-Typescript@master
      env:
        FTP_SERVER: example.com
        FTP_USERNAME: username
        FTP_PASSWORD: password
        ARGS: --defaults --exclude-glob=.htaccess
```
