### ISSUE TITLE
Host keeps sending FTPError No Transfer-time exceeded and failing the deployment

### ISSUE THREAD

**Issue by Vicken52** [SamKirkland/FTP-Deploy-Action#181]
**Bug Description**
I'm using a game server host called zap-hosting, and with the magnitude of lua files, I wanted to use github and FTP Deploy to help make managing all these files a lot easier for me and my friend, but the hosting website decides to send `FTPError: 4*** No-transfer-time exceeded. Closing control connection.` every 2 minutes as a way to deal with lingering connections. Is there anyway to have FTP Deploy retry to connect in order to avoid these issues completely stopping the deployment?

My file changes are about 2 GBs and just normal FTP deploy takes between 30 minutes to an hour for all of them. I am fine to do that instead if I'm able to generate the state.json file myself and upload that to make future deployments short and clean.

**My Action Config**
```yaml
# This is a basic workflow to help you get started with Actions
name: FTP Deploy
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    # Runs a set of commands using the runners shell
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: ${{ secrets.ftp_port }}
        server-dir: /*****/gta5-fivem/server-data/
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - server.cfg
          - server.real.cfg
          - README.md
          - imgui.ini
          - essentialmode.db
          - db/**
          - cache/**
          - .vs/**
```

**My Action Log**
```
400 level error from server when performing action - retrying...
FTPError: 4*** No-transfer-time exceeded. Closing control connection.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3759:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3600:44)
    at Socket.emit (events.js:***0:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 4***
}
Error: Server sent FIN packet unexpectedly, closing connection.
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3602:56)
    at Socket.emit (events.js:***5:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:***)
```
