### ISSUE TITLE
Server closing connection - Requires KeepAlive type argument

### ISSUE THREAD

**Issue by NegativeStuff** [SamKirkland/FTP-Deploy-Action#182]
**Bug Description**
When connecting to my host (zap-hosting.com) I will receive the following before the transfer can complete.
On speaking with providers CS, they recommend a keep alive argument or detecting the disconnect and reconnecting.

Any way to keep the connection alive?

**My Action Config**
```yaml
on: push
name: 🚀 Deploy ForgeRP Resources on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: REDACTED
        port: REDACTED
        username: REDACTED
        password: ${{ secrets.ftp_password }}
        protocol: ftp
        server-dir: /RE/DAC/TED/
```

**My Action Log**
```
400 level error from server when performing action - retrying...
FTPError: 421 No-transfer-time exceeded. Closing control connection.
at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3759:39)
at Socket. (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3600:44)
at Socket.emit (events.js:210:5)
at addChunk (_stream_readable.js:309:12)
at readableAddChunk (_stream_readable.js:286:13)
at Socket.Readable.push (_stream_readable.js:224:10)
at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
name: 'FTPError',
code: 421
}
Error: Server sent FIN packet unexpectedly, closing connection.
at Socket. (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3602:56)
at Socket.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1184:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
