### ISSUE TITLE
How to deploy a specific branche?

### ISSUE THREAD

**Issue by ilonashairstyling** [SamKirkland/FTP-Deploy-Action#183]
**Bug Description**
I would like to learn how to deploy only a specific branche.
Adding the following doesn't seem to work:
on: push
    branches:
    - online-bestelling

**My Action Config**
```yaml
on: push
  branches:
    - development
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        server-dir: ${{ secrets.destination }}
```

**My Action Log**
```
Will not execute - error in yaml file.
```

**Comment by SamKirkland** [comment]
I believe your branches format is wrong. See [github workflow syntax](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-multiple-events-with-activity-types-or-configuration)

```yaml
on:
  push:
    branches:
      - online-bestelling
name: 🚀 Deploy website on push
# The rest of the action...
```

Can you try out the above change?
