### ISSUE TITLE
Github Actions Error: Timeout (data socket)

### ISSUE THREAD

**Issue by TarekMowafy** [SamKirkland/FTP-Deploy-Action#185]
**Bug Description**
I am running through an issue where my builds are not failing , but the content of the website on the server is not updated, when i checked the logs of the action builds i noticed that there is a timeout happening when 
Making changes to X files to sync server state
Uploading: 3.72 MB -- Deleting: 2.11 MB -- Replacing: 150 kB

**My Action Config**
```yaml
name: Deploy WEBSITE Dev
on:
  push:
    branches:
      - dev
jobs:
  Build-project:
    name: 🎉 Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: 🚚 Build
      run: |
        yarn install
        yarn build
        
    - name: List output files
      run: find public/ -print
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: gator2004.hostgator.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: /subdomain.placeholder.org/

```

**My Action Log**
```
Making changes to 82 files to sync server state
Uploading: 3.72 MB -- Deleting: 2.11 MB -- Replacing: 150 kB
----------------------------------------------------------------
creating folder "404/"
creating folder "page-data/404/"
creating folder "page-data/404.html/"
creating folder "page-data/dummypage/"
creating folder "dummypage/"
uploading "1bfc9850-d6c25717fec99bc12e24.js"
uploading "1bfc9850-d6c25717fec99bc12e24.js.map"
Error: Timeout (data socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3793:58)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket._onTimeout (net.js:469:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: Timeout (data socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3793:58)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket._onTimeout (net.js:469:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
----------------------------------------------------------------
Time spent hashing:               154 milliseconds
Time spent connecting to server:  1.6 seconds
Time spent deploying:             1 minute 2.2 seconds (62.1 kB/second)
  - changing dirs:                1.4 seconds
  - logging:                      6 milliseconds
----------------------------------------------------------------
Total time:                       1 minute 4.8 seconds
```
