### ISSUE TITLE
ECONNRESET (control socket) in internal/stream_base_commons.js:201:27

### ISSUE THREAD

**Issue by phyle** [SamKirkland/FTP-Deploy-Action#192]
**Bug Description**
Until May 12, I was able to successfully use FTP-Deploy daily and it worked great! (Thanks!)  Suddenly, I now always receive ECONNRESET errors every time the action runs.  The FTP connection with the same credentials works well with FileZilla and other local clients.  I know the Actions yml file, the related Secrets (I even reset them), and the the version 4.0.0 of FTP-Deploy did not change so it's probably an issue with our hosting (GoDaddy).  I added verbose logging but it doesn't tell much more...  I've read somewhere that others fixed similar tools having this error by setting keep-alive=false, but I don't think we have this option for FTP-Deploy. Can you please hint me what could be the cause and/or how to fix that? Thanks.

**My Action Config**
```yaml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
          
#[...] build hugo site

      - name: 📂 Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: <REDACTED>
          username: ${{ secrets.ftpuser }}
          password: ${{ secrets.ftppassword }}
          local-dir: <REDACTED>
          server-dir: <REDACTED>
          protocol: ftps
          log-level: verbose
```

**My Action Log**
```

Run SamKirkland/FTP-Deploy-Action@4.0.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Creating local state at <REDACTED>/.ftp-deploy-sync-state.json
Local state created
Connected to ***:21 (No encryption)

----------------------------------------------------------------
---------------  🔥🔥🔥 A error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  Full Error below  ----------------------
Error: read ECONNRESET (control socket)
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: Error: read ECONNRESET (control socket)
```
