### ISSUE TITLE
Similar issue as in #137: "Server sent FIN packet unexpectedly"

### ISSUE THREAD

**Issue by freakyshine** [SamKirkland/FTP-Deploy-Action#197]
**Bug Description**
Just like in #137 I'm not able to deploy to the FTP server however, I'm confident my hosting provider provides a ftp (port 21) and a sftp (port 5544).
When using Filezilla with the credentials stored in the secrets it works as it should, but not with the action.

**My Action Config**
```yaml
on:
  push:
    branches:
      - main
name: 🚀 Deploy to production
jobs:
  web-deploy:
    name: 🎉 Prod Deployment
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user_prod }}
        password: ${{ secrets.ftp_password_prod }}

```

**My Action Log**
```
   Run SamKirkland/FTP-Deploy-Action@4.0.0
  with:
    server: ***
    username: ***
    password: ***
    log-level: verbose
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Creating local state at ./.ftp-deploy-sync-state.json
Local state created
Connected to 116.202.46.46:21 (No encryption)

----------------------------------------------------------------
---------------  🔥🔥🔥 A error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  Full Error below  ----------------------
Error: Server sent FIN packet unexpectedly, closing connection.
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3602:56)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Error: Error: Server sent FIN packet unexpectedly, closing connection.
```
