### ISSUE TITLE
Cannot connect to FTP server

### ISSUE THREAD

**Issue by vladislav-naydenov** [SamKirkland/FTP-Deploy-Action#199]
**Bug Description**
When the FTP job runs it fails right away. I can't figure out what the issue is. I can login to the FTP server using file zilla or any other ftp client.

**My Action Config**
```yaml
- name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with: 
        server: ${{ secrets.FTP_SERVER_URL }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ${{ env.WORKING_DIRECTORY }}/smileonwebapp/
        server-dir: staging/
        dangerous-clean-slate: true
```

**My Action Log**
```
  Run SamKirkland/FTP-Deploy-Action@4.0.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge

----------------------------------------------------------------
---------------  🔥🔥🔥 A error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  Full Error below  ----------------------
Error: getaddrinfo EAI_AGAIN ftp.site4now.net (control socket)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'ftp.site4now.net'
}
Error: Error: getaddrinfo EAI_AGAIN ftp.site4now.net (control socket)
```
