### ISSUE TITLE
Workflow not valid: A sequence was not expected

### ISSUE THREAD

**Issue by vivi90** [SamKirkland/FTP-Deploy-Action#200]
I try to use the following action configuration:
```yaml
      # Deploy the project
      - name: Deploy 🚀
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        if: success()
        with:
          log-level: verbose
          security: loose
          protocol: ftps
          port: 990
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: web/CLIENT/PROJECT/Build/
          state-name: .deploy-sync-state.json
          local-dir: Build/
          exclude:
            - .htaccess
            - index.html
```
But i get the error:
```
The workflow is not valid. .github/workflows/unity-ci.yml (Line: 119, Col: 13): A sequence was not expected
```
Right after the line: 
```
            - .htaccess
 ```
What i am doing wrong here?
Used this example: https://github.com/SamKirkland/FTP-Deploy-Action#exclude-files
Tested also with action version `4.1.0` but no change.
Also tested to use quotes:
```yaml
            - ".htaccess"
            - "index.html"
```
But same behaviour.

**Comment by SamKirkland** [comment]
I'm pretty sure your `if: success()` condition is wrong. The way you have this setup its trying to parse the entire ftp-deploy action within the `if`.

You should add a comparison operator to the if block like so
`if: success() == "true"` (note: untested)

I'm closing this ticket for now, but leave a comment to update me on the issue and I can reopen if needed 👍

**Comment by maximilianschmidt** [comment]
i am getting the same error right after the first excluded folder since i added `exclude` to the workflow file: 

```
      - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.user }}
        password: ${{ secrets.password }}
        exclude:
          - .github/
          - .git/
          - .babelrc
          - .editorconfig
          - .eslintrc
          - .prettierrc
          - .stylelintrc
          - /build
```
