### ISSUE TITLE
exclude option - syntax is wrong in the readme

### ISSUE THREAD

**Issue by benwainwright** [SamKirkland/FTP-Deploy-Action#202]
**Bug Description**
"Sequence is not expected" when I add an "exclude" key with multiple entries

**My Action Config**
```yaml
      - name: Upload Files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server-dir: (path on server)
          exclude:
            - "**/node_modules/**"
            - .git/**
            - .cache-loader/**
          log-level: verbose
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

```

**My Action Log**
```
The workflow is not valid. .github/workflows/deploy-to-staging.yaml (Line: 31, Col: 13): A sequence was not expected
```

**Comment by juliamenndez** [comment]
Hi!

I was having the same issue. I removed the '-' preceding each item and it worked!

Regards.

**Comment by maximilianschmidt** [comment]
when removing the `-` the error is gone but the desired folders aren't excluded anymore, at least for me. 😕

**Comment by vivi90** [comment]
@SamKirkland Seems to be the same issue like here: https://github.com/SamKirkland/FTP-Deploy-Action/issues/200

**Comment by benwainwright** [comment]
@maximilianschmidt this works for me; you are a star. I'll leave the issue open as the bug as described is still present but I'm gonna unfollow.

**Comment by DemianX0** [comment]
@maximilianschmidt Thanks for the solution!

There are two convenient ways to write it, both syntax handled properly by the action.
With square brackets - the separator is `, `:
```
        exclude: '[
        , **/.git*/**
        , **/node_modules/**
        , **/build/
        , .babelrc
        , .editorconfig
        , .eslintrc
        , .prettierrc
        , .stylelintrc
        ]'
```

Without square brackets - note the separator is ` - `:
```
        exclude: '
        - **/.git*/**
        - **/node_modules/**
        - **/build/
        - .babelrc
        - .editorconfig
        - .eslintrc
        - .prettierrc
        - .stylelintrc
        '
```

GitHub actions API does not handle yaml lists, only strings, thus the need to pass a string which is then split into individual globs.
The function that parses it:
https://github.com/SamKirkland/FTP-Deploy-Action/blob/65c6a8f943bbf04faf9b59520a103318b418952e/src/parse.ts#L102
https://github.com/SamKirkland/FTP-Deploy-Action/blob/65c6a8f943bbf04faf9b59520a103318b418952e/src/parse.ts#L106

README.md could be updated to reflect one of these syntaxes.

**Comment by SamKirkland** [comment]
I have a beta branch deployed that uses the new format.

To use the beta branch you can use the following:
`uses: SamKirkland/FTP-Deploy-Action@v4.2.0-beta`
**Note: This branch will be removed once this change is merged**

Any feedback/testing is welcome.

**Comment by philharmonie** [comment]
What is the latest way of working code in the master?
I got my script but is not excluding a single line:
```
on:
  push:
    branches:
      - testserver
name: 🚀 Deploy app to test server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.myserver.com
          username: d0123456
          password: ${{ secrets.ftp_password }}
          exclude: |
            **/node_modules/**
            **/.git
            **/.github
            ./tests/**
            ./vendor/**
            ./writeable/**
```

Same for 
```
          exclude: 
            - **/node_modules/**
            - **/.git
            - **/.github
            - ./tests/**
            - ./vendor/**
            - ./writeable/**
```
