### ISSUE TITLE
`chmod +x` change is not detected

### ISSUE THREAD

**Issue by feyst** [SamKirkland/FTP-Deploy-Action#209]
**Bug Description**
When I only change the mode of a file (`chmod +x ./src/file`), then commit the change and push it. 
The ftp script does not seem to recognice the change. and does not alter the destination file mode.

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_host }}
          protocol: ftps
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}```

**My Action Log**
```
⚖️  File content is the same, doing nothing: src/file
```
