### ISSUE TITLE
Exclude parameter does not seem to work

### ISSUE THREAD

**Issue by ggPixel** [SamKirkland/FTP-Deploy-Action#211]
**Bug Description**
I'm trying to exclude certain files and folders but it doesn't seem to work. I have tried using all methods (string with array, string with YAML lists, and also removing the double asterisk for LFTP) but nothing works. Question is does it always exclude files and folders when you specify them or only when they don't exist locally?

I followed this https://github.com/SamKirkland/FTP-Deploy-Action/issues/12 and this https://github.com/SamKirkland/FTP-Deploy-Action/pull/205 but didn't work for me.

The biggest problem I have is that the action runs for over an hour and fails every time with a FIN error and so the json file does not get created and the workflow has to resync all files again.

I have 3 other repos with the exact same action and they work 100%. (each deploying in its own folder)

Any help would be appreciated.

**My Action Config**
```
name: Custom CI FTP deployment for plugins
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_DEPLOY_KEY }}
        password: ${{ secrets.FTP_DEPLOY_SECRET }}
        server-dir: public_html/wp-content/plugins/
        exclude: '["/excel-module/**", "/vendor/**", "/.git/", "/.git*", "/.git*/**", "/.git*/**", "/ctu-emit-chatbot/**", "/cloud-campus/**", "/akismet/**", "/all-in-one-wp-security-and-firewall/**", "/classic-editor/**", "/cloudflare/**", "/contact-form-7*/**", "/git-updater/**", "/jwt-auth/**", "/listo/**", "/PayWeb_WooCommerce-master/**", "/pixel-caffeine/**", "/regenerate-thumbnails/**", "/supportcandy/**", "/tinymce-advanced/**", "/w3-total-cache/**", "/wc-variations-radio-buttons/**", "/woocommerce*/**", "/wordpress-seo/**", "/wordpress-social-login/**", "/wp-live-chat-software-for-wordpress/**", "/wp-responsive-menu/**", "/wp-smushit/**", "/yith-woocommerce-product-add-ons/**", "/yith-woocommerce-subscription/**"]'
```

**My Action Log** (excerpt, log is huge)
```
----------------------------------------------------------------
Making changes to 6358 files/folders to sync server state
Uploading: 221 MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder ".git/"                     <---- This folder and below should be ignored
creating folder ".git/branches/"
creating folder ".git/hooks/"
creating folder ".git/info/"
creating folder ".git/logs/"
creating folder ".git/logs/refs/"
creating folder ".git/logs/refs/heads/"
creating folder ".git/logs/refs/remotes/"
creating folder ".git/logs/refs/remotes/origin/"
creating folder ".git/objects/"
creating folder ".git/objects/info/"
creating folder ".git/objects/pack/"
creating folder ".git/refs/"
creating folder ".git/refs/heads/"
creating folder ".git/refs/remotes/"
creating folder ".git/refs/remotes/origin/"
creating folder ".git/refs/tags/"
creating folder ".github/"
creating folder ".github/workflows/"
creating folder "ctu-badges/"
creating folder "ctu-courses/"
creating folder "ctu-courses/inc/"
creating folder "ctu-courses/inc/icas-api/"
creating folder "ctu-crm/"
creating folder "ctu-crm/inc/"
creating folder "ctu-crm/inc/data/"
creating folder "ctu-crm/inc/excel-module/" <---- Same here, this folder and below should be ignored
creating folder "ctu-crm/inc/excel-module/src/"
creating folder "ctu-crm/inc/excel-module/src/PhpSpreadsheet/"
creating folder "ctu-crm/inc/excel-module/src/PhpSpreadsheet/Calculation/"
creating folder "ctu-crm/inc/excel-module/src/PhpSpreadsheet/Calculation/Engine/"

...

Error: Server sent FIN packet unexpectedly, closing connection.
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3602:56)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Error: Server sent FIN packet unexpectedly, closing connection.
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3602:56)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
----------------------------------------------------------------
Time spent hashing:               3.3 seconds
Time spent connecting to server:  2.5 seconds
Time spent deploying:             59 minutes 55.6 seconds (62 kB/second)
  - changing dirs:                39 minutes 59.6 seconds
  - logging:                      172 milliseconds
----------------------------------------------------------------
Total time:                       1 hour 4.5 seconds
```
