### ISSUE TITLE
Adding SFTP support? 

### ISSUE THREAD

**Issue by Olzie-12** [SamKirkland/FTP-Deploy-Action#213]
**Bug Description**
Why is SFTP no longer supported on the latest version?
I know you can use a previous version to use SFTP but I'd prefer to use the latest version with SFTP.

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
      - name: Deploy resources
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          local-dir: PlayerWarps-Plugin/src/main/resources/configuration/
          server-dir: /var/www/html/playerwarps/configuration/
          server: cdn.olziedev.com
          username: ${{secrets.FTP_USERNAME_CDN}}
          password: ${{secrets.FTP_PASSWORD_CDN}}
          port: 2022
```
