### ISSUE TITLE
Deploying specific branch

### ISSUE THREAD

**Issue by lyzio** [SamKirkland/FTP-Deploy-Action#215]
Looked in the files and the syntaxes and tried to see if there was a way to deploy a specific branch when the action is located in the master branch but could not find any.

So if I have missed this please enlighten me, otherwise is there a workaround or is this a feature that might be implemented in the future?

**Comment by SamKirkland** [comment]
Hey @lyzio 

Github actions have a built-in way of targeting branches.
Read more about it on the [workflow syntax reference](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)

You probably want something like this:
```yaml
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
      # Push events to branches matching refs/heads/mona/octocat
      - 'mona/octocat'
      # Push events to branches matching refs/heads/releases/10
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - v1             # Push events to v1 tag
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags
```

**Comment by michelvanheest** [comment]
For people who're looking for an example with right indentation in the future:

```
name: 🚀 Deploy website on push
on: 
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ...
        username: ...
        password: ...
        local-dir: ./_site/
        server-dir: ...
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          **/*.DS_Store
```
