### ISSUE TITLE
error when removing folder or file that not exist

### ISSUE THREAD

**Issue by WorkAttackDev** [SamKirkland/FTP-Deploy-Action#218]
**Bug Description**
I use next.js with a custom server, and i build and deploy to my server using actions. But always occurs this error where they can't find i file or folder and instead of ignore because when i build a next.js it generate and remove some file, throw an exception.
have a way to ignore or silence some errors.

**My Action Config**
on:
  push:
    branches:
      - main
name: 🚀 Deploy workattack frontend
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: 🔨 Build Project
        run: |
          npm run boot
          npm run build:front
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{secrets.ftp_host}}
          username: ${{secrets.ftp_user}}
          password: ${{ secrets.ftp_password }}
          local-dir: ./packages/next-app/
          server-dir: ./workattack_frontend/
          dangerous-clean-slate: false

**My Action Log**

removing "public/images/packages/programming.jpg"
removing folder ".next/static/A0skO_UhpkfdlsMF7orUt/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't remove directory: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Can't remove directory: No such file or directory

**Comment by andre-lergier** [comment]
I get the same error with my **Nuxt.js** application since I updated to FTP-Deploy-Action Version 4. Using Version 3.1.1 always worked for me.

Here's my error:
```sh
FTPError: 550 Can't remove directory: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Can't remove directory: No such file or directory
```

Deleting the file `.ftp-deploy-sync-state.json` on the server solved it for one deploy.

My action looks like this:
```yml
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2
        
      - name: ⚙️ Nuxt generate
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        run: |
          npm install
          npm run generate
        
      - name: 📂 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
```
