### ISSUE TITLE
Error while deploying static Nuxt.js page

### ISSUE THREAD

**Issue by andre-lergier** [SamKirkland/FTP-Deploy-Action#219]
**Bug Description**
If I try to deploy my static Nuxt.js page the FTP-Deploy-Action always fails with the same error. Using Version 3.1.1 or after deleting the file `.ftp-deploy-sync-state.json` on the server the deployment works fine.
To update the Version to v4 I followed this [Migration Guide](https://github.com/SamKirkland/FTP-Deploy-Action/blob/master/migration.md).

**My Action Config**
```yml
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v2
        
      - name: ⚙️ Nuxt generate
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 🔨 Generate site
        run: |
          npm install
          npm run generate
        
      - name: 📂 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
```

**My Action Log**
```sh
...
----------------------------------------------------------------
Local Files:	271
Server Files:	271
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
...
----------------------------------------------------------------
Making changes to 126 files/folders to sync server state
Uploading: 1.14 MB -- Deleting: 1.14 MB -- Replacing: 6.12 MB
----------------------------------------------------------------
...
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't remove directory: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Can't remove directory: No such file or directory
```
