### ISSUE TITLE
Specify branch

### ISSUE THREAD

**Issue by sebastienserre** [SamKirkland/FTP-Deploy-Action#22]
Hello,

Is it possible to specify a branch to follow?

**Comment by jay-oswald** [comment]
You can set up your github workflow to specify the branch that you want to deploy.

e.g. this is my script for deploying

```
name: Deploy - Master

on:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Yarn Install
        run: yarn
      - name: Yarn Build Production
        run: yarn prod
      - name: Clean for Deploy
        run: |
          rm -r node_modules/
          rm -r .github/
          rm -r .git/
          rm .eslintrc.js
          rm .gitignore
          rm .stylelintrc.js
          rm .stylelintignore
          rm yarn.lock
      - name: Deploy to Server - FTP
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.DEPLOY_MASTER_FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.DEPLOY_MASTER_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.DEPLOY_MASTER_FTP_PASSWORD }}
          REMOTE_DIR: ${{ secrets.DEPLOY_MASTER_FTP_REMOTE_PATH }}
          ARGS: --delete
```

Up the top is where you define what branch it happens on, if you want to deploy multiple branches you can have multiple workflow scripts. Like I have a 2nd script for deploying from the staging branch to the staging environment
