### ISSUE TITLE
Fail when conditions are not set

### ISSUE THREAD

**Issue by CHEWX** [SamKirkland/FTP-Deploy-Action#224]
**Bug Description**
When doing this, if the files do not go into the `public_html` folder, then the build should fail, I am getting deployments being uploaded to the root and not `public_html`, not sure why it doesn't fail if it's not going into `public_html`

```yaml
      with:
        server-dir: public_html/
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
```

**Comment by SamKirkland** [comment]
It looks like you are using some options from the latest version (version 4+) but also have a few options from version 3 (legacy version).

In your case it looks like you are actually using version 3, but are also using the `server-dir` option which is from version 4.

You probably should upgrade to version 4, if you need version 3 for SFTP support I assume you want something like this instead:
```yaml
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}/public_html/ # no idea what your FTP_SERVER is here. This could result in a double //. You should either update your secrete to include the full path. Or just hard-code the FTP_SERVER here
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
```

Docs:
- [Version 3](https://github.com/marketplace/actions/ftp-deploy?version=3.1.1)
- [Version 4](https://github.com/marketplace/actions/ftp-deploy?version=4.1.0)
