### ISSUE TITLE
Only send files that have been modified. 

### ISSUE THREAD

**Issue by JonhnyDev** [SamKirkland/FTP-Deploy-Action#227]
I'm using version 3.0.0 because 4.1 doesn't work on aws returns "timeout" error probably because i use sftp.
in 3.0.0 it works perfectly but I would like to know if there is a way to send only the modified files, currently it sends all files from the repository, I would like it to be only the modified files that were committed 

It is currently uploading all files from the repository except the files that are in the ".git-ftp-ignore" but I only want the files that have been modified

configs:
```
on: 
  push:
    branches:
      - main
name: 🚀 Deploy API plataforma Oficial
jobs:
  sv1:
    name: 🎉 Deploy SERVIDOR OFICIAL 1
    runs-on: ubuntu-latest
    environment:
      name: sv1
      url: http://sv1.chatcomposer.com
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_HOST_SV1 }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args:
          --insecure
```
