### ISSUE TITLE
Sync file is created on ftp root level instead of in the specified server-dir folder

### ISSUE THREAD

**Issue by samuelT2** [SamKirkland/FTP-Deploy-Action#231]
**Bug Description**
When running an action, the ".ftp-deploy-sync-state.json" file is created/updated on ftp root level instead of in the specified server-dir folder.

**My Action Config**
```yaml
name: xx.xx.xx / TEST deployment

on:
  push:
    branches: [ dev_integration ]
  pull_request:
    branches: [ dev_integration ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: |
          npm install

      - name: npm build standalone
        run: |
          npm run build -- --mode staging
          
      - name: FTP Deploy (Staging)
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: xx.xx
          username: xx@xx.xx
          password: ${{ secrets.FTP_DEPLOYMENT_USER }}
          local-dir: ./dist/
          server-dir: 0807_test_admin_Bigbites.ch/

```

Let me know if the full action is log is also needed.
