### ISSUE TITLE
TLS security issue

### ISSUE THREAD

**Issue by toledox82** [SamKirkland/FTP-Deploy-Action#234]
**Bug Description**
I having issue with cPanel TLS security for FTP connection.

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        security: strict
```

**My Action Log**
```
FTPError: 421-Sorry, cleartext sessions and weak ciphers are not accepted on this server.
421 Please reconnect using TLS security mechanisms.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 421
}
Error: FTPError: 421-Sorry, cleartext sessions and weak ciphers are not accepted on this server.
421 Please reconnect using TLS security mechanisms.
```

**Comment by Dandix3** [comment]
i have the same problem. Did u solve it ?

**Comment by renehamburger** [comment]
@toledox82, did you try `protocol: ftps` or `protocol: ftps-legacy`?

**Comment by shamimbdpro** [comment]
![image](https://user-images.githubusercontent.com/39990205/197452846-c73d0aa1-2cc4-496e-aecc-d925f57b6b93.png)
Same Issue for me

**Comment by samfrank** [comment]
Adding `protocol: ftps` and `security: loose` worked for me to solve the same issue

**Comment by iyinusa** [comment]
Adding `protocol: ftps` only works for me.

**Comment by saifulsaif** [comment]
where I should added **protocol: ftps** I have still the issue

**Comment by saifulsaif** [comment]
> 

where should add them? please help I have same issue

**Comment by awsajidhussain** [comment]
Put ftps in the following manner
```
...
with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
```
