### ISSUE TITLE
Exclude gets an error in the syntax

### ISSUE THREAD

**Issue by nabsba** [SamKirkland/FTP-Deploy-Action#235]
**Bug Description**
Exclude doesn't work as the syntax seems wrong

**My Action Config**
```yaml

on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: 📂 Sync files frontend
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.mywebsite.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /test/
        exclude:
          - **/src/**
          - **/node_modules/**
          
```

**My Action Log**
```
Invalid workflow file
You have an error in your yaml syntax on line 19
```
