### ISSUE TITLE
Cannot connect using 3.1.1

### ISSUE THREAD

**Issue by Olzie-12** [SamKirkland/FTP-Deploy-Action#238]
**Bug Description**
For some reason, now when i try and deploy my files, it doesn't allow me to and it says something to do with cannot connect. It was working beforehand and now it doesn't work, it doesn't work for this specific host but it use to and it works just fine on my filezilla which is weird.

**My Action Config**
```yaml
name: Maven
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-:
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          local-dir: target/
          ftp-server: sftp://ca03.tekknodes.com:2022/jars
#           git-ftp-args: --insecure
          ftp-username: ${{secrets.FTP_USERNAME}}
          ftp-password: ${{secrets.FTP_PASSWORD}}
```

**My Action Log**
```
  /usr/bin/git ftp push --force --auto-init --verbose --syncroot=target/ --user=*** --passwd=***  sftp://ca03.tekknodes.com:2022/jars
  Fri Oct 29 16:21:04 UTC 2021: git-ftp version 1.5.1 running on Linux 2df6e0c23fa3 5.8.0-1042-azure #45~20.04.1-Ubuntu SMP Wed Sep 15 14:24:15 UTC 2021 x86_64 GNU/Linux
  Fri Oct 29 16:21:04 UTC 2021: Forced mode enabled.
  Fri Oct 29 16:21:04 UTC 2021: Auto init if needed.
  Fri Oct 29 16:21:04 UTC 2021: Using syncroot target/ if exists.
  Fri Oct 29 16:21:04 UTC 2021: Host is 'ca03.tekknodes.com:2022'.
  Fri Oct 29 16:21:04 UTC 2021: User is '***'.
  Fri Oct 29 16:21:04 UTC 2021: Password is set.
  Fri Oct 29 16:21:04 UTC 2021: CACert is ''.
  Fri Oct 29 16:21:04 UTC 2021: Insecure is '0'.
  Fri Oct 29 16:21:04 UTC 2021: Proxy is ''.
  Fri Oct 29 16:21:04 UTC 2021: Added missing trailing / in path.
  Fri Oct 29 16:21:04 UTC 2021: Path is 'jars/'.
  Fri Oct 29 16:21:04 UTC 2021: Syncroot is 'target/'.
  Fri Oct 29 16:21:04 UTC 2021: The remote sha1 is saved in file '.git-ftp.log'.
  Fri Oct 29 16:21:04 UTC 2021: Check if curl is functional.
  Fri Oct 29 16:21:04 UTC 2021: Retrieving last commit from ***ca03.tekknodes.com:2022/jars/.
  #=#=#                                                                         
  ##O#- #                                                                       
  curl: (2) Failure establishing ssh session: -5, Unable to exchange encryption keys
  Fri Oct 29 16:21:04 UTC 2021: Check if ***ca03.tekknodes.com:2022 is accessible.
  #=#=#                                                                         
  ##O#- #                                                                       
  curl: (2) Failure establishing ssh session: -5, Unable to exchange encryption keys
  Fri Oct 29 16:21:05 UTC 2021: fatal: Can't access remote '***ca03.tekknodes.com:2022', exiting...
Error: The process '/usr/bin/git' failed with exit code 5
✅ Deploy Complete
```

Maybe any help finding what the issue is please
