### ISSUE TITLE
Does not work if password has a space at the end.

### ISSUE THREAD

**Issue by AllenKll** [SamKirkland/FTP-Deploy-Action#239]
**Bug Description**
Login to server fails if password has a space at the end.  Possibly, if password has spaces in the middle.  this may be an issue with github secrets, not this plugin, but I can find no information on it.

**My Action Config**
```yaml
      - name: Sync to Server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: myserver.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: /public_html/
```

**My Action Log**
```
FTPError: 530 Login authentication failed
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 530

```
