### ISSUE TITLE
Does this action no more place a "git-ftp.lck" file?

### ISSUE THREAD

**Issue by xannasavin** [SamKirkland/FTP-Deploy-Action#242]
**Bug Description**

In the past, I noticed that the deploy action was placing a "git-ftp.lck" file in the folder of deployment.
I made use of this and built some automatisms, that put pages into maintenance mode when this file is present.
However, today during deployment, I noticed that no such file was placed anymore... 

Was something changed, do I miss something?

**My Action Config**
```yaml
# https://github.com/marketplace/actions/ftp-deploy
# 31.05.2021

name: 🚀 Deploy website on push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - .github/*
          - .gitignore
          - */.gitignore
          - */.gitkeep
          - .gitlab-ci.yml
          - readme.md
          - *.md
          - /logs/*  
          - /upgrade/*
          - /uploads/*
          - /languages/*
          - /updraft/*
          - /cache/*  
          - *.scss
          - */.idea/
          - */dev-src/
          - prepros.config
          - *.map
```

**Comment by xannasavin** [comment]
it seems this does not happen since something longer. maybe with the new update - can't tell, the time I built those mechanisms is quite some time ago and I just noticed today ><

Is there any way I can tell the action to place such file in the beginning and remove it afterwards? Would be really helpfull...

**Comment by SamKirkland** [comment]
v4+ no longer uses that file.
v4+ creates a `.ftp-deploy-sync-state.json` file, but it is always present. The file is updated after every successful deployment.

One option would be to have a maintenance page and redirect to it when the deployment starts, then remove the redirect when the deployment ends. For example if you are using Apache to host your website you could use a `htaccess` file to redirect users to maintenance page, and remove the file when the deployment is complete.

I'm not sure what tooling you were using to do this previously. But if you wanted to use github actions you could use a step before `ftp-deploy-action` to deploy the htaccess file, and another step after the deployment to remove the `htaccess` file.

I wrote some code below, the important bit is `state-name` - we need to use a unique state name for the maintenance deploy, state-name is used so the script knows which files exist on the server.

Example: Note the following is untested example code only
```yaml
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 👷 Maintenance mode on
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        state-name: .ftp-deploy-sync-state--maintenance-mode.json
        exclude: EXCLUDE ALL FILES EXCEPT THE HTACCESS FILE AND MAINTENCE PAGE

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: EXCLUDE HTACCESS FILE, BECAUSE THIS IS USING A DIFFERENT STATE-NAME IT WONT KNOW THE MAINTENCE PAGE/HTACCESS FILE EXIST... SO THEY WONT BE REMOVED

    - name: 👷 Maintenance mode off
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        state-name: .ftp-deploy-sync-state--maintenance-mode.json
        exclude: EXCLUDE ALL FILES SO THE HTACCESS FILE IS DELETED
```


I'm going to close this out. If you get something working please post back here with your htaccess file and deployment yaml and I can add it as an example!
