### ISSUE TITLE
deploy only when push on master

### ISSUE THREAD

**Issue by csdm** [SamKirkland/FTP-Deploy-Action#244]
I need to deploy the files only when the push is done on branch master.
I'm using this:
```
on: 
  push:
    branches: master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_pwd }}
        port: 21
```

Actually the deploy starts also when I do the push on a branch different from master. In which way can I avoid this and deploy only when the push appens on master?
