### ISSUE TITLE
Negated exclude glob pattern does not seem to work

### ISSUE THREAD

**Issue by jdiazgon55** [SamKirkland/FTP-Deploy-Action#247]
**Bug Description**
When using a negated glob pattern (i.e. `!main.*`), `exclude` does not seem to parse it correctly. I tested the glob pattern and I think my syntax is correct:

![image](https://user-images.githubusercontent.com/28304354/143600506-7444e154-933f-4ba1-832f-21e9fb688a87.png)

I want to exclude everything but `main.533533353535.js`. The other way around is:

![image](https://user-images.githubusercontent.com/28304354/143600683-bd77afe5-89c2-442c-97cd-cfdf3f83b479.png)

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
      - name: Desplegar front a produccion (NEXO ERP) 
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with: 
          server: xxxxxx
          username: xxxxx
          password: ${{ secrets.ftp_password_prod }}
          local-dir: ./dist/prod-nexogeo-front/
          server-dir: pruebas/
          dry-run: true
          exclude: |
            !main.*
```

**My Action Log**
```
➕ Upload: index.html
➕ Upload: main.7a3ad33cea4274fddadd.js
➕ Upload: polyfills.70ffb02a82cc06d3b0cb.js
➕ Upload: runtime.7b63b9fd40098a2e8207.js
➕ Upload: styles.f9b4475c7347b120c30f.css
```

As you can see, not only my file `main.7a3ad33cea4274fddadd.js.` has been uploaded, but also the other ones.

**Using the non-negated version:**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
      - name: Desplegar front a produccion (NEXO ERP) 
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with: 
          server: xxxxxx
          username: xxxxx
          password: ${{ secrets.ftp_password_prod }}
          local-dir: ./dist/prod-nexogeo-front/
          server-dir: pruebas/
          dry-run: true
          exclude: |
            main.*
```

**My Action Log**
```
➕ Upload: index.html
➕ Upload: polyfills.70ffb02a82cc06d3b0cb.js
➕ Upload: runtime.7b63b9fd40098a2e8207.js
➕ Upload: styles.f9b4475c7347b120c30f.css
```

My file `main.7a3ad33cea4274fddadd.js.` has been correctly excluded.

What am I trying to achieve? Actually when uploading my files, every already existing file is getting deleted. I just want to upload the files I negate on `exclude` so that it does not remove other previous files with different names.
