### ISSUE TITLE
Best way to go!

### ISSUE THREAD

**Issue by DanielGilB** [SamKirkland/FTP-Deploy-Action#249]
Hi! This is going to be my first time using your action. It looks great, congrats! At this moment im running git-ftp in local for the desire project with a dirty solution so I would like to improve my solution.

How is really working FTP Deploy Action ? 
***Example action from read.me***
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.password }}
```

This action is going to upload the generated node_modules by the npm build every time right? So how is working exclude node_modules ?

Another question, what happen with the servers files which are in .gitignore? 

In other hand, this is not an issue/question with your project but maybe it helpful for the community, its possible to combine your action with zip action to upload node_modules ? Something like that:

```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

      - name: Create zipped vendor directory
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./node_modules.zip ./node_modules
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.password }}
```

Then create a post action to unzip the file and remove it. (its necessary to connect via ssh for that)
   

Im not sure the best way to go, since my project is Laravel + React components in blades. Im thinking to create 3 kinds of actions: Simple action (just deploy files changes) + Composer touched Action (only deploy vendors when they are touched) + Node modules action ( only deploy node_modules when they are touched). What do you think guys ?

Thanks !!
