### ISSUE TITLE
Deploy Action Job fails under "Sync Files". Some files transferred successfully.

### ISSUE THREAD

**Issue by ApplecakeYT** [SamKirkland/FTP-Deploy-Action#250]
**Bug Description**
When a commit is pushed, the workflow seems to deploy the file updates successful(test files committed showed up in FTP). Although the "Sync Files" section seems to fail(Every other section succeeded).

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./server/
        server-dir: ./world/datapacks/
```

**My Action Log(When error occured)**
```
----------------------------------------------------------------
Making changes to 9 files/folders to sync server state
Uploading: 38 B -- Deleting: 165 B -- Replacing: 8.76 kB
----------------------------------------------------------------
uploading "reasources.mcfunction"
uploading "test.mcfunction"
replacing "Laser Tag/data/lasertag/functions/init.mcfunction"
replacing "Laser Tag/data/lasertag/functions/loop.mcfunction"
replacing "Laser Tag/data/lasertag/functions/messages.mcfunction"
replacing "Race/data/race/functions/loop/timer.mcfunction"
removing "Laser Tag/data/lasertag/tags/blocks/pads.json"
File not found or you don't have access to the file - skipping...
removing folder "Laser Tag/data/lasertag/tags/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 No such file or directory.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4744:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4585:44)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 550
}
Error: FTPError: 550 No such file or directory.
```
