### ISSUE TITLE
Error: Error: EACCES: permission denied, open './_site/.ftp-deploy-sync-state.json'

### ISSUE THREAD

**Issue by ukutaht** [SamKirkland/FTP-Deploy-Action#254]
**Bug Description**

I am trying to upload a jekyll site to BunnyCDN over FTP. I started with the following configuration:

```
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./_site/
```

Full configuration [here](https://github.com/plausible/website/blob/693f8aa381839c3faf10a7c4076b3f04a15d0964/.github/workflows/jekyll.yml)

This configuration does not successfully upload the files, instead it throws the following error:

> Error: Error: EACCES: permission denied, open './_site/.ftp-deploy-sync-state.json'

Full build log [here](https://github.com/plausible/website/runs/4813159548?check_suite_focus=true)

### Workaround

I tried using the workaround mentioned in https://github.com/SamKirkland/FTP-Deploy-Action/issues/146 that adds the following configuration:

> state-name: ../.ftp-deploy-sync-state.json

Unfortunately this doesn't work for me either. The build gets much further but times out at the end when it tries to save the state file:

```
Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4778:58)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket._onTimeout (net.js:469:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: Error: Timeout (control socket)
```

Full build log [here](https://github.com/plausible/website/runs/4813302224?check_suite_focus=true0
I can confirm this is not an isolated failure, the timeout happens predictably every time.

Any ideas how to fix this?
