### ISSUE TITLE
NEW FEATURE: force

### ISSUE THREAD

**Issue by JaviRpo** [SamKirkland/FTP-Deploy-Action#255]
**Bug Description**
Sometimes for any particular reason (maybe an external modification), we want to force the upload of a directory/file.
If we have a new flag `force` the deploy process can omit/delete the `state-name` file and recreate from scratch.

I don't want to use the `dangerous-clean-slate` because could be some untracked files, that I don't want to delete.

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          force: true
```

**My Action Log**
```
   # Paste Log here
   # you may want enable verbose logging with   log-level: verbose
```

**Comment by SamKirkland** [comment]
Hello! Thanks for the PRs :)

I took a look at both of them. The problem with deleting the last published code is this action will now have no knowledge of the actual server state. Which means the state of github and the FTP server will slowly "drift".

Lets walk through an example:
- You deploy `file.txt` and `myCreditCardInfo.txt` with `force: true`
- You delete `myCreditCardInfo.txt` from github and deploy again. This action doesn't know `myCreditCardInfo.txt` exists on the server! So it won't be removed!!!

This wont be clear to users so I don't think I want to be merging these PRs. However I anticipated situations like yours when I was writing this plugin. That's why `IDiff` is an interface, we can make a new difference algorithm as it's own implementation. For example we could crawl the entire deployed sever state and build a dynamic state file on every build. This would be a more robust solution but would take quite a bit of development time and the deployment would be pretty slow.

Instead can you give me some more context on what your use-case is? It sounds like something else is modifying your server content?

**Comment by SamKirkland** [comment]
Closing for now, I can reopen as needed :)

**Comment by JaviRpo** [comment]
Hi @SamKirkland , thanks for your response, I'll try to describe my scenario and why I was proposing that solution.

My folder structure is something like this:
```
📁 www
     📁 app
         ➕ file1, file2, ..., fileN
     📁 assets
         ➕ file1, file2, ..., fileN
     📁 config
         ➕ file1
         ➕ file2
         ➕ ...
         ➕ fileN
         ➕ dbConnectionFile
📁 clients
     📁 client1
         ➕ dbConnectionFile
     📁 client2
         ➕ dbConnectionFile
     📁 ...
         ➕ dbConnectionFile
     📁 clientN
         ➕ dbConnectionFile
```
And my need is that I deploy the same code for different clients but each client has its own configuration file such as constants and database connection. The connection file is in the path `www/config/` but not only this file.

My deployment process is:
1. Upload the whole `www` folder. This creates a sync file in the root path with the diffs.
2. Upload the file inside the folder `clientX` into the path `www/config/`. In this folder, there is no sync file, so the deploy create a new one in this path and upload the files without deleting the other files `file1, file2, ..., fileN`
3. - At this point, the diff in the root path for the file `www/config/dbConnectionFile` is not correct because the file changed in step 2, but doesn't matter to me.

This is my action file
```yaml
on:
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client:
          - client1
          - client2
          - ...
          - clientN
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync all files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./www/
        server-dir: /${{ matrix.client }}/
    
    - name: 📂 Sync client files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./clients/${{ matrix.client }}/
        server-dir: /${{ matrix.client }}/config/
```

The second time I do the deployment:
- in the first step even if the `dbConnectionFile` is different because the repo file has not changed and the diff is the same.
- in the second step happens the same, there is no upload because the file is the same and the diff is the same.

My problem happens when I change the `www/config/dbConnectionFile` file with my local configurations and I commit it by mistake. The connection file will be uploaded to all clients in step 1 because the diff is different and in step 2 there is no upload because the diff is the same.

---

This is the reason I would like to add that new flag `force`. This will allow me to remove the sync file in the inner folder `www/config/` and upload again no matter what the `dbConnectionFile`.
And I cannot use the `dangerous-clean-slate` flag, because in the inner folder there are other files (common to all clients) and those will ve deleted because those are not in the clients folder.
