### ISSUE TITLE
FTPError: 550 Can't change directory to tests/: No such file or directory

### ISSUE THREAD

**Issue by paul45** [SamKirkland/FTP-Deploy-Action#257]
**Bug Description**
the connection works and transfert looks like works but i have a fail when deleting some folder

**My Action Config**
```yaml
on: 
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'images/**'
      - 'documents/**'
      - 'assets/**'
      - 'public/**'
name: 🚀 Deploy system on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: xxxxx
        username: xxxxx
        password: xxxxx
        server-dir: nouveau/
        exclude: |
          **/.git*
          **/.git*/**
          composer.json
          composer.lock
          **tests/**
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@4.2.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
Last published on 📅 Wednesday, January 19, 2022, 9:23 AM
----------------------------------------------------------------
Local Files:	1,040
Server Files:	1,040
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
⚖️  File content is the same, doing nothing: app/.htaccess
⚖️  File content is the same, doing nothing: app/Common.php
.............................
🗑️  Delete: tests/_support/View/Views/simpler.php    
📁  Delete: tests/app    
🗑️  Delete: tests/app/AccueilTest.php    
🗑️  Delete: tests/README.md    
📁  Delete: tests/session    
🗑️  Delete: tests/session/ExampleSessionTest.php    
⚖️  File content is the same, doing nothing: writable/.htaccess
⚖️  File content is the same, doing nothing: writable/backup/database/index.html
⚖️  File content is the same, doing nothing: writable/cache/index.html
⚖️  File content is the same, doing nothing: writable/debugbar/index.html
⚖️  File content is the same, doing nothing: writable/logs/index.html
⚖️  File content is the same, doing nothing: writable/session/index.html
⚖️  File content is the same, doing nothing: writable/uploads/index.html
----------------------------------------------------------------
Making changes to 118 files/folders to sync server state
Uploading: 0 B -- Deleting: 552 kB -- Replacing: 76.9 kB
----------------------------------------------------------------
replacing "app/Config/Database.php"
.............
   File not found or you don't have access to the file - skipping...
removing "tests/README.md"
File not found or you don't have access to the file - skipping...
removing "tests/session/ExampleSessionTest.php"
File not found or you don't have access to the file - skipping...
removing folder "tests/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't change directory to tests/: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4744:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4585:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Can't change directory to tests/: No such file or directory
```
