### ISSUE TITLE
Case change in file names ignored

### ISSUE THREAD

**Issue by CachingFoX** [SamKirkland/FTP-Deploy-Action#263]
**Bug Description**
Chance of lower/upper case of a file name doesn't recognized and file is not updated.

* File S5_1.jpg was committed and pushed to the git repo
* File was sync with FTP-Deploy-Action to a web server 
* File was renamed from S5_1.jpg to s5_1.jpg in the repository
* FTP-Action doesn't recognized renaming and do nothing.

**My Action Config**
```
name: 🚀 Deploy website

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files main
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: xxxxxxxx.kasserver.com
        username: f0123456
        password: ${{ secrets.password }}
        local-dir: ./folder/
        server-dir: ./folder/
```

**My Action Log**
```
⚖️  File content is the same, doing nothing: S5_1.jpg
⚖️  File content is the same, doing nothing: S5_2.jpg
```

**Comment by CachingFoX** [comment]
I update to latest version 4.2.0 - same behaviour

**Comment by SamKirkland** [comment]
Hmmm I haven't been able to recreate this. I even wrote a test with your exact file names and it passed.

Is it possible you are running this on the same commit and just rerunning the workflow? I have no experience with `workflow_dispatch`
```yaml
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
```
