### ISSUE TITLE
Error deploying via FTPs protocol - ERR_SSL_WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by tkpitta** [SamKirkland/FTP-Deploy-Action#267]
**Bug Description**
Can't seem to make my deploy via FTPs. My server is configured to use FTPs but after 5 minutes on my first deployment I get the following error : ERR_SSL_WRONG_VERSION_NUMBER. My FTPs server is configured to use the default TLS protocol.

**My Action Config**
```yaml
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  web-deploy:
    name: 🎉 FTP Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Execute Steps
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # FTP Deploy
      - name: 📂 Sync files in FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          local-dir: ./Code/
          server-dir: Code/
          server: ${{ secrets.ftps_host }}
          protocol: ftps
          port: 990
          username: ${{ secrets.ftps_user }}
          password: ${{ secrets.ftps_password }}
```

**My Action Log**
```
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

[Error: 139787667785600:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:308:
 (control socket)] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ERR_SSL_WRONG_VERSION_NUMBER'
}
Error: Error: 139787667785600:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:308:
 (control socket)
```
