### ISSUE TITLE
FTPError: 550 Failed to change directory

### ISSUE THREAD

**Issue by Scorpio256** [SamKirkland/FTP-Deploy-Action#270]
**Bug Description**
Clean uplad is fine but next changes (delete files, more dirs to clean) ends with this error.

**My Action Config**
```yaml
name: Deployment DEV

on:
  push:
    branches: [ dev ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment:
      name: dev
      
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2            
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.DEV_DEPLOYMENT_PATH }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

```

**My Action Log**
```
FTPError: 550 Failed to change directory.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4744:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4585:44)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 550
}
Error: FTPError: 550 Failed to change directory.
```
