### ISSUE TITLE
Error: Error: Can't open data connection in passive mode: connect ETIMEDOUT 162.0.215.157:12102

### ISSUE THREAD

**Issue by danieluac** [SamKirkland/FTP-Deploy-Action#273]
**Bug Description**

**My Action Config**
```yaml
name: Deployiment to Staging

on:
  push:
    branches: [ staging ]

jobs:
  web-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copying .env
      run: php -r "file_exists('.env') || copy('.env.example-staging', '.env');"
    - name: Installing Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Deploying changes to production server
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.NAMECHEAP_SERVER}}
        username: ${{ secrets.NAMECHEAP_USER}}
        password: ${{ secrets.NAMECHEAP_PASSWORD}}
        protocol: ftps
        server-dir: "api.example.com/"
```

**My Action Log**
```
  ----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------
----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------
Error: Can't open data connection in passive mode: connect ETIMEDOUT 162.0.215.157:12102
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '162.0.215.157',
  port: 12102
}
Error: Error: Can't open data connection in passive mode: connect ETIMEDOUT 162.0.215.157:12102
```
