### ISSUE TITLE
Cannot connect to working FTP server

### ISSUE THREAD

**Issue by coldfeudal** [SamKirkland/FTP-Deploy-Action#274]
Tried the action myself and it failed on the first try. Configured the action according to multiple guides and got the error. Password is set correctly in same repo settings. Was able to connect from ftp client with same credentials. Any ftp connection ips are not blacklisted on server
```yaml
on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: murzlkin.myjino.ru
        username: murzlkin
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: domains/pbc.murzlkin.myjino.ru/
        dry-run: true
```

![image](https://user-images.githubusercontent.com/27438739/155002929-37312fb3-acca-4dc0-8996-50fcf11d7af5.png)

```
Run SamKirkland/FTP-Deploy-Action@4.3.0
  with:
    server: murzlkin.myjino.ru
    username: murzlkin
    password: ***
    server-dir: domains/pbc.murzlkin.myjino.ru/
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 530 Login incorrect.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4774:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4615:44)
    at Socket.emit (events.js:[2](https://github.com/coldfeudal/pbc/runs/5277831301?check_suite_focus=true#step:3:2)10:5)
    at addChunk (_stream_readable.js:[3](https://github.com/coldfeudal/pbc/runs/5277831301?check_suite_focus=true#step:3:3)09:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at Socket.Readable.push (_stream_readable.js:22[4](https://github.com/coldfeudal/pbc/runs/5277831301?check_suite_focus=true#step:3:4):10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: [5](https://github.com/coldfeudal/pbc/runs/5277831301?check_suite_focus=true#step:3:5)[30](https://github.com/coldfeudal/pbc/runs/5277831301?check_suite_focus=true#step:3:30)
}
Error: FTPError: 530 Login incorrect.
```
