### ISSUE TITLE
excludes not excluding

### ISSUE THREAD

**Issue by shuantsu** [SamKirkland/FTP-Deploy-Action#284]
this is my action

```
on:
  push:
    branches:
      - main
name: Deployar aplicação
jobs:
  web-deploy:
    name: Deployar
    runs-on: ubuntu-latest
    steps:
      - name: Pega código
        uses: actions/checkout@v2

      - name: Faz upload
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./src/
          server-dir: /www/test/
          exclude: |
            **/scss/**
            *.bat
```

but even after putting the scss folder on the exclude section, the folder is not being excluded.
what am I doing wrong?
