### ISSUE TITLE
Can't open data connection in passive mode: connect ETIMEDOUT

### ISSUE THREAD

**Issue by sacsbrainz** [SamKirkland/FTP-Deploy-Action#288]
**Bug Description**
When i push to my git during the deploy process i get this error

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ***************
        username: *****************
        password: ******************
        port: 21
```

**My Action Log**
```
  Error: Can't open data connection in passive mode: connect ETIMEDOUT 179.178.206.30:12048
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '179.178.206.30',
  port: 12048
}
Error: Error: Can't open data connection in passive mode: connect ETIMEDOUT 179.178.206.30:12048
```
