### ISSUE TITLE
Failure when removing missing folder

### ISSUE THREAD

**Issue by Korijn** [SamKirkland/FTP-Deploy-Action#289]
**Bug Description**
Failure while syncing on removing a missing folder.

**My Action Config**
```yaml
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: .....
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_pass }}
        protocol: ftps
        local-dir: ./public/
        server-dir: ...../
```

**My Action Log**
```
removing folder "band/"
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------
----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------
FTPError: 550 The system cannot find the file specified. 
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4744:39)
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.2.0/dist/index.js:4585:44)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:2[68](https://github.com/Korijn/...../runs/6673937025?check_suite_focus=true#step:5:69):11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 550
}
Error: FTPError: 550 The system cannot find the file specified.
```
