### ISSUE TITLE
Using "ftpes://" on server gives error: "getaddrinfo ENOTFOUND *** (control socket)"

### ISSUE THREAD

**Issue by bydiogosampaio** [SamKirkland/FTP-Deploy-Action#290]
Hi,
I can't connect with my server via FTP unless I use "ftpes://" on the server value:

> FTPES (explicit SSL mode, encrypted):
> 
> Host: ftpes://[your server hostname or IP address]
> Username: your cPanel username or full [FTP username]
> Password: your cPanel password or [FTP account password]
> Port: 21

I haven't used FTP Deploy since version 3.1.1 and it was working with that version, now when using this version 4.3.0 it's not working and I get this error:

```
Error: getaddrinfo ENOTFOUND *** (control socket)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:XX:[XX](XXXXXXXXX)) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '***'
}
Error: Error: getaddrinfo ENOTFOUND *** (control socket)`
```

```
name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21 # todo replace with your web hosts ftps port
        exclude: |
                  **/.git*
                  **/.git*/**
                  **/.github*/**
                  **/node_modules/**
```
