### ISSUE TITLE
Cpanel CI/CD: Error: getaddrinfo ENOTFOUND ftp.*******.org (control socket)

### ISSUE THREAD

**Issue by defidev0508** [SamKirkland/FTP-Deploy-Action#293]
**Bug Description**
I want to implement CI/CD from github repsitory to CPanel.
But I got this error as below.

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
    name: Building files
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Build Project
        run: |
          npm install
          npm run build --if-present

      - name: List output files
        run: ls

      - name: sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.***********.org
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftps
          local-dir: build/
          port: 2083
```

**My Action Log**
```
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------
The server "ftp.**********.org" doesn't seem to exist. Do you have a typo?
----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------
Error: getaddrinfo ENOTFOUND ftp.***********.org (control socket)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:[26](https://github.com/*****/***********/runs/6895339722?check_suite_focus=true#step:6:27)) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ftp.*********.org'
}
Error: Error: getaddrinfo ENOTFOUND ftp.***********.org (control socket)
```
