### ISSUE TITLE
New example for Laravel (PHP) project

### ISSUE THREAD

**Issue by Mavv3006** [SamKirkland/FTP-Deploy-Action#297]
Please add a new example for a [Laravel](https://laravel.com/) project.

**Comment by bhekor** [comment]
yes pleaseeee.

**Comment by ngl5000** [comment]
3rd please :)

**Comment by zendzo** [comment]
i use this setting on my main.yaml
```
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.event-meitech.com
        username: ftp.master@event-meitech.com
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        port: 21 # todo replace with your web hosts ftps port
```

on the server side. setting directly on laravel folder

**Comment by zendzo** [comment]
i use this setting on my main.yaml
```
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: **
        username: **
        protocol: ftps
        port: 21 # todo replace with your web hosts ftps port
```

on the server side. create user and and folder setting in cpanel directly on laravel folder
