### ISSUE TITLE
Deploy to Azure failed - MFF and SITE CHMOD are not supported by this site

### ISSUE THREAD

**Issue by Misiu** [SamKirkland/FTP-Deploy-Action#30]
I have a very simple action that deploys the content of the build folder to Azure FTP.

```
- name: FTP Deploy to Azure
  uses: SamKirkland/FTP-Deploy-Action@2.0.0
  env: 
   FTP_SERVER: ${{ secrets.FTP_SERVER_AZURE_TEST }}
   FTP_USERNAME: ${{ secrets.FTP_USERNAME_AZURE_TEST }}
   FTP_PASSWORD: ${{ secrets.FTP_PASSWORD_AZURE_TEST }}
   REMOTE_DIR: site/wwwroot
   LOCAL_DIR: build
   METHOD: ftp
   ARGS: --no-empty-dirs --delete --ignore-time --verbose --continue
```

Unfortunately, I get these errors when Actions run:

```
Transferring file `PHPMailer/SMTP.php'
chmod: Access failed: 500 'SITE': command not understood (./Exception.php)
chmod: Operation not supported: MFF and SITE CHMOD are not supported by this site
chmod: Operation not supported: MFF and SITE CHMOD are not supported by this site
chmod: Operation not supported: MFF and SITE CHMOD are not supported by this site
chmod: Operation not supported: MFF and SITE CHMOD are not supported by this site
Making directory `kontakt'
Removing old file `kontakt/index.html'
Transferring file `kontakt/index.html'
chmod: Operation not supported: MFF and SITE CHMOD are not supported by this site
Making directory `not-found'
Removing old file `not-found/index.html'
Transferring file `not-found/index.html'
chmod: Operation not supported: MFF and SITE CHMOD are not supported by this site
```

The same action works fine when I deploy to OVH, but on Azure, I get the above errors.

Does anyone have an idea what might be wrong?
