### ISSUE TITLE
FTPError: 550 The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by adeel-rana** [SamKirkland/FTP-Deploy-Action#303]
**Bug Description**
I am facing the below error on the time when files are replacing/overwriting. 

**Sometimes this error occurs when multiple actions run in parallel to deploy the application on the same server with different directories and usernames.**

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
    - name: 📂 Sync files
       uses: SamKirkland/FTP-Deploy-Action@4.3.0
       with:
        server: <MY_SERVER>
        username: <MY_USERNAME>
        password:<MY_PASSWORD>
        local-dir: ./Release/
        log-level: verbose
```

**My Action Log**
```
   Making changes to 2 files/folders to sync server state
Uploading: 0 B -- Deleting: 0 B -- Replacing: 604 kB
replacing "CMS.dll"
-------------- 🔥🔥🔥 an error occurred 🔥🔥🔥 --------------
---------------------- full error below ----------------------
FTPError: 550 The process cannot access the file because it is being used by another process.
at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4774:39)
at Socket. (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4615:44)
at Socket.emit (events.js:314:20)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:268:11)
at Socket.Readable.push (_stream_readable.js:213:10)
at TCP.onStreamRead (internal/stream_base_commons.js:1[88](https://github.com/AzeemArshad/CMS/runs/7373755805?check_suite_focus=true#step:9:89):23) {
code: 550
}
Error: FTPError: 550 The process cannot access the file because it is being used by another process.
```

**Comment by Cyrildu31** [comment]
Hello, 
I have  the same Issue.
Did you found a fix ?
Thank you.

**Comment by PieterjanDeClippel** [comment]
Same

**Comment by mathdx1111** [comment]
How to fix it?

**Comment by tuongduy10** [comment]
Same here, i use FileZilla and it works fine but the error occured at .dll file when replacing or uploading with FTP Deploy in github actions 

![Uploading unnamed.png…]()

**Comment by PieterjanDeClippel** [comment]
Hi you can fix this by creating and uploading an `app_offline.htm` and waiting 3 seconds before running this action

**Comment by tuongduy10** [comment]
Thanks @PieterjanDeClippel i've fixed my problem
Btw i've found the root cause after searching for a while, here is the anwser
https://stackoverflow.com/a/68326476/22006469

**Comment by yigitgnc** [comment]
> Hi you can fix this by creating and uploading an `app_offline.htm` and waiting 3 seconds before running this action
> 
> Something [like this](https://github.com/MintPlayer/MintPlayer.GithubApps/blob/master/.github%2Fworkflows%2Fpublish-master.yml#L44-L90) however it's not perfect and may need to be tweaked

thanks that's clever

**Comment by yigitgnc** [comment]
> Hi you can fix this by creating and uploading an `app_offline.htm` and waiting 3 seconds before running this action
> 
> Something [like this](https://github.com/MintPlayer/MintPlayer.GithubApps/blob/master/.github%2Fworkflows%2Fpublish-master.yml#L44-L90) however it's not perfect and may need to be tweaked

thanks thats clever

**Comment by nima-ghomri** [comment]
Thank everyone for the guiding me to the right direction, I'm gonna share this which works perfectly for .net apps and does not require multiple steps and it's clean. I actually ended up using python `ftplib` for the `app_offline.htm` creating and deleting part so I don't mess with the ` .ftp-deploy-sync-state.json` file.
```
name: Deploy via FTP

on:
  push:
    branches:
      - main
      
env:
  DRY_RUN: false
  DOTNET_VERSION: '9.0'
  PROJECT_PATH: '.Test.csproj'
  PUBLISH_DIR: './Test/bin/Publish/'  
  SERVER_DIR: '/srv/'
  OFFLINE_PATH: '/srv/app_offline.htm'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish the project
        run: |
          dotnet publish -c Release ${{ env.PROJECT_PATH }} -o ${{ env.PUBLISH_DIR }}

      - name: Switch the site offline
        shell: python
        run: |
            import ftplib
            ftp = ftplib.FTP('${{ secrets.FTP_SERVER }}')
            ftp.login('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')
            open('temp.htm', "w").close()  
            with open('temp.htm', "rb") as file:
                ftp.storbinary("STOR ${{ env.OFFLINE_PATH }}", file)
            ftp.quit()

      - name: Deploy using FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          protocol: ftps
          dry-run: ${{ env.DRY_RUN }}
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ env.PUBLISH_DIR }} 
          server-dir: ${{ env.SERVER_DIR }}
          exclude: |
            ${{ env.OFFLINE_PATH }}
      
      - name: Switch the site online
        shell: python
        run: |
            import ftplib
            ftp = ftplib.FTP('${{ secrets.FTP_SERVER }}')
            ftp.login('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')
            ftp.delete('${{ env.OFFLINE_PATH }}')
            ftp.quit()
```
