### ISSUE TITLE
Gives error with next.config.js

### ISSUE THREAD

**Issue by sc0rp10n-py** [SamKirkland/FTP-Deploy-Action#304]
I get this error when deploying my next js project
![image](https://user-images.githubusercontent.com/49873605/180617502-071ad649-9694-43b6-ba38-7e61bce07880.png)

the `next.config.js` code
```js
/** @type {import('next').NextConfig} */
// const withPlugin = require('next-compose-plugins');
// const optimizedImages = require('next-optimized-images');

const nextConfig = {
  reactStrictMode: true,
}

module.exports = {
  nextConfig,
  images: {
    domains: ['images.unsplash.com'],
    loader: 'akamai',
    path: '',
  },
}
```

the `main.yml`
```yml
on: push
name: Publish to prod
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://something/mnt/Storage/www/summercamp
        ftp-username: something
        ftp-password: ${{ secrets.PASSWORD }}
        local-dir: dist/
        git-ftp-args: --insecure
```
