### ISSUE TITLE
Error timeout after many uploads

### ISSUE THREAD

**Issue by Gashmob** [SamKirkland/FTP-Deploy-Action#305]
**Bug Description**
I deploy a website made with Symfony, before uses your action i run `composer update`. So the deploy needs to uploads all vendor files. It take more than an hour and then it's stop with a timeout error. Does this error come from my server or from the config i use ?

**My Action Config**
```yaml
on: push
name: Deploy website

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: http

      - name: Install dependencies
        run: |
          composer update
      - name: Prepare config
        run: |
          mv .env.prod .env
      - name: Export files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftpcloud.cluster024.hosting.ovh.net
          protocol: ftp
          port: 21
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: CodeShare/
          security: loose
```

**My Action Log**
```
...1 hour of log then :
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Can't open data connection in passive mode: connect ETIMEDOUT 91.134.248.222:54448
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '91.134.248.222',
  port: 54448
}
```
