### ISSUE TITLE
Tagging your deployment to go into different folders on remote host

### ISSUE THREAD

**Issue by makooda** [SamKirkland/FTP-Deploy-Action#307]
Is there a way to specify a tag eg. `test` or `live` to push to different folders ?

**Comment by SamKirkland** [comment]
Yes!

Setup a `test` branch and `master` branch.
When someone merges to the `test` branch deploy to the test server/folder.
When someone merges to the `master` branch deploy to the production server/folder.
See github documentation https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters

Example code (untested)


#### ProductionDeploy.yaml
```yaml
on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.ftp_password }}
        server-dir: ./production/
```


#### TestDeploy.yaml
```yaml
on:
  push:
    branches:
      - test
```
