### ISSUE TITLE
FTP-Deploy-Action cannot be used if initial upload takes longer than 6 hours

### ISSUE THREAD

**Issue by JulianGro** [SamKirkland/FTP-Deploy-Action#311]
**Bug Description**
When deploying a large amount of files, a workflow might run into GitHubs 6 hour time limit.
Since FTP-Deploy-Action does not create intermittent `.ftp-deploy-sync-state.json` files, it has to start anew after GitHub kills the runner.

**My Action Config**
```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build_site:
    runs-on: ubuntu-latest

    name: Deploy content
    steps:
    - uses: actions/checkout@v3

    - name: Deploy content
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.tuxfamily.org
        username: ${{ secrets.GHA_FTP_USER }}
        password: ${{ secrets.GHA_FTP_PASS }}
        local-dir: ./
        server-dir: overte/overte-repository/content/
        exclude: |
          **/staging/**
          .htaccess
          **/.git*
          **/.git*/**
```
