### ISSUE TITLE
Error when trying to deploy a .Net core app

### ISSUE THREAD

**Issue by digounet** [SamKirkland/FTP-Deploy-Action#314]
**Bug Description**
The upload process is failing always on the same dll file (automapper.dll)

**My Action Config**
```yaml

name: Deployment

concurrency: production

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release --output ./Release
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
          server: ${{ secrets.FTP_SERVER }}
          # FTP account username
          username: ${{ secrets.FTP_USERNAME }}
          # FTP account password
          password: ${{ secrets.FTP_PASSWORD }}
          # The local folder to copy, defaults to root project folder
          local-dir: ./Release/
          server-dir: ${{ secrets.SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/wwwroot/**
          dangerous-clean-slate: true
          log-level: verbose

```

**My Action Log**
```

Uploading to 191.6.218.55:39462 (No encryption)
858
upload progress for "appsettings.json". Progress: 0 bytes of 6806 bytes
859
upload progress for "appsettings.json". Progress: 318 bytes of 7124 bytes
860
< 226 Transfer complete.
861

862
  file uploaded
863
uploading "AutoMapper.dll"
864
> EPSV
865
< 229 Entering Extended Passive Mode (|||39463|)
866

867
> STOR AutoMapper.dll
868
< 550 
869

870

871
----------------------------------------------------------------
872
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
873
----------------------------------------------------------------
874

875
----------------------------------------------------------------
876
----------------------  full error below  ----------------------
877
----------------------------------------------------------------
878

879
FTPError: 550 
880
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.1/dist/index.js:5254:39)
881
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.1/dist/index.js:5095:44)
882
    at Socket.emit (events.js:314:20)
883
    at addChunk (_stream_readable.js:297:12)
884
    at readableAddChunk (_stream_readable.js:268:11)
885
    at Socket.Readable.push (_stream_readable.js:213:10)
886
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
887
  code: 550
888
}
889
Error: FTPError: 550 

   logging with   log-level: verbose
```
