### ISSUE TITLE
Deleted everything in target directory

### ISSUE THREAD

**Issue by d1ag0n** [SamKirkland/FTP-Deploy-Action#315]
Deleted everything in target directory and deleted sub directories

**My Action Config**
```yaml
    steps:
    - name: make offline dir
      run: mkdir offline
    - name: make offline file
      run: ni offline\App_Offline.htm
    - name: upload offline
      uses: SamKirkland/FTP-Deploy-Action@4.3.0      
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./offline/
        server-dir: ./wws/
```
