### ISSUE TITLE
timeout is Unexpected input?

### ISSUE THREAD

**Issue by rockbenben** [SamKirkland/FTP-Deploy-Action#316]
**Bug Description**
I set `timeout`, but it shows `Unexpected input(s) 'timeout'`。

**My Action Config**
```yaml
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          local-dir: docs/.vuepress/dist/
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          timeout: 600000
```

**My Action Log**
```
Warning: Unexpected input(s) 'timeout', valid inputs are ['server', 'username', 'password', 'port', 'protocol', 'local-dir', 'server-dir', 'state-name', 'dry-run', 'dangerous-clean-slate', 'exclude', 'log-level', 'security']
Run SamKirkland/FTP-Deploy-Action@4.3.1
```
