### ISSUE TITLE
Error: Can't parse response to 'PASV': 226 Closing data connection, file transfer successful

### ISSUE THREAD

**Issue by StruffelProductions** [SamKirkland/FTP-Deploy-Action#320]
**Bug Description**
While running the job I receive the error: **Error: Can't parse response to 'PASV': 226 Closing data connection, file transfer successful**

**My Action Config**
```yaml
name: XXXXXXX

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          # ftp server
          server: ${{secrets.CDN_FTP_SERVER}}
          # ftp username
          username: ${{secrets.CDN_FTP_LOGIN}}
          # ftp password
          password: ${{secrets.CDN_FTP_PASSWORD}}
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: main/
          local-dir: ./src/
```

**My Action Log**
```
  Calculating differences between client & server
----------------------------------------------------------------
📁 Create: css
📁 Create: js
📁 Create: lib
📁 Create: media
📄 Upload: css/main.css
📄 Upload: hdri-flat.html
📄 Upload: hdri-panorama.html
📄 Upload: js/hdri-flat.js
📄 Upload: js/hdri-panorama.js
📄 Upload: js/main.js
📄 Upload: js/pbr-material.js
📄 Upload: js/texture-tiling.js
📄 Upload: lib/EXRLoader.r142.js
📄 Upload: lib/OrbitControls.r142.js
📄 Upload: lib/RGBELoader.r142.js
📄 Upload: lib/three.r142.min.js
📄 Upload: media/env-full-forest-hq.exr
📄 Upload: media/env-full-forest-lq.exr
📄 Upload: media/env-full-lab-hq.exr
📄 Upload: media/env-full-lab-lq.exr
📄 Upload: media/env-full-riverbed-hq.exr
📄 Upload: media/env-full-riverbed-lq.exr
📄 Upload: media/env-full-sculpture-hq.exr
📄 Upload: media/env-full-sculpture-lq.exr
📄 Upload: media/env-half-sunny-hq.exr
📄 Upload: media/env-half-sunny-lq.exr
📄 Upload: media/env-half-sunset-hq.exr
📄 Upload: media/env-half-sunset-lq.exr
📄 Upload: pbr-material.html
📄 Upload: texture-tiling.html
----------------------------------------------------------------
Making changes to 30 files/folders to sync server state
Uploading: 98.6 MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder "css/"
creating folder "js/"
creating folder "lib/"
creating folder "media/"
uploading "css/main.css"
uploading "hdri-flat.html"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Can't parse response to 'PASV': 2[26](https://github.com/StruffelProductions/PBR.ONE/runs/8293610445?check_suite_focus=true#step:3:27) Closing data connection, file transfer successful
    at parsePasvResponse (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.2/dist/index.js:6193:15)
    at Client.enterPassiveModeIPv4 [as prepareTransfer] (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.2/dist/index.js:6170:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Client._uploadFromStream (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.2/dist/index.js:[44](https://github.com/StruffelProductions/PBR.ONE/runs/8293610445?check_suite_focus=true#step:3:45)91:13)
    at async Client._uploadLocalFile (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.2/dist/index.js:4[47](https://github.com/StruffelProductions/PBR.ONE/runs/8293610445?check_suite_focus=true#step:3:48)7:20)
Error: Error: Can't parse response to 'PASV': 226 Closing data connection, file transfer successful
```
