### ISSUE TITLE
`550 .ftp-deploy-sync-state.json: No such file or directory`

### ISSUE THREAD

**Issue by overheadhunter** [SamKirkland/FTP-Deploy-Action#324]
**Bug Description**
I want to upload files. Not sync them. Just upload. Nothing fancy. Upload succeeds, however the action still fails due to `550 .ftp-deploy-sync-state.json: No such file or directory`.

**My Action Config**
```yaml
on: push
jobs:
  // ...
  allowlist:
    steps:
      - name: Upload to Kaspersky
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          protocol: ftps
          server: allowlist.kaspersky-labs.com
          port: 990
          username: ${{ secrets.ALLOWLIST_KASPERSKY_USERNAME }}
          password: ${{ secrets.ALLOWLIST_KASPERSKY_PASSWORD }}
          local-dir: files/
```

**My Action Log**
```
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
No file exists on the server "./.ftp-deploy-sync-state.json" - this must be your first publish! 🎉
The first publish will take a while... but once the initial sync is done only differences are published!
If you get this message and its NOT your first publish, something is wrong.
----------------------------------------------------------------
Local Files:	2
Server Files:	0
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
📄 Upload: file1
📄 Upload: file2
----------------------------------------------------------------
Making changes to 2 files/folders to sync server state
Uploading: 1[12](https://github.com/foo/bar/actions/runs/23/jobs/42#step:5:13) MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
uploading "file1"
uploading "file2"
----------------------------------------------------------------
🎉 Sync complete. Saving current server state to "./.ftp-deploy-sync-state.json"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 .ftp-deploy-sync-state.json: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4774:39)
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4615:44)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at TLSSocket.Readable.push (_stream_readable.js:2[13](https://github.com/foo/bar/actions/runs/23/jobs/42#step:5:14):10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:[18](https://github.com/foo/bar/actions/runs/23/jobs/42#step:5:19)8:[23](https://github.com/foo/bar/actions/runs/23/jobs/42#step:5:24)) {
  code: 5[50](https://github.com/foo/bar/actions/runs/23/jobs/42#step:5:51)
}
Error: FTPError: [55](https://github.com/foo/bar/actions/runs/23/jobs/42#step:5:56)0 .ftp-deploy-sync-state.json: No such file or directory
```
