### ISSUE TITLE
Delete some directories on FTP after deploy?

### ISSUE THREAD

**Issue by pechondra** [SamKirkland/FTP-Deploy-Action#326]
Is possible delete some directories on FTP after deploy?

**Comment by SamKirkland** [comment]
No, this action syncs a clone of your github repo --> ftp server.

If you would like to delete a file simply modify it after you clone your repo, then trigger this action.

Example (untested code)
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Delete folder for this run (locally only, will not change github files)
      run: rm -r example/
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.password }}
```
