### ISSUE TITLE
How to deploy only dist folder 

### ISSUE THREAD

**Issue by sadiqueamt** [SamKirkland/FTP-Deploy-Action#334]
Hi,
I don't want to deploy all the files, how can i deploy only the dist folder?

```
name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
```

**Comment by samfrank** [comment]
You can add `local-dir` to the configuration to specific which folder is to be deployed

```
with:
  server: ${{ secrets.FTP_SERVER }}
  username: ${{ secrets.FTP_USERNAME }}
  password: ${{ secrets.FTP_PASSWORD }}
  local-dir: ./_site/ 
```
