### ISSUE TITLE
Deploy error on `actions/checkout@v2`

### ISSUE THREAD

**Issue by sammyskills** [SamKirkland/FTP-Deploy-Action#340]
**Bug Description**
Error: None of the available transfer modes work.

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        port: 21
        server-dir: /staging-core/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          docs/**
          public/**
          src/**
          todo.txt
          misc/**
```

**My Action Log**
```
   Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
```
