### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by chzappsinc** [SamKirkland/FTP-Deploy-Action#343]
**Bug Description**

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🚀 Deploy website every commit
    # !!!!!!! TODO Fill Out !!!!!!!
```

**My Action Log**
```
 Error: Error: EACCES: permission denied, scandir '/lost+found'
```
