### ISSUE TITLE
Set connection as insecure with arguments?

### ISSUE THREAD

**Issue by ahinkle** [SamKirkland/FTP-Deploy-Action#344]
**Bug Description**
I'm trying to upgrade from v3 to v4. I'm using WpEngine. I'm getting a connection failure. Any ideas on the differences between the two? I noticed `git-ftp-args` was deprecated. How can I mark the connection to allow insecure?

Here is my v3 setup:
```yaml
on:
  push:
    branches:
      - staging
name: Deploy WordPress Site to WP Engine Staging
jobs:
  Deploy-via-SFTP:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: sftp://***.sftp.wpengine.com:2222/wp-content/
          ftp-username: ${{ secrets.STG_FTP_USERNAME }}
          ftp-password: ${{ secrets.STG_FTP_PASSWORD }}
          local-dir: wordpress/wp-content
          git-ftp-args: --insecure
```

**My v4 setup:**
```yaml
on:
  push:
    branches:
      - staging
name: Deploy WordPress Site to WP Engine Staging
jobs:
  Deploy-via-SFTP:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ***.sftp.wpengine.com
          port: 2222
          protocol: ftps
          username:  ${{ secrets.STG_FTP_USERNAME }}
          password: ${{ secrets.STG_FTP_PASSWORD }}
          local-dir: wordpress/wp-content/
          server-dir: /wp-content/
          dry-run: true
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@4.3.3
  with:
    server: ***.sftp.wpengine.com
    port: [2](https://github.com/***/***/actions/runs/3689070568/jobs/6244607773#step:3:2)222
    protocol: ftps
    username: ***
    password: ***
    local-dir: wordpress/wp-content/
    server-dir: /wp-content/
    dry-run: true
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.[3](https://github.com/***/***/actions/runs/3689070568/jobs/6244607773#step:3:3).3/dist/index.js:[5](https://github.com/***/***/actions/runs/3689070568/jobs/6244607773#step:3:5)288:58)
    at Object.onceWrapper (node:events:509:28)
    at Socket.emit (node:events:390:28)
    at Socket._onTimeout (node:net:501:8)
    at listOnTimeout (node:internal/timers:55[7](https://github.com/***/***/actions/runs/3689070568/jobs/6244607773#step:3:7):[17](https://github.com/***/***/actions/runs/3689070568/jobs/6244607773#step:3:18))
    at processTimers (node:internal/timers:500:7)
Error: Error: Timeout (control socket)
```
