### ISSUE TITLE
FTPS with --verbose stuck at Uploading files

### ISSUE THREAD

**Issue by andrewbarnesweb** [SamKirkland/FTP-Deploy-Action#35]
I can't seem to get it to work successfully. The FTP that I'm using seems to only work over FTPS, so I'm wondering if that's the issue. But it just spins at `Uploading files...` and doesn't seem to give me any connection errors or the like.

Wondering if I'm missing something.

Here is my current config.

```yml
on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        ARGS: --delete --verbose
```

**Comment by andrewbarnesweb** [comment]
Also worth noting, that I'm using Cpanel. And it adds my username with an `@` in the middle. Didn't know if that would cause issues also.

**Comment by SamKirkland** [comment]
A username with @ is fine :)
Can you verify on another client (ex: filezilla) that you can connect via ftp using your username/password.

**Comment by andrewbarnesweb** [comment]
Thanks for a prompt reply. I can connect on Cyberduck, but only on FTP-SSL, it won’t connect on FTP. I also have to accept some dodgy certificate thing.

**Comment by andrewbarnesweb** [comment]
I've tried with Filezilla just now. Connects, although does fire up a dialog about miss matched certificates (hostname does not match certificate). Not sure how much of the dialog is safe to disclose in a public issue :-)

![image](https://user-images.githubusercontent.com/20924669/71325629-75c34c00-24e7-11ea-9fc4-10346441d230.png)

**Comment by SamKirkland** [comment]
Unfortunately host doesn't support FTPS so I haven't been able to test this. Can you try setting the method to ftps?

```
on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        METHOD: ftps
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        ARGS: --delete --verbose
```
