### ISSUE TITLE
Instability of sending files via FTP

### ISSUE THREAD

**Issue by daherlive** [SamKirkland/FTP-Deploy-Action#353]
Hey! 

Since Tuesday, the deployment action via FTP has presented instability that I followed in the issue closed yesterday with the solution of the problem.

The action really worked again, however instead of sending only the commit changes via FTP, it uploads all the branch files, taking more than 1 hour. 

> Example: I made a commit changing 3 files and adding 2 new ones. Instead of sending only 5 files to ftp, it sends the whole project.
> 
**> Before, it added, edited or deleted according to the commit, now it doesn't.**

Any suggestions for the problem?

```
name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
```
