### ISSUE TITLE
FTP_SERVER ARGS not defined error is coming

### ISSUE THREAD

**Issue by vedikinsolutions** [SamKirkland/FTP-Deploy-Action#36]
Hello!

I am trying to configure this git action in my repository. Here is my main.yml file looks like.

```
name: Publish Website
on: 
  push:
    branches:
    - master
jobs:
  deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          FTP_SERVER: thcitsolutions.com
          ftp_username: dev@thcitsolutions.com
          ftp_password: ##ActualPasswordGoesHere##
          method: ftp
          port: 21
          # The local folder to copy, defaults to root project folder
          # local_dir: # optional, default is 
          # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
          remote_dir: test # optional, default is 
          # Passes through options into lftp
          ARGS: --exclude=.ftpquota --exclude-glob=.git*/** --exclude-glob=.git**
```

But when I push to master branch, it is giving error while connecting to FTP (/entrypoint.sh: line 25: FTP_SERVER: parameter not set). PFA screenshot for reference purpose.

Can you please guide what I am missing. 
![GitHub FTP - Error Screenshot](https://user-images.githubusercontent.com/53016481/71943582-1eabbf80-31e7-11ea-8268-6976ff0bddd3.PNG)

Note: I am new to Git Action and this is my first git action.

**Comment by SamKirkland** [comment]
Hey, congratulations on using your first action!

Simple fix, your config is SO close.
Simply change `with:` -> `env:`

```yaml
name: Publish Website
on: 
  push:
    branches:
    - master
jobs:
  deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: thcitsolutions.com
          ftp_username: #########@thcitsolutions.com
          ftp_password: ##ActualPasswordGoesHere##
          method: ftp
          port: 21
          # The local folder to copy, defaults to root project folder
          # local_dir: # optional, default is 
          # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
          remote_dir: test # optional, default is 
          # Passes through options into lftp
          ARGS: --exclude=.ftpquota --exclude-glob=.git*/** --exclude-glob=.git**
```

Please post back and let me know if that resolved your issue, then we can continue debugging or close the issue.
