### ISSUE TITLE
Not pushing only modified files

### ISSUE THREAD

**Issue by joecollett** [SamKirkland/FTP-Deploy-Action#366]
**Bug Description**
Every time I make a commit and push to my github repo its take 20 mins+ because its redeploying everything. Am I missing something from my configuration to make this just pick up the latest modified files?

**My Action Config**
```yaml
on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          wp-config.php
          .htaccess
          .htaccess.bk
          .env
          **/wp-content/uploads/**
```

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/13499326/215340307-4b85d296-ae1e-4be1-b779-92ce1ee98eea.png">

<img width="525" alt="image" src="https://user-images.githubusercontent.com/13499326/215340361-7598bde6-71d7-4638-8b2c-a786c48b4c91.png">
