### ISSUE TITLE
FTPError: 550 /public_html/favicomatic: No such file or directory

### ISSUE THREAD

**Issue by simonbrage** [SamKirkland/FTP-Deploy-Action#369]
**Bug Description**
I am getting `FTPError: 550 /public_html/favicomatic: No such file or directory` when deploying. I don't even have a `favicomatic`-folder in my `public_html`-folder. The `favicomatic`-folder is placed in `public_html/img/favicomatic`, so it all seem kind of weird to me. Deploying still updates my website, but the action registers and error.

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: linux110.unoeuro.com
        username: simonbrage.dk
        password: ${{ secrets.password }}
        server-dir: ./public_html/

```

**My Action Log**
```
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 /public_html/favicomatic: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5254:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5095:44)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 550
}
Error: FTPError: 550 /public_html/favicomatic: No such file or directory```

**Comment by bvoat** [comment]
It's a problem that happened to me, too. It suddenly doesn't work.

**Comment by SamKirkland** [comment]
This action navigates in/out of folders to deploy only changed files. This has been a hard to recreate bug.

If you could post your full action log. Specifically I'm looking to recreate this hug so i can write some tests and fix it. Thanks.

**Comment by tehSIRius** [comment]
I have bumped into the same issue. It has happened to me for the second time but I do not have the previous log as it expired. Maybe it has to do with a previous version of the server directory? I had a different folder structure earlier and the workflow has started after the change.

All of the data got uploaded correctly. Only issue is the failing workflow badge in the repository 😅 

Here is my config
```yaml
name: Production Deployment

on:
  push:
    branches: prod

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: true

      - name: Build
        run: |
          pnpm build
      - name: Reset pnpm-lock.yaml
        run: |
          git checkout pnpm-lock.yaml
      - name: File Sanity Check
        run: ls build

      - name: Upload FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "build/client/"
          server-dir: "www/"
```

and here is the full log
```bash
 ----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
Last published on 📅 Sunday, February 14, 2021, 1:55 PM
----------------------------------------------------------------
Local Files:	28
Server Files:	24
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
📁 Create: assets
📁 Create: assets/src
📁 Create: assets/src/renderer
📄 Upload: 404.html
📄 Upload: assets/chunk-0efebcaf.js
📄 Upload: assets/chunk-4ed993c7.js
📄 Upload: assets/chunk-5335a9d3.js
📄 Upload: assets/chunk-8649acf1.js
📄 Upload: assets/chunk-9153d54c.js
📄 Upload: assets/entry-client-routing.19d306f2.js
📄 Upload: assets/entry-server-routing.75f37d10.js
📄 Upload: assets/Header.17f3d2d0.css
📄 Upload: assets/index.a35c69e8.css
📄 Upload: assets/jost-all-400-normal.19c2f793.woff
📄 Upload: assets/jost-latin-400-normal.a25da21f.woff2
📄 Upload: assets/jost-latin-ext-400-normal.155818f3.woff2
📄 Upload: assets/Me.406c08b5.jpg
📄 Upload: assets/src/renderer/_default.page.client.ab28a44a.js
📄 Upload: manifest.json
📄 Upload: vite-plugin-ssr.json
🔁 File replace: index.html
🔁 File replace: site.webmanifest
📄 Delete: about.txt    
📄 Delete: asset-manifest.json    
📁 Delete: static    
⚖️  File content is the same, doing nothing: android-chrome-192x192.png
⚖️  File content is the same, doing nothing: android-chrome-512x512.png
⚖️  File content is the same, doing nothing: apple-touch-icon.png
⚖️  File content is the same, doing nothing: favicon-16x16.png
⚖️  File content is the same, doing nothing: favicon-32x32.png
⚖️  File content is the same, doing nothing: favicon.ico
----------------------------------------------------------------
Making changes to 25 files/folders to sync server state
Uploading: 408 kB -- Deleting: 656 kB -- Replacing: 6.43 kB
----------------------------------------------------------------
creating folder "assets/"
creating folder "assets/src/"
creating folder "assets/src/renderer/"
uploading "404.html"
uploading "assets/chunk-0efebcaf.js"
uploading "assets/chunk-4ed993c7.js"
uploading "assets/chunk-5335a9d3.js"
uploading "assets/chunk-8649acf1.js"
uploading "assets/chunk-9153d54c.js"
uploading "assets/entry-client-routing.19d306f2.js"
uploading "assets/entry-server-routing.75f37d10.js"
uploading "assets/Header.17f3d2d0.css"
uploading "assets/index.a35c69e8.css"
uploading "assets/jost-all-400-normal.19c2f793.woff"
uploading "assets/jost-latin-400-normal.a25da21f.woff2"
uploading "assets/jost-latin-ext-400-normal.155818f3.woff2"
uploading "assets/Me.406c08b5.jpg"
uploading "assets/src/renderer/_default.page.client.ab28a44a.js"
uploading "manifest.json"
uploading "vite-plugin-ssr.json"
replacing "index.html"
replacing "site.webmanifest"
removing "about.txt"
File not found or you don't have access to the file - skipping...
removing "asset-manifest.json"
File not found or you don't have access to the file - skipping...
removing folder "/www/static"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't change directory to /www/static: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.2/dist/index.js:5254:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.2/dist/index.js:5095:44)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: 550
}
```
