### ISSUE TITLE
Using with Git Submodules?

### ISSUE THREAD

**Issue by cagrimmett** [SamKirkland/FTP-Deploy-Action#371]
When using this deploy action with git submodules (the submodules are public repos), the submodule does not get deployed as expected. The link shows as a zero byte file with the name of the submodule instead of the expected folder with the contents of the submodule.

Is there any special configuration needed to support submodules? Has anyone successfully gotten one to deploy with this action?

**Comment by NicolasArvani** [comment]
Idk if its too late but recently i've had the same issue. Turns out it's quite easy, its a configuration of the actions/checkout.
```YAML
- name: 2 - Getting latest code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
``` 
Use `recursive` in the submodule option if your submodules also have submodules. You can use `true` otherwise.
I only managed to make it work using a [PAT token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens), but my repos were private so it's probably that. You can try deploying without the token to see if it works.

You can check more info in the checkout repo @ [https://github.com/actions/checkout/tree/main](https://github.com/actions/checkout/tree/main)
