### ISSUE TITLE
The process "git" failed with exit code 8

### ISSUE THREAD

**Issue by vivekvc2021** [SamKirkland/FTP-Deploy-Action#372]
**Bug Description**
I tried pushing one of my changes to my website, and it normally works but for some reason my pushes started erroring with exit code 8. Why is this, and how do I fix it?

**My Action Config**
```yaml
`on: 
  push:
    branches:
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASS }}`
```

**My Action Log**
```
  git ftp push --force --auto-init --verbose --syncroot ./ --user *** --passwd *** ***
 Fri Feb  3 16:13:47 UTC 2023: git-ftp version 1.6.0 running on Linux 4dc1[9](https://github.com/ICAN-dev-team/ICAN2020/actions/runs/4085887734/jobs/7044463032#step:4:10)1f3b79e 5.15.0-[10](https://github.com/ICAN-dev-team/ICAN2020/actions/runs/4085887734/jobs/7044463032#step:4:11)31-azure #38-Ubuntu SMP Mon Jan 9 12:49:59 UTC 2023 x86_64 GNU/Linux
  Fri Feb  3 16:13:47 UTC 2023: Forced mode enabled.
  Fri Feb  3 16:13:47 UTC 2023: Auto init if needed.
  Fri Feb  3 16:13:47 UTC 2023: Using syncroot ./ if exists.
  Fri Feb  3 16:[13](https://github.com/ICAN-dev-team/ICAN2020/actions/runs/4085887734/jobs/7044463032#step:4:14):47 UTC 2023: Syncroot is './'.
  Fri Feb  3 16:13:47 UTC 2023: fatal: Not a Git project? Exiting...
```
