### ISSUE TITLE
Deploying Next.js to cPanel

### ISSUE THREAD

**Issue by 4886Talga** [SamKirkland/FTP-Deploy-Action#373]
Is it posible to get example of how to deploy Next.js application to cPanel.

**Comment by janbiasi** [comment]
This is how we did it together with Next.js' SSG, maybe this will help to get started.

1. Adjust the build script to also create an export
```json
"scripts": {
  "build": "next build && next export"
}
```

2. Deploy to a webserver
```yaml
- run: npm run build

- name: Deploy Website
   uses: SamKirkland/FTP-Deploy-Action@4.3.0
   with:
     server: ${{ secrets.FTP_SERVER }}
     username: ${{ secrets.FTP_USERNAME }}
     password: ${{ secrets.FTP_PASSWORD }}
     local-dir: ./out/
     server-dir: webserver/path/
```
