### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 8

### ISSUE THREAD

**Issue by alvin-kiveu** [SamKirkland/FTP-Deploy-Action#375]
**Bug Description**

I have being getting this error and i can't find a way to fix it,  please help

**My Action Config**
```yaml
name: Deploy to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      # Deploy to cPanel
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
```
