### ISSUE TITLE
FTPError: 421

### ISSUE THREAD

**Issue by michael-letcher** [SamKirkland/FTP-Deploy-Action#382]
**Bug Description**

**My Action Config**
```yaml
      - name: 📂 FTP Deploy
        if: success()
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.X.com.au
          username: X
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/X/
          server-dir: ./public_html/X/
          dry-run: true
```

Also tried: `ftpes://ftp.X.com.au`

**My Action Log**
```
FTPError: 421-Sorry, cleartext sessions and weak ciphers are not accepted on this server.
421 Please reconnect using TLS security mechanisms.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5254:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5095:44)
    at Socket.emit (node:events:5[27](https://github.com/Smartercare/portal/actions/runs/4335600358/jobs/7570307272#step:6:28):[28](https://github.com/Smartercare/portal/actions/runs/4335600358/jobs/7570307272#step:6:29))
    at addChunk (node:internal/streams/readable:[31](https://github.com/Smartercare/portal/actions/runs/4335600358/jobs/7570307272#step:6:32)5:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 421
}
Error: FTPError: 421-Sorry, cleartext sessions and weak ciphers are not accepted on this server.
421 Please reconnect using TLS security mechanisms.
```
