### ISSUE TITLE
SFTP upload - Process '/usr/bin/git' failed with exit code 5

### ISSUE THREAD

**Issue by donroyco** [SamKirkland/FTP-Deploy-Action#384]
**Bug Description**
The original issue in #367 got solved, but it leaves a lot of people with another error when using SFTP:

> Error: The process '/usr/bin/git' failed with exit code 5

The patch that got introduced to solve #367 did not work for me.

Current version:  
> git-ftp version 1.6.0 running on Linux cdcd85627b15 5.15.0-1034-azure #41~20.04.1-Ubuntu SMP Sat Feb 11 17:02:42 UTC 2023 x86_64 Linux

Last working version (for me):
> git-ftp version 1.6.0 running on Linux a0d45716b585 5.15.0-1031-azure #38~20.04.1-Ubuntu SMP Mon Jan 9 18:23:48 UTC 2023 x86_64 GNU/Linux

**My Action Config**
```yaml
- name: Deploy to LE
        uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch
        with:
          ftp-server: ${{ secrets.SFTP_SERVER }}
          ftp-username: ${{ secrets.SFTP_USERNAME }}
          ftp-password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: public
          git-ftp-args: --insecure
```

**My Action Log**
```
  Thu Mar  9 13:13:45 UTC 2023: git-ftp version 1.6.0 running on Linux cdcd85627b15 5.15.0-1034-azure #41~20.04.1-Ubuntu SMP Sat Feb 11 17:02:42 UTC 2023 x86_64 Linux
  [...]
  Thu Mar  9 13:13:45 UTC 2023: Path is 'www/'.
  Thu Mar  9 13:13:45 UTC 2023: The remote sha1 is saved in file '.git-ftp.log'.
  Thu Mar  9 13:13:45 UTC 2023: Check if curl is functional.
  Thu Mar  9 13:13:45 UTC 2023: fatal: Protocol 'sftp' not supported by curl, exiting...
Error: The process '/usr/bin/git' failed with exit code 5
✅ Deploy Complete
```
Thank you for looking into it. I am happy to help in testing anything.
