### ISSUE TITLE
Feature request: support FTP Active mode

### ISSUE THREAD

**Issue by jo-chemla** [SamKirkland/FTP-Deploy-Action#386]
**Bug Description**
The FTP Push github action won't work for my workflow, probably because my FTP server is only accessible through **Active** mode. 

Trying to setup this ftp server for Passive mode was not successful after several attempts (just a summary why I'd like to use Active FTP mode rather than passive)
 - IIS FTP Server 10.0 on Windows server 2016 on an azure VM, 
 - with inbound and outbound firewall rules, + allow in-out ports ranges 5000-5100 on Network-Security-Group and firewall, 
 - trying NIC public IP or private IP in FTP Firewall support External IP Address of Firewall, and setting same port range 5000-5100
 - and editing various authorizations of directory listing, folder sharing properties etc.

Note that in Filezilla I can access my FTP (not SFTP) on port 21, using explicit TLS over FTP if available, and normal logon type with username/password. I can do so in Active mode in filezilla settings but directory listing does not work in passive mode with the subsequent logs: 
```
Status:	Connecting to 1.2.3.4:21...
Status:	Connection established, waiting for welcome message...
Status:	Initializing TLS...
Status:	TLS connection established.
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is current directory.
Command:	TYPE I
Response:	200 Type set to I.
Command:	PASV
Response:	227 Entering Passive Mode (1.2.3.4,19,137).
Command:	LIST
Response:	150 Opening BINARY mode data connection.
Error:	Connection timed out after 20 seconds of inactivity
Error:	Failed to retrieve directory listing
```

**My Action Config**
```yaml
# From actions/ftp-deploy https://github.com/marketplace/actions/ftp-deploy
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: '/test/'
        local-dir: './dist/'
        dry-run: false
        log-level: verbose
        protocol: ftp
        port: 21
```

**My Action Log**
```
Local state created
Connected to 1.2.3.4:[21](https://github.com/repo/actions/runs/4418908812/jobs/7746646900#step:5:22) (No encryption)
< [22](https://github.com/repo/actions/runs/4418908812/jobs/7746646900#step:5:23)0 Microsoft FTP Service

> AUTH TLS
< 534 Local policy on server does not allow TLS secure connections.

Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 534 Local policy on server does not allow TLS secure connections.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5254:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5095:44)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:[23](https://github.com/repo/actions/runs/4418908812/jobs/7746646900#step:5:24)) {
  code: 5[34](https://github.com/repo/actions/runs/4418908812/jobs/7746646900#step:5:35)
}
Error: FTPError: 534 Local policy on server does not allow TLS secure connections.


Other error: 
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.
----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5288:58)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:5[27](https://github.com/repo/actions/runs/4417947826/jobs/7766677614#step:5:28):[28](https://github.com/repo/actions/runs/4417947826/jobs/7766677614#step:5:29))
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Error: Error: Timeout (control socket)
```

Checking  the FTP server logs (an IIS FTP server on an azure VM with Network Security Group correctly setup), is seems that connection is closed after PASV mode is set.
