### ISSUE TITLE
Error: FTPError: 451-Error during read from data connection

### ISSUE THREAD

**Issue by Cristishor201** [SamKirkland/FTP-Deploy-Action#387]
**Bug Description**
on issue #77 
> @mhdizmni `SamKirkland/FTP-Deploy-Action@4.3.3` does not support SFTP which is required by some hosts like WPEngine.

I confirm also that I can not use SFTP.

**My Action Config**
```
name: Publish Website to CPanel
on: push # on debug only
  #push:
  #  tags:
  #    - '*1.*' # matching pattern, i.e. 1.0.0, v1.1.0
  #    - '1.*'

jobs:
  build:
    name: Build and deploy the website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v3 because, require node 16
        
      - name: Deploy website with FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./site/
          server-dir: ./
          port: 21
          protocol: ftps
          exclude: |
            *.psd
            images/processings/**
```

**My Action Log**
```
FTPError: 451-Error during read from data connection
451-Transfer aborted
451 0.176 seconds (measured here), 90.66 Kbytes per second
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5[254](https://github.com/Cristishor201/cristishor.net/actions/runs/4406811746/jobs/7719694841#step:3:255):39)
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5095:44)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 451
}
Error: FTPError: 451-Error during read from data connection
451-Transfer aborted
451 0.176 seconds (measured here), 90.66 Kbytes per second
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Deploy website with FTP
```
