### ISSUE TITLE
Deployed Laravel Site has an error

### ISSUE THREAD

**Issue by keanallen** [SamKirkland/FTP-Deploy-Action#388]
**Bug Description**
No errors during FTP deploy. But when I access my site I got an error:

```
is_dir(): open_basedir restriction in effect. File(/home/runner/work/lara-api/lara-api/storage/logs) is not within the allowed path(s): (/www/wwwroot/api-stg.laravel.lb.com:/tmp/)

```

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
    
     name: Deploy to staging
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: my.server.com
          username: my-user-name+
          password: my-password
          exclude: ".git*"
```

**My Action Log**
```
IT SUCCESSFULLY UPLOADED!
```
