### ISSUE TITLE
Multiple git branch and differenct FTP folder

### ISSUE THREAD

**Issue by gentlemoore** [SamKirkland/FTP-Deploy-Action#39]
Hello SamKirkland

Thanks once again for your response, it was helpful.
But I have another issue  related to issue no #37, which is, I want to do multiple deployment based on git branch

- uses: actions/checkout@master TO FTP::production
AND
- uses: actions/checkout@development TO FTP::development 

Thanks

**Comment by SamKirkland** [comment]
Closed out - answered on issue #37 

----------------
See response below

I'd approach this by creating two action yaml files. One for the dev environment, another for production. [See github's documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration)

```yaml
on:
  # Trigger only for the development branch
  # Only trigger on push. You can also trigger this on [push, pull_requests] etc...
  push:
    branches:
      - development
name: Publish Development Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy to first folder
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.samkirkland.com
        FTP_USERNAME: devEnvFTPAccount
        FTP_PASSWORD: ${{ secrets.DEV_FTP_PASSWORD }}
        ARGS: --delete
```

Then create another yaml file and tell it to run only on the master branch
```yaml
on:
  # Trigger only for the development branch
  # You can also trigger this on pull_requests, etc...
  push:
    branches:
      - master
name: Publish Production Website
# see above ...
```
