### ISSUE TITLE
FTPError: 550 Unknown error 183.

### ISSUE THREAD

**Issue by tskopen** [SamKirkland/FTP-Deploy-Action#393]
**Bug Description**
I run the workflow and everything works for about 5min, but stops when it gets to a certain point and I get this error

**My Action Config**
```yaml
on: workflow_dispatch
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server:  *censored*
        username: *censored*
        password: ${{ secrets.FTP_PASSWORD }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          fileToExclude.txt
```

**My Action Log**
https://mcpaste.io/0942a5eaf94c08bb
```
