### ISSUE TITLE
Bump SamKirkland/FTP-Deploy-Action from 4.3.3 to 4.3.4 from dependabot failed

### ISSUE THREAD

**Issue by ybayle** [SamKirkland/FTP-Deploy-Action#394]
**Bug Description**
Dear developer,
- 4.3.3 is working on my repo.
- dependabot automatically created a PR and tried to upgrade to 4.3.4 but I've got this `Error: Input required and not supplied: server`
- could you tell me what I'm doing wrong? Thanks!

**My Action Config**
```yaml
name: CI Website
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.<SOMETHING> }}
        username: ${{ secrets.<SOMETHING> }}
        password: ${{ secrets.<SOMETHING> }}
        local-dir: ./<SOMETHING>/vitrine/
        server-dir: httpdocs/<SOMETHING>/
        log-level: verbose
        port: 21
        protocol: ftp
        timeout: 60000
```

**My Action Log**
```
    Error: Error: Input required and not supplied: server
```
