### ISSUE TITLE
connect ECONNREFUSED ***:21

### ISSUE THREAD

**Issue by xyhcode** [SamKirkland/FTP-Deploy-Action#397]
**Bug Description**
Error: connect ECONNREFUSED ***:21 (control socket)，I opened the FTP port

**My Action Config**
```yaml
      - name: Upload Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./public/
          server-dir: /opt/www/tblog/
```

**My Action Log**
```
Error: connect ECONNREFUSED ***:21
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '***',
  port: 21
}
Error: Error: connect ECONNREFUSED ***:21 (control socket)
```
