### ISSUE TITLE
Rename Files

### ISSUE THREAD

**Issue by Zediz** [SamKirkland/FTP-Deploy-Action#399]
**Bug Description**
When I rename a file locally and then push, the action run and complete all the jobs. But when i see on the server I got duplicated file, one of them has the old name, and the other one has the new name.

**My Action Config**
```yaml
name: build and deploy
on:
  push: 
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@main
#       - name: Install dependencies
#         run: npm ci
#       - name: Build Dependencies
#         run: npm run build
      - name: Archive Angular App
        uses: actions/upload-artifact@main
        with:
          name: app
          path: client/dist
      - name: Archive API
        uses: actions/upload-artifact@main
        with:
          name: api
          path: api
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download App
        uses: actions/download-artifact@main
        with:
          name: app
          path: ./public_html
      - name: Download LMS API
        uses: actions/download-artifact@main
        with:
          name: api
          path: ./public_html/api
      - name: See Directories
        run: ls -R
      - name: Sync Files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: ftp.mindtech.com.mx
          username: ${{ secrets.USER }}
          password: ${{ secrets.FTP_PASSWORD }}
```

**My Action Log**
```
   # Paste Log here
   # you may want enable verbose logging with   log-level: verbose
```
