### ISSUE TITLE
Syncronization of subdir "lib" fails

### ISSUE THREAD

**Issue by gabkol** [SamKirkland/FTP-Deploy-Action#40]
**Bug Description**
If I try to sync a project with a subdirectory called lib, the deployment will fail.

**My Action Config**
```yaml
on:
  push:
    branches:
      - master
name: Publish Website over SFTP
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: 
        FTP_USERNAME: 
        FTP_PASSWORD: 
        METHOD: sftp
        PORT: 22
        LOCAL_DIR: public
        ARGS: --delete --transfer-all --no-empty-dirs
```

**My Action Log**
```
   mirror: Access failed: No such file (/lib)
```

**Workaround**
Rename the directory "lib" to "libs" and everything works fine.
