### ISSUE TITLE
Error: Error: getaddrinfo ENOTFOUND *** (control socket)

### ISSUE THREAD

**Issue by ckobasti77** [SamKirkland/FTP-Deploy-Action#400]
**Bug Description**
Getting **My Action Log** error when i try to connect it with my cPanel.
Its React app with NodeJS backend that is hosted on free hosting service.
So React app on cPanel with backend on free service.

**My Action Config**
```yaml
on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
        username: ${{ secrets.GIT_CPANEL_REACT_USER }}
        password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
        protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
        local-dir: ./src/
```

**My Action Log**
```
  Error: Error: getaddrinfo ENOTFOUND *** (control socket)
```

**Comment by talhaa99** [comment]
I also got the same error

```
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge

----------------------------------------------------------------
---------------  🔥🔥🔥 A error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------
The server "***" doesn't seem to exist. Do you have a typo?

----------------------------------------------------------------
----------------------  Full Error below  ----------------------
Error: getaddrinfo ENOTFOUND *** (control socket)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:[26](https://github.com/Astrosteem/Astrosteem-Backend/actions/runs/4958576036/jobs/8871619717#step:6:27)) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '***'
}
Error: Error: getaddrinfo ENOTFOUND *** (control socket)
```

This is the .yml file

```
on:
  push:
    branches:
      - dev
name: 🚀 Deploy website on push (DEV)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
```
