### ISSUE TITLE
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

### ISSUE THREAD

**Issue by bhekor** [SamKirkland/FTP-Deploy-Action#402]
I'm using Namecheap and it was working perfectly before now. I have disabled Proxied on Cloudflare, because I'm using Cloudflare.

Run SamKirkland/FTP-Deploy-Action@v4.3.4
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5288:33)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:5[16](https://github.com/username/app/actions/runs/5106021444/jobs/9177966952#step:9:17):8)
    at listOnTimeout (node:internal/timers:559:[17]((https://github.com/username/app/actions/runs/5106021444/jobs/9177966952#step:9:18))
    at processTimers (node:internal/timers:502:7)
Error: Error: Timeout (control socket)

**Comment by xannasavin** [comment]
I have the very same issue

```
Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5288:33)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:5[27](https://github.com/xannasavin/YOURLS/actions/runs/5132500397/jobs/9233873454#step:3:28):[28](https://github.com/xannasavin/YOURLS/actions/runs/5132500397/jobs/9233873454#step:3:29))
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Error: Error: Timeout (control socket)
```

**Comment by thechandanbhagat** [comment]
Any Updates?  I am also facing the same issue
![2023-06-05,Mon,15-45-23](https://github.com/SamKirkland/FTP-Deploy-Action/assets/6848264/fa3d6e1a-d7a2-41f9-82b9-0e24b4d1ca12)

**Comment by AffiTheCreator** [comment]
same here

**Comment by dersonsena** [comment]
I was having this same problem and saw in [another issue](https://github.com/SamKirkland/FTP-Deploy-Action/issues/239) that someone else was having problems with special characters or spaces in the password.

My solution was: I created a password with **only letters and numbers** and the problem no longer occurred, try that.

**Comment by xannasavin** [comment]
I updated my password to alphanumerical, but it did not solve the issue

**Comment by xannasavin** [comment]
```yaml
# https://github.com/marketplace/actions/ftp-deploy
# 08.03.2023

name: 🚀 Deploy website on push

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3.4.0

      # https://github.com/actions/checkout
      - name: Checkout WP Plugin
        uses: actions/checkout@v3.4.0
        with:
          repository: XXX
          token: ${{ secrets.my_pat }}
          path: mu-plugins

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            .git*
            .git*/**
            .github/*
           [...]
```

```
Run SamKirkland/FTP-Deploy-Action@4.3.3
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5288:58)
    at Object.onceWrapper (node:events:6[41](https://github.com/xannasavin/fuehringer/actions/runs/5209528020/jobs/9399480241#step:4:42):28)
    at Socket.emit (node:events:527:28)
    at Socket._onTimeout (node:net:516:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:[50](https://github.com/xannasavin/fuehringer/actions/runs/5209528020/jobs/9399480241#step:4:51)2:7)
Error: Error: Timeout (control socket)
```
