### ISSUE TITLE
Delete 

### ISSUE THREAD

**Issue by horatiu665** [SamKirkland/FTP-Deploy-Action#405]
**Bug Description**
I think my website wasn't reading the capitalized SoMe/ folder even tho locally I renamed it to some/, so I renamed it to sm/ so the server can consider it totally different name and make it work. But it failed on deleting. see log below.

I'm guessing there is a bug related to SoMe vs some    ..... I now learned never to use capitals in folder structure :)

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.horatiuromantic.com
        username: horatiuromantic.com
        password: ${{ secrets.FTP_PASS }}
        local-dir: ./public/
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/unused_workflows/**
```

**My Action Log**
```
[...]
uploading "img/sm/youtube.svg"
uploading "img/sm/youtube2.svg"
uploading "img/sm/youtube3.svg"
replacing "some_links.php"
removing folder "/img/SoMe"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Requested action not taken. File unavailable (e.g., file not found, no access).
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5252:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:50[96](https://github.com/horatiu665/hr-web/actions/runs/5242293485/jobs/9465515248#step:3:97):44)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 550
}
```
