### ISSUE TITLE
Failed to download action

### ISSUE THREAD

**Issue by ermirbeqiraj** [SamKirkland/FTP-Deploy-Action#41]
**Bug Description**
Fails to download v3 action
**My Action Config**
```yaml
name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build DataEntry/DataEntry.sln --configuration Release
    - name: Publish
      run: dotnet publish DataEntry/DataEntry.MVC/DataEntry.MVC.csproj --configuration Release --output PublishResult
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://ftp.........
        ftp-username: ftpusernameinhere.....
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: PublishResult
        git-ftp-args: --lock --remote-root=data-entry\src
```

**My Action Log**
```
Failed to download action 'https://api.github.com/repos/SamKirkland/FTP-Deploy-Action/tarball/3.0.0'. Error Response status code does not indicate success: 404 (Not Found).

```
