### ISSUE TITLE
Deploy dist/build folder only

### ISSUE THREAD

**Issue by edemking** [SamKirkland/FTP-Deploy-Action#410]
Hi there,

There comes a time you would like to deploy just the built files only.

Even as you have "Build and Publish React/Angular/Vue Website" there could be a request by someone to deploy to a different server and you may want to deploy just the built files.

How can that be done?

Please help.

**Comment by quiet-programmer** [comment]
Hi @edemking I had some issues but went through the docs and saw you can do this by adding this commands on the "with" call

```
with:
   server: ${{ secrets.ftp_server }}
   username: ${{ secrets.ftp_username }}
   password: ${{ secrets.ftp_password }}
   server-dir: /public_html/
   dangerous-clean-slate: true
   local-dir: ./dist/
```

This should help you out and you can close this issue... Thank You

**Comment by quiet-programmer** [comment]
> Hi there,
> 
> There comes a time you would like to deploy just the built files only.
> 
> Even as you have "Build and Publish React/Angular/Vue Website" there could be a request by someone to deploy to a different server and you may want to deploy just the built files.
> 
> How can that be done?
> 
> Please help.

Hi @edemking I had some issues but went through the docs and saw you can do this by adding this commands on the "with" call

```
with:
   server: ${{ secrets.ftp_server }}
   username: ${{ secrets.ftp_username }}
   password: ${{ secrets.ftp_password }}
   server-dir: /public_html/
   dangerous-clean-slate: true
   local-dir: ./dist/
```

This should help you out and you can close this issue... Thank You
