### ISSUE TITLE
Can't upload node_modules even with custom `exclude`

### ISSUE THREAD

**Issue by juanbomfim22** [SamKirkland/FTP-Deploy-Action#411]
**Bug Description**
Can't upload node_modules even with custom `exclude`

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy: 
   - name: 📂 Sync files using FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SMARTERASP_FTP_SERVER }}
        username: ${{ secrets.SMARTERASP_FTP_USERNAME_BACKEND }}
        password: ${{ secrets.SMARTERASP_FTP_PASSWORD_BACKEND }} 
        exclude: |
              **/.git/**
```

**My Action Log**
```
Using the following excludes filters: ["**/.git*","**/.git*/**"]
Creating local state at ./.ftp-deploy-sync-state.json
Local state created
Connected to 205.144.171.212:21 (No encryption)
< 220 Microsoft FTP Service

Login security: No encryption
> USER ***
< 331 Password required

> PASS ###
< 230 User logged in.

> FEAT
< 211-Extended features supported:
 LANG EN*
 UTF8
 AUTH TLS;TLS-C;SSL;TLS-P;
 PBSZ
 PROT C;P;
 CCC
 HOST
 SIZE
 MDTM
 REST STREAM
211 END

> TYPE I
< 200 Type set to I.

> STRU F
< 200 STRU F ok.

> OPTS UTF8 ON
< 200 OPTS UTF8 command successful - UTF8 encoding now ON.

  changing dir to ./
> MKD .
< 550 Access is denied. 

> CWD .
< 250 CWD command successful.

  dir changed
Trying to find optimal transfer strategy...
> EPSV
< 229 Entering Extended Passive Mode (|||40003|)

Optimal transfer strategy found.
> RETR .ftp-deploy-sync-state.json
< 125 Data connection already open; Transfer starting.

Downloading from 205.144.171.212:40003 (No encryption)
download progress for ".ftp-deploy-sync-state.json". Progress: 0 bytes of 0 bytes
< 226 Transfer complete.

download progress for ".ftp-deploy-sync-state.json". Progress: 58063 bytes of 58063 bytes
----------------------------------------------------------------
Last published on 📅 Sunday, July 30, 2023, 4:06 AM
----------------------------------------------------------------
Local Files:	273
Server Files:	273
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
🔁 File replace: web.config
⚖️  File content is the same, doing nothing: .dockerignore
⚖️  File content is the same, doing nothing: .env
⚖️  File content is the same, doing nothing: .env.example 
... (NO node_modules)
----------------------------------------------------------------
Making changes to 1 file/folder to sync server state
Uploading: 0 B -- Deleting: 0 B -- Replacing: 683 B
----------------------------------------------------------------
replacing "web.config"
> EPSV
< 229 Entering Extended Passive Mode (|||40001|)

> STOR web.config
< 125 Data connection already open; Transfer starting.

Uploading to 205.144.171.212:40001 (No encryption)
upload progress for "web.config". Progress: 0 bytes of 58063 bytes
upload progress for "web.config". Progress: 683 bytes of 58746 bytes
< 226 Transfer complete.

  file replaced
----------------------------------------------------------------
🎉 Sync complete. Saving current server state to "./.ftp-deploy-sync-state.json"
> EPSV
< 229 Entering Extended Passive Mode (|||40048|)

> STOR .ftp-deploy-sync-state.json
< 150 Opening BINARY mode data connection.

Uploading to 205.144.171.212:40048 (No encryption)
upload progress for ".ftp-deploy-sync-state.json". Progress: 0 bytes of 58746 bytes
upload progress for ".ftp-deploy-sync-state.json". Progress: 58063 bytes of 116809 bytes
< 226 Transfer complete.

> QUIT
```
