### ISSUE TITLE
Transferring an empty file may close the connection prematurely

### ISSUE THREAD

**Issue by chsxf** [SamKirkland/FTP-Deploy-Action#412]
**Bug Description**
The transfer of an empty file closes the connection prematurely.
The file `Empty.twig` was previously empty. By adding a commented content, the action went through. This has been reproduced many times.

**My Action Config**
```yaml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: ''

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.webmo.fr
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        server-dir: analytics/
        exclude: |
          **/.git*
          **/.git*/**
          **/secrets.php
```

**My Action Log**
```
Many other files before that that were uploaded successfully
...
 uploading "vendor/chsxf/mfx/src/templates/Empty.twig"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Server sent FIN packet unexpectedly, closing connection.
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5098:56)
    at TLSSocket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: Error: Server sent FIN packet unexpectedly, closing connection.
```
