### ISSUE TITLE
Support for sftp? 

### ISSUE THREAD

**Issue by fhg-isi** [SamKirkland/FTP-Deploy-Action#418]
Could you please clarify if sftp is supported and if so, give an example on how to use it?
I tried with

```
uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SFTP_URL }}
        port: 22
        timeout: 60000
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
        local-dir: micat/dist/
```

and get timeout errors. A connection with WinScp works. 

Related:

https://stackoverflow.com/questions/63697142/how-to-sftp-with-github-actions
