### ISSUE TITLE
FTPError: 550 ~partytown: No such file or directory

### ISSUE THREAD

**Issue by m1chale** [SamKirkland/FTP-Deploy-Action#422]
**Bug Description**
Im not able to deploy my website code built with GatsbyJS.
I always get the error 550 with folder "~partytown".
Im not sure, maybe its because of the "~" ?

Thanks for your help!

**My Action Config**
```yaml
     - name: 📂 Sync files by FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # dangerous-clean-slate: true
          server: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PW }}
          protocol: ftps
          port: 21
          local-dir: "./public/"
          server-dir: "./test-me/"
```

**My Action Log**
```
...
----------------------------------------------------------------
Making changes to 337 files/folders to sync server state
Uploading: 40.2 MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder "_gatsby/"
creating folder "_gatsby/slices/"
creating folder "~partytown/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 ~partytown: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5252:39)
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5096:44)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 550
}
Error: FTPError: 550 ~partytown: No such file or directory
```
