### ISSUE TITLE
dist folder not uploaded

### ISSUE THREAD

**Issue by jorenbroekema** [SamKirkland/FTP-Deploy-Action#43]
**Bug Description**

I want to use this action for uploading the resulting folder of `npm run build` which is a dist folder in root. My workflow properly builds it and listing the folders shows it's correct, but then the build folder is not uploaded to SFTP as intended. 

I might be mistaken but I think this has to do with it using git-ftp under the hood now since v3? 
Which I think checks which files have been changed and committed? 

The thing is, I have the /dist/ folder in my `.gitignore`, because I don't want to have that folder be part of my version control, because it isn't source code. It's production / distribution code, only to be built when I push something new to master, and then to be deployed on my server.

**My Action Config**
```yaml
on:
  push:
    branches:
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build Project
      run: |
        npm install
        npm run build --if-present

    - name: List output files
      run: ls

    - name: List dist files
      run: cd dist && ls

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://188.166.61.51
        ftp-username: joren
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure --remote-root home/joren/yc-bank-frontend --all
        local-dir: dist
```

I put the --all flag just to see if it would help but it doesn't.

**My Action Log**
```
     Wed Feb 19 20:47:47 UTC 2020: The remote sha1 is saved in file '.git-ftp.log'.
  Wed Feb 19 20:47:47 UTC 2020: Check if curl is functional.
  Wed Feb 19 20:47:47 UTC 2020: Retrieving last commit from sftp://joren:***@188.166.61.51/home/joren/yc-bank-frontend/.
  #=#=#                                                                         
  ##O#- #                                                                       
  ##O=#  #                                                                      
  #=#=-#  #                                                                     
  -#O#- #   #                                                                   
  -=#=#   #   #                                                                 
  -=O#- #  #    #                                                               
  -=O=#  #   #   #                                                              
  
  ######################################################################## 100.0%
  Wed Feb 19 20:47:50 UTC 2020: Taking all files.
  Wed Feb 19 20:47:50 UTC 2020: No files to sync. All changed files ignored.
  Wed Feb 19 20:47:50 UTC 2020: There are no files to sync.
  Wed Feb 19 20:47:50 UTC 2020: Uploading commit log to sftp://joren:***@188.166.61.51/home/joren/yc-bank-frontend/.git-ftp.log.
  #=#=#                                                                         
  ##O#- #                                                                       
  ##O=#  #                                                                      
  #=#=-#  #                                                                     
  -#O#- #   #                                                                   
  -=#=#   #   #                                                                 
  -=O#- #  #    #                                                               
  -=O=#  #   #   #                                                              
  -=O=-#  #    #   #                                                            
  Wed Feb 19 20:47:52 UTC 2020: Last deployment changed from aadf920b6030699d9137fe1d56d497a8bed7021e to 7462f39642bea68d75e12f8d05a102afeea457b2.
✅ Deploy Complete
```

I wasn't sure if the above is the action log you meant, let me know if you need more info.

Here's the repo btw: https://github.com/jorenbroekema/yc-bank-frontend/
