### ISSUE TITLE
add the 'include'  parameter

### ISSUE THREAD

**Issue by okwareddevnest** [SamKirkland/FTP-Deploy-Action#436]
**Bug Description**
The `FTP-Deploy-Action` lacks an `include` parameter, which is necessary for specifying files to upload. Currently, the action only provides an exclude parameter to define files to ignore during deployment. This makes it cumbersome to deploy specific files or directories, especially when dealing with a large number of files where excluding individually would not be practical.

**My Action Config**
```yaml
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        exclude: '**/*'
        include: next.tar.gz,server.js,package.json,package-lock.json
```

**My Action Log**
```
Invalid action input 'include'. Available expression contexts: `github`, `inputs`, `vars`, `needs`, `strategy`, `matrix`, `secrets`, `steps`, `job`, `runner`, `env`. Available expression functions: `hashFiles`
```

**Comment by Trainax** [comment]
Duplicate of #201 

You could achieve what you want by using the `exclude` option in reverse. Try using:

```yaml
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        exclude: !{next.tar.gz,server.js,package.json,package-lock.json}
```

Which excludes everything that doesn't match the values in the array

**Comment by christophechateau** [comment]
>       uses: SamKirkland/FTP-Deploy-Action@4.0.0
>       with:
>         exclude: !{next.tar.gz,server.js,package.json,package-lock.json}
> ```

Hi, 

This does not work. All my files are uploaded and not just the exception.

**Comment by Trainax** [comment]
> This does not work. All my files are uploaded and not just the exception.

Hi. That's quite odd... I've tried the pattern in the [glob tester](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%21%7Bnext.tar.gz%2Cserver.js%2Cpackage.json%2Cpackage-lock.json%7D&matches=false&tests=next.tar.gz&tests=server.js&tests=package.json&tests=package-lock.json&tests=test.txt&tests=test%2Fsam&tests=.git%2F&tests=.github%2F&tests=.git%2Ftest&tests=.gitattributes&tests=.gitignore&tests=.git%2Fconfig&tests=.git%2Ftest%2Ftest&tests=.github%2Fworkflows%2Fmain.yml&tests=node_modules%2Ffolder%2F&tests=node_modules%2Fotherfolder%2F&tests=subfolder%2Fnode_modules%2F) again and we can see that all files except those specified get matched (and thus excluded)... I don't know why it isn't working...

Just to be sure: are you using the latest version of this action (v4.3.5)?

**Comment by hansmorb** [comment]
Hey, sorry if this might be a noob question but I am having issues with the syntax mentioned above. I either keep getting: "Tags and anchors must be separated from the next token by white space " or "Incorrect type. Expected "string | number | boolean" from Github.

I have tried a different syntax like so:

```
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
       with:
         exclude: |
          !myfile.zip
```

-> Result: Everything got uploaded (with and 

```     - name: Upload zip
       uses: SamKirkland/FTP-Deploy-Action@v4.3.5
       with:
         exclude: ! myfile.zip
```

-> Result: Workflow not valid


```     - name: Upload zip
       uses: SamKirkland/FTP-Deploy-Action@v4.3.5
       with:
         exclude: !{myfile.zip}
```

-> Result: You have an error in your yaml syntax on line (exclude line)

```
    - name: Upload zip
       uses: SamKirkland/FTP-Deploy-Action@v4.3.5
       with:
         exclude: '!myfile.zip'
```

-> Result: Everything gets uploaded

```
     - name: Upload zip
       uses: SamKirkland/FTP-Deploy-Action@v4.3.5
       with:
         exclude: '!{myfile.zip}'
```

-> Result: Everything uploaded, same thing with full quotation marks.
