### ISSUE TITLE
Error: Unable to resolve action `SamKirkland/FTP-Deploy-Action@4.3.4`, unable to find version `4.3.4`

### ISSUE THREAD

**Issue by Mornevanzyl** [SamKirkland/FTP-Deploy-Action#440]
**Bug Description**
I've been getting a FTPError: 451-Error during read from data connection 451-Transfer aborted 451 0.214 seconds (measured here), 74.70 Kbytes per second.

I thought I'd start by updating to the latest version to see if that resolved the issue, but can't seem to use v4.3.4

**My Action Config**
```yaml
name: Publish Site to Interwebs

on:
  push:
    branches: [ main ]
jobs:
  schemas-deploy:
    name: Publish
    runs-on: ubuntu-latest  
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4

      - name: Upload images to site
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./assets/
```

**My Action Log**
```
Current runner version: '[2](https://github.com/NoxOrg/Images/actions/runs/7897598416/job/21553454676#step:1:2).3[13](https://github.com/NoxOrg/Images/actions/runs/7897598416/job/21553454676#step:1:16).0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `SamKirkland/FTP-Deploy-Action@4.3.4`, unable to find version `4.3.4`
```
