### ISSUE TITLE
Because deploy generally synchronizes all files again and not just the file I'm sending

### ISSUE THREAD

**Issue by pedro0506** [SamKirkland/FTP-Deploy-Action#441]
**Bug Description**
Because deploy generally synchronizes all files again and not just the file I'm sending?.

I understand that this synchronization should only occur on the first push, or am I wrong?

**My Action Config**
```yaml
on:
  push:
    branches:
      - main
      name: 🚀 Deploy website on push
      jobs:
        web-deploy:
          name: 🎉 Deploy
          runs-on: ubuntu-22.04
          steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2
      
            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                server: ${{ secrets.ftp_host }}
                username: ${{ secrets.ftp_user }}
                password: ${{ secrets.ftp_password }}
                server-dir: public_html/
          
```

**My Action Log**

![image](https://github.com/SamKirkland/FTP-Deploy-Action/assets/17099471/c50e4e07-6d17-46c7-93d8-992b73b524fb)
