### ISSUE TITLE
FTP Upload Fails Every Time

### ISSUE THREAD

**Issue by mazureth** [SamKirkland/FTP-Deploy-Action#442]
**Bug Description**
Every time I run the upload it fails in the same place with a connection refused error. The odd part is that it is able to create all the folders and upload 1 file before it fails. So I know the connection works at first. The same file fails every time, a font file. I'm not sure if I am hitting some limit or running into an unsupported filetype? I am able to manually FTP the project from my local machine using the same host and credentials with FileZilla. Any help would be greatly appreciated.

Also I noticed a typo:
"No file exists on the server "/debook-app/.ftp-deploy-sync-state.json" - this much be your first publish! 🎉"
---------------------------------------------------------------------------------------^
Probably should be:
"No file exists on the server "/debook-app/.ftp-deploy-sync-state.json" - this must be your first publish! 🎉"
---------------------------------------------------------------------------------------^

**My Action Config**
```
name: Auto Deploy to Live

on:
  workflow_dispatch:

jobs:
  web-deploy:

    name: Deploy Anuglar
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Build Angular app to live
      working-directory: ./
      run: npm install && npm run build

    - name: FTP Files to Ionic
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.IONOS_FTP_SERVER }}
        username: ${{ secrets.IONOS_FTP_USER }}
        password: ${{ secrets.IONOS_FTP_PASS }}
        local-dir: ./dist/debook.app/
        server-dir: /debook-app/
        # to remove older JS files with hashed names (main-[hash].js)
        dangerous-clean-slate: true
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@4.0.0
  with:
    server: ***
    username: ***
    password: ***
    local-dir: ./dist/debook.app/
    server-dir: /debook-app/
    dangerous-clean-slate: true
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
🗑️ Removing all files on the server because 'dangerous-clean-slate' was set, this will make the deployment very slow...
----------------------------------------------------------------
No file exists on the server "/debook-app/.ftp-deploy-sync-state.json" - this much be your first publish! 🎉
The first publish will take a while... but once the initial sync is done only differences are published!
If you get this message and its NOT your first publish, something is wrong.
----------------------------------------------------------------
Local Files:	35
Server Files:	35
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
➕ Upload: 3rdpartylicenses.txt
📁 Create: browser
📁 Create: browser/assets
📁 Create: browser/assets/fonts
➕ Upload: browser/assets/fonts/Satoshi-Black.ttf
➕ Upload: browser/assets/fonts/Satoshi-Light.ttf
➕ Upload: browser/assets/fonts/Satoshi-Medium.ttf
➕ Upload: browser/assets/fonts/Satoshi-Regular.ttf
📁 Create: browser/assets/media
➕ Upload: browser/assets/media/debookFavicon.png
➕ Upload: browser/assets/media/example.mp4
➕ Upload: browser/assets/media/iconLogo.svg
➕ Upload: browser/assets/media/textLogo.svg
➕ Upload: browser/favicon.ico
➕ Upload: browser/index.html
➕ Upload: browser/main-7TGU3GQM.js
📁 Create: browser/media
➕ Upload: browser/media/Satoshi-Black-CLK2FY4C.ttf
➕ Upload: browser/media/Satoshi-Light-CINRKHM2.ttf
➕ Upload: browser/media/Satoshi-Medium-QIL3OLQH.ttf
➕ Upload: browser/media/Satoshi-Regular-UEXLJ65B.ttf
➕ Upload: browser/polyfills-RT5I6R6G.js
➕ Upload: browser/scripts-LGHYJXS5.js
➕ Upload: browser/styles-CXEURODC.css
➕ Upload: prerendered-routes.json
📁 Create: server
➕ Upload: server/chunk-AZIHRZDC.mjs
➕ Upload: server/chunk-CKY3Q2WY.mjs
➕ Upload: server/chunk-O73ZHKXN.mjs
➕ Upload: server/chunk-VVCT4QZE.mjs
➕ Upload: server/index.server.html
➕ Upload: server/main.server.mjs
➕ Upload: server/polyfills.server.mjs
➕ Upload: server/render-utils.server.mjs
➕ Upload: server/server.mjs
----------------------------------------------------------------
Making changes to 35 files to sync server state
Uploading: 9.12 MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder "browser/"
creating folder "browser/assets/"
creating folder "browser/assets/fonts/"
creating folder "browser/assets/media/"
creating folder "browser/media/"
creating folder "server/"
uploading "3rdpartylicenses.txt"
uploading "browser/assets/fonts/Satoshi-Black.ttf"
Error: connect ECONNREFUSED 217.160.233.24:50880
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '217.160.233.24',
  port: 50880
}
Error: connect ECONNREFUSED 217.160.233.24:50880
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '217.160.233.24',
  port: 50880
}
----------------------------------------------------------------
Time spent hashing:               45 milliseconds
Time spent connecting to server:  1 second
Time spent deploying:             5 seconds (1.79 MB/second)
  - changing dirs:                2.9 seconds
  - logging:                      45 milliseconds
----------------------------------------------------------------
Total time:                       7.3 seconds
----------------------------------------------------------------
```
