### ISSUE TITLE
Logs says everything went well but no files were transferred to server

### ISSUE THREAD

**Issue by ow3ndesu** [SamKirkland/FTP-Deploy-Action#445]
**Bug Description**
I can't find where things are going wrong, my logs says everything went well but no files were transferred to server. Tried looking on other folders if maybe I misspelled or did something wrong but date modified shows nothing is new throughout the whole server. Also, folder specified was generated. That's off.

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME}}
        password: ${{ secrets.FTP_PASSWORD}}
        server-dir: testing.aecc.com.ph/
        dry-run: true
```
![Screenshot_4](https://github.com/SamKirkland/FTP-Deploy-Action/assets/65291500/6da0ebcb-bc1e-4269-9b18-069180b499e9)
![Screenshot_3](https://github.com/SamKirkland/FTP-Deploy-Action/assets/65291500/ff6beb71-aaed-4313-b53b-3d23f64a111e)

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@v4.3.5
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
No file exists on the server "testing.aecc.com.ph/.ftp-deploy-sync-state.json" - this must be your first publish! 🎉
The first publish will take a while... but once the initial sync is done only differences are published!
If you get this message and its NOT your first publish, something is wrong.
----------------------------------------------------------------
Local Files:	715
Server Files:	0
----------------------------------------------------------------
Calculating differences between client & server

UPLOAD HERE ...

🎉 Sync complete. Saving current server state to "testing.aecc.com.ph/.ftp-deploy-sync-state.json"
----------------------------------------------------------------
Time spent hashing: 933 milliseconds
Time spent connecting to server: 2.3 seconds
Time spent deploying: 32 milliseconds (4.23 GB/second)
  - changing dirs: 368 milliseconds
  - logging: 84 milliseconds
----------------------------------------------------------------
Total time: 1 minute 4.1 seconds
----------------------------------------------------------------

```
