### ISSUE TITLE
Deploy a .Net core build

### ISSUE THREAD

**Issue by lsvMoretti** [SamKirkland/FTP-Deploy-Action#45]
Hello, I love this action by the way it's very useful.

I am having some issues trying to use this with one of my .net core 3.1 builds. I am unsure on how to upload just the build of the .net core.

Heres a few outputs I am getting:

When going to the FTP deploy section:

```Run SamKirkland/FTP-Deploy-Action@3.0.0
/usr/bin/docker run --name e87b5248c6555427d54fedbd5ac9c14af2afed_17fc5a --label e87b52 --workdir /github/workspace --rm -e DOTNET_ROOT -e INPUT_FTP-SERVER -e INPUT_FTP-USERNAME -e INPUT_FTP-PASSWORD -e INPUT_LOCAL-DIR -e INPUT_GIT-FTP-ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/Los-Santos-V/Los-Santos-V":"/github/workspace" e87b52:48c6555427d54fedbd5ac9c14af2afed
Uploading files
  git ftp push --force --auto-init --verbose --syncroot Server/bin/Release/netcoreapp3.1 --user *** --passwd *** ftp://193.70.80.232
  Fri Feb 21 15:57:41 UTC 2020: git-ftp version 1.5.1 running on Linux 0e84ace6b059 5.0.0-1031-azure #33-Ubuntu SMP Thu Feb 6 22:26:13 UTC 2020 x86_64 GNU/Linux
  Fri Feb 21 15:57:41 UTC 2020: Forced mode enabled.
  Fri Feb 21 15:57:41 UTC 2020: Auto init if needed.
  Fri Feb 21 15:57:41 UTC 2020: Using syncroot Server/bin/Release/netcoreapp3.1 if exists.
  Fri Feb 21 15:57:41 UTC 2020: Host is '193.70.80.232'.
  Fri Feb 21 15:57:41 UTC 2020: User is '***'.
  Fri Feb 21 15:57:41 UTC 2020: Password is set.
  Fri Feb 21 15:57:41 UTC 2020: CACert is ''.
  Fri Feb 21 15:57:41 UTC 2020: Insecure is '0'.
  Fri Feb 21 15:57:41 UTC 2020: Proxy is ''.
  Fri Feb 21 15:57:41 UTC 2020: Path is ''.
  Fri Feb 21 15:57:41 UTC 2020: fatal: 'Server/bin/Release/netcoreapp3.1' is not a directory! Exiting...
⚠️ Failed to upload files
⚠️ Error deploying
##[error]The process 'git' failed with exit code 8
##[error]The process 'git' failed with exit code 8```




When I build with .net, it outputs my .dll here:

`Server -> /home/runner/work/Los-Santos-V/Los-Santos-V/Server/bin/Release/netcoreapp3.1/Server.dll`

My ftp local dir is set:

`local-dir: Server/bin/Release/netcoreapp3.1`

I have also set this to the full path above and also `local-dir: build`

**Comment by SamKirkland** [comment]
Hello!

I've done some testing to try to recreate this issue without actually trying to publish a folder that doesn't exist. My assumption is you aren't building the project in your action so that folder doesn't actually exist.

You have two options here:
1) Build your project on your machine and commit the dll's to github. Publish these files as you are attempting to above.
2) Build your project within your github action prior to running the deploy. You can [see an node example of this in the docs](https://github.com/SamKirkland/FTP-Deploy-Action#build-and-publish-reactangularvue-website), you'd replace the node sections with .net core. If you take this approach and get something working please let me know what your action yaml file is so I can add an example to the docs!

If you pick option #2 you'll have to add the built file to `.git-ftp-include` [see here](/SamKirkland/FTP-Deploy-Action#build-and-publish-reactangularvue-website)

**Comment by lsvMoretti** [comment]
Okay I'll try option 2 later on thanks.

Where should I place the .git-ftp-include?

**Comment by SamKirkland** [comment]
In the root (top most folder) of your project.

Let me know how it goes and if you need help.

**Comment by lsvMoretti** [comment]
I've been playing around with this for a bit but can't seem to get the files to upload.

```
name: Deploy Server

on:
  push:

jobs:
  build-server:
    name: Build Server
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build Server --configuration Release
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: MyFTPIp
        ftp-username: GitUser
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: home/runner/work/Los-Santos-V/Los-Santos-V/Server/bin/Release/netcoreapp3.1/
```

**Comment by SamKirkland** [comment]
1. Your path needs to be relative to your projects root folder. So it should be `bin/Release/netcoreapp3.1/`
2. The content of `.git-ftp-include` should also be relative. So `!bin/Release/netcoreapp3.1/`
3. Please ⭐️ this github project. IM SO CLOSE TO 200!!!!
4. Let me know if that works and I'll close out this issue and add the example to the readme

Here is a full demo of a .net core hello work app deployment (I'm using .net core v2.1 but you can change that). [See the git repo I put together](https://github.com/SamKirkland/net-core-example)
```yaml
on: push
name: Test FTP Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code from github
      uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.804 # SDK Version to use see https://dotnet.microsoft.com/download/dotnet-core
    
    - name: Build with dotnet
      run: dotnet build dotnet-core-hello-world.csproj --configuration Release
        
    - name: List output files
      run: find bin/ -print

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action-Typescript@master
      with:
        ftp-server: ftp://ftp.samkirkland.com/
        ftp-username: dotnet-core-action@samkirkland.com
        ftp-password: ${{ secrets.ftp_password }}
        local-dir: bin/Release/netcoreapp2.1/
```

**Comment by lsvMoretti** [comment]
Okay, I have it finding the files in the directory after build, I am using a folder called Server/ and inside that is my .csproj. I think the issue was I was using actions/checkout@master which cleaned up the bin directory.

However, it's not over yet! How can I update the git? I'm getting this issue on my FTP now.

` Dirty repository: Having uncommitted changes. Exiting...`

**Comment by Danda87** [comment]
This is not a solution to your problem, but maybe it helps someone. The way I do it is - I have a separate branch called "release", in my repository, and when I want to upload the changes to my web site I just create a Pull Request from my development branch to my "release" branch. My workflow gets triggered only when I merge my request.

**I never push my changes directly to my "release" branch!** Only by creating and reviewing a pull request.

Here's my workflow:
```yml
name: Build and deploy

on:
  pull_request:
    types: [closed]
    branches:
    - 'release'

jobs:
  Build-And-Deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.event.pull_request.merged
      with:
        fetch-depth: 2

    # setup dot net and build the project
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108 # SDK Version to use see https://dotnet.microsoft.com/download/dotnet-core
    - name: Remove old publish directory
      run: rm -rf publish_package
    - name: Build with dotnet
      run: dotnet publish api.csproj --configuration Release --output publish_package

    # commit chages
    - name: Add changes to Git tracking
      run: git add -A .
    - name: Commit changes
      uses: zwaldowski/git-commit-action@v1
    - name: Push changes to release branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: release

    # upload to ftp
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASS }}
        local-dir: publish_package/
```

I'm sure this can be done in a better way, but this is good enough for me!
