### ISSUE TITLE
FTPError: 553 Can't open that file: No such file or directory

### ISSUE THREAD

**Issue by ivcho02** [SamKirkland/FTP-Deploy-Action#450]
**Bug Description**

Hi team, 

The following error occurs on initial deploy: 
FTPError: 553 Can't open that file: No such file or directory

There is a similar ticket closed on this repo but the solution does not work for me because I don't have the sync file on the FTP (https://github.com/SamKirkland/FTP-Deploy-Action/issues/262)

**My Action Config**
```yaml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: 🚀 Deploy website on push (Master)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
        
      - name: Create .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer update --ignore-platform-reqs

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 775 storage

      - name: Clear Caches
        run: php artisan optimize:clear

      - name: Setup Database
        run: php artisan migrate --env=production --no-interaction

      - name: Storage link
        run: php artisan storage:link

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: .....
          username: .....
          password: .....
          exclude: |
            package-lock.json
            package.json
            readme.md
            webpack.mix.js
            **/.github
            **/.github*
            **/.tests*/**

```

**My Action Log**
```
uploading "vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php"
uploading "vendor/laravel/framework/src/Illuminate/View/View.php"
uploading "vendor/laravel/framework/src/Illuminate/View/ViewFinderInterface.php"
uploading "vendor/laravel/framework/src/Illuminate/View/ViewName.php"
uploading "vendor/laravel/framework/src/Illuminate/View/ViewServiceProvider.php"
uploading "vendor/laravel/homestead/.editorconfig"
uploading "vendor/laravel/homestead/.github/ISSUE_TEMPLATE.md"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 553 Can't open that file: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5263:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5107:44)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:345:11)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 553
}
Error: FTPError: 553 Can't open that file: No such file or directory
```

**Comment by ivcho02** [comment]
```
uploading "vendor/zendframework/zend-diactoros/src/StreamFactory.php"
uploading "vendor/zendframework/zend-diactoros/src/UploadedFile.php"
uploading "vendor/zendframework/zend-diactoros/src/UploadedFileFactory.php"
uploading "vendor/zendframework/zend-diactoros/src/Uri.php"
uploading "vendor/zendframework/zend-diactoros/src/UriFactory.php"
uploading "webpack.mix.js"
----------------------------------------------------------------
🎉 Sync complete. Saving current server state to "./.ftp-deploy-sync-state.json"
----------------------------------------------------------------
Time spent hashing: 1.9 seconds
Time spent connecting to server: 1.2 seconds
Time spent deploying: 1 hour 36 minutes 33.1 seconds (6.75 kB/second)
  - changing dirs: 27 minutes 28.4 seconds
  - logging: 160 milliseconds
----------------------------------------------------------------
Total time: 1 hour 36 minutes 37 seconds
----------------------------------------------------------------
```




Success with the following yml configuration:


```
name: 🚀 Deploye

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploying
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4.33

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer update --ignore-platform-reqs

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 775 storage

    - name: Clear Caches
      run: php artisan optimize:clear

    - name: Setup Database
      run: php artisan migrate --env=production --no-interaction

    - name: Storage link
      run: php artisan storage:link

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: .....
        username: .....
        password: .....

```



**PHP: 7.3.44
Laravel Framework: 5.7.29**
