### ISSUE TITLE
web.config missing from the deployment

### ISSUE THREAD

**Issue by PieterjanDeClippel** [SamKirkland/FTP-Deploy-Action#454]
**Bug Description**
![image](https://github.com/SamKirkland/FTP-Deploy-Action/assets/9629574/717b8c4f-2123-401a-b6d3-5cb65dfe22bf)

While the `web.config` file is clearly present after building the project, it's not being uploaded to the server.

**My Action Config**
```yaml
name: npm-publish

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:

    name: npm-publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run nx run-many -- --target=build --configuration=production

    - name: Move web.config
      run: mv dist/apps/video-player-demo/browser/web.config dist/apps/video-player-demo/

    - name: Test
      run: npm run nx run-many -- --target=test --browsers=ChromeHeadless --parallel=true

    ## ng-canvas-resizer
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-ng-canvas-resizer

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-ng-canvas-resizer/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-ng-canvas-resizer/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## player-provider
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-player-provider

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-player-provider/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-player-provider/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## player-progress
    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-player-progress/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-player-progress/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## video-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-video-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-video-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-video-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## ng-video-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-ng-video-player

    - name: Push to NPM
      id: publish_ng_video_player
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-ng-video-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-ng-video-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## facebook-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-facebook-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-facebook-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-facebook-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## mixcloud-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-mixcloud-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-mixcloud-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-mixcloud-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## soundcloud-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-soundcloud-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-soundcloud-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-soundcloud-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## spotify-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-spotify-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-spotify-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-spotify-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## streamable-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-streamable-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-streamable-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-streamable-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## twitch-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-twitch-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-twitch-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-twitch-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## vidyard-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-vidyard-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-vidyard-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-vidyard-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## vimeo-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-vimeo-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-vimeo-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-vimeo-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## wistia-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-wistia-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-wistia-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-wistia-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## youtube-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-youtube-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-youtube-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-youtube-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## file-player
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-file-player

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-file-player/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-file-player/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    ## playlist-controller
    - name: Upload code coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/libs/mintplayer-playlist-controller

    - name: Push to NPM
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-playlist-controller/package.json'
        registry: 'https://registry.npmjs.org'
        token: ${{ secrets.PUBLISH_NODE_TO_NPMJS_COM }}
        access: 'public'
        provenance: true

    - name: Push to Github
      uses: JS-DevTools/npm-publish@v3
      with:
        package: 'dist/libs/mintplayer-playlist-controller/package.json'
        registry: 'https://npm.pkg.github.com'
        token: ${{ github.token }}
        access: 'public'
        provenance: true

    - name: Publish through FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      if: ${{ steps.publish_ng_video_player.outputs.type }}
      with:
        server: mintplayer.com
        username: ${{ secrets.PUBLISH_FTP_USER }}
        password: ${{ secrets.PUBLISH_FTP_PWD }}
        local-dir: ./dist/apps/video-player-demo/browser/
        server-dir: ./
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    server: mintplayer.com
    username: ***
    password: ***
    local-dir: ./dist/apps/video-player-demo/browser/
    server-dir: ./
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
No file exists on the server "./.ftp-deploy-sync-state.json" - this must be your first publish! 🎉
The first publish will take a while... but once the initial sync is done only differences are published!
If you get this message and its NOT your first publish, something is wrong.
----------------------------------------------------------------
Local Files:	4[2](https://github.com/MintPlayer/mintplayer-ng-video-player/actions/runs/8771259338/job/24068787927#step:58:2)
Server Files:	0
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
📁 Create: assets
📁 Create: fonts
📄 Upload: assets/A-Sky-Full-of-Stars.mp[3](https://github.com/MintPlayer/mintplayer-ng-video-player/actions/runs/8771259338/job/24068787927#step:58:3)
📄 Upload: assets/github.svg
📄 Upload: assets/Jim_Yosef_Firefly_pt_II.mp3
📄 Upload: assets/Modern-iMovie-8ot-eJxH2yc.mp[4](https://github.com/MintPlayer/mintplayer-ng-video-player/actions/runs/8771259338/job/24068787927#step:58:4)
📄 Upload: chunk-2O4COJJ7.js
📄 Upload: chunk-2QLEXCGC.js
📄 Upload: chunk-3QZCMXY4.js
📄 Upload: chunk-4[5](https://github.com/MintPlayer/mintplayer-ng-video-player/actions/runs/8771259338/job/24068787927#step:58:5)KMOJ5O.js
📄 Upload: chunk-4A[6](https://github.com/MintPlayer/mintplayer-ng-video-player/actions/runs/8771259338/job/24068787927#step:58:6)GE3J5.js
📄 Upload: chunk-5BXZWKIF.js
📄 Upload: chunk-5C2M3AH5.js
📄 Upload: chunk-[7](https://github.com/MintPlayer/mintplayer-ng-video-player/actions/runs/8771259338/job/24068787927#step:58:7)YV37YHO.js
📄 Upload: chunk-ADMQDPYG.js
📄 Upload: chunk-AJ6EV7ZZ.js
📄 Upload: chunk-EVNI7ONN.js
📄 Upload: chunk-FTISO72U.js
📄 Upload: chunk-FXDQ5OYD.js
📄 Upload: chunk-FZ7D5DS6.js
📄 Upload: chunk-GEBHT6IQ.js
📄 Upload: chunk-GMCEDK2I.js
📄 Upload: chunk-I3VFUSN4.js
📄 Upload: chunk-ITCV3WOU.js
📄 Upload: chunk-JYLTQLDQ.js
📄 Upload: chunk-LSOHEN47.js
📄 Upload: chunk-LT3YEHIL.js
📄 Upload: chunk-P2VZOJAX.js
📄 Upload: chunk-PYKZEVEZ.js
📄 Upload: chunk-QNRDKPZT.js
📄 Upload: chunk-R6L36YQ3.js
📄 Upload: chunk-UJEUUZ55.js
📄 Upload: chunk-VBDOM5JA.js
📄 Upload: chunk-WZ55B5IY.js
📄 Upload: chunk-ZHKQ22YC.js
📄 Upload: favicon.ico
📄 Upload: fonts/bootstrap-icons.woff
📄 Upload: fonts/bootstrap-icons.woff2
📄 Upload: index.html
📄 Upload: main-YWQSPBJN.js
📄 Upload: polyfills-XTOFW74M.js
📄 Upload: styles-FGCNNYTD.css
----------------------------------------------------------------
Making changes to 42 files/folders to sync server state
Uploading: 22.3 MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder "assets/"
creating folder "fonts/"
uploading "assets/A-Sky-Full-of-Stars.mp3"
uploading "assets/github.svg"
uploading "assets/Jim_Yosef_Firefly_pt_II.mp3"
uploading "assets/Modern-iMovie-[8](https://github.com/MintPlayer/mintplayer-ng-video-player/actions/runs/8771259338/job/24068787927#step:58:9)ot-eJxH2yc.mp4"
uploading "chunk-2O4COJJ7.js"
uploading "chunk-2QLEXCGC.js"
uploading "chunk-3QZCMXY4.js"
uploading "chunk-45KMOJ5O.js"
uploading "chunk-4A6GE3J5.js"
uploading "chunk-5BXZWKIF.js"
uploading "chunk-5C2M3AH5.js"
uploading "chunk-7YV37YHO.js"
uploading "chunk-ADMQDPYG.js"
uploading "chunk-AJ6EV7ZZ.js"
uploading "chunk-EVNI7ONN.js"
uploading "chunk-FTISO72U.js"
uploading "chunk-FXDQ5OYD.js"
uploading "chunk-FZ7D5DS6.js"
uploading "chunk-GEBHT6IQ.js"
uploading "chunk-GMCEDK2I.js"
uploading "chunk-I3VFUSN4.js"
uploading "chunk-ITCV3WOU.js"
uploading "chunk-JYLTQLDQ.js"
uploading "chunk-LSOHEN47.js"
uploading "chunk-LT3YEHIL.js"
uploading "chunk-P2VZOJAX.js"
uploading "chunk-PYKZEVEZ.js"
uploading "chunk-QNRDKPZT.js"
uploading "chunk-R6L36YQ3.js"
uploading "chunk-UJEUUZ55.js"
uploading "chunk-VBDOM5JA.js"
uploading "chunk-WZ55B5IY.js"
uploading "chunk-ZHKQ22YC.js"
uploading "favicon.ico"
uploading "fonts/bootstrap-icons.woff"
uploading "fonts/bootstrap-icons.woff2"
uploading "index.html"
uploading "main-YWQSPBJN.js"
uploading "polyfills-XTOFW74M.js"
uploading "styles-FGCNNYTD.css"
----------------------------------------------------------------
🎉 Sync complete. Saving current server state to "./.ftp-deploy-sync-state.json"
----------------------------------------------------------------
Time spent hashing: 63 milliseconds
Time spent connecting to server: 1.5 seconds
Time spent deploying: 35.1 seconds (635 kB/second)
  - changing dirs: [9](https://github.com/MintPlayer/mintplayer-ng-video-player/actions/runs/8771259338/job/24068787927#step:58:10)29 milliseconds
  - logging: 12 milliseconds
----------------------------------------------------------------
Total time: 37.5 seconds
----------------------------------------------------------------
```
