### ISSUE TITLE
Help using regex

### ISSUE THREAD

**Issue by AB6162** [SamKirkland/FTP-Deploy-Action#465]
**Question/Support**
Hi, I am needing to exclude name.js files from uploading and only upload name-min.js files. I have tried with the following configuration  including the expression **/(.*)[^\-min]\.js/m** but I get error: 

```
on:
  push:
    branches:
      - develop
name: Deploy on develop branch
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Push files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: xxx
        username: xxxx
        password: ${{ secrets.xxxxx }}
        server-dir: public_html/
        exclude: |
          **/.github/**
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/test/**
          test/**
          **/public/static/js/admin//(.*)[^\-min]\.js/m
```

Is there any way to use a regex expression or could someone tell me where I am wrong?

Thanks!!
