### ISSUE TITLE
Folder for the state file (sync-state.json) doesn't get created with "state-name" 

### ISSUE THREAD

**Issue by Micha-2409** [SamKirkland/FTP-Deploy-Action#468]
**Request (Bug Description)**
I am trying to use the setting "state-name" to save the sync-state-file in a certain folder, which is not existent at the initial push.
Is there a possibility to "create" that folder 'on the fly' if not already existent (like it is done for "server-dir") ? 

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🔵 Web-Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 💾 Upload files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        protocol: ftps
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: ${{ secrets.FTP_SERVERDIR }}
        
        state-name: .deployment/.deploy-ftp-sync-state.json
        #state-name: deployment/.deploy-ftp-sync-state.json   ## same error
        #state-name: /.deployment/.deploy-ftp-sync-state.json   ## same error
        #state-name: ./.deployment/.deploy-ftp-sync-state.json   ## same error
        
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          ./README.md
        log-level: verbose
        #dangerous-clean-slate: true
        #dry-run: true
```

**My Action Log**
```
   Error: ENOENT: no such file or directory, open './.deployment/.deploy-ftp-sync-state.json'
```

**Further Question From A Friend 😇**
Is there a way or an update about "excluding all files/folders, except certain ones" ?
I read the issues concerning this topic [201](https://github.com/SamKirkland/FTP-Deploy-Action/issues/201), [247](https://github.com/SamKirkland/FTP-Deploy-Action/issues/247), [292](https://github.com/SamKirkland/FTP-Deploy-Action/issues/292), [356](https://github.com/SamKirkland/FTP-Deploy-Action/issues/356) and [436](https://github.com/SamKirkland/FTP-Deploy-Action/issues/436) but couldn't find a clear answer (or a working scenario).

THANKS A LOT FOR YOUR GREAT WORK 🚀🚀🚀

**Comment by donnikitos** [comment]
A possible workaround might be to create the folder manually before the upload?
```
on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🔵 Web-Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: Create sync folder
      run: mkdir .deployment
    
    - name: 💾 Upload files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        protocol: ftps
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server-dir: ${{ secrets.FTP_SERVERDIR }}
        
        state-name: .deployment/.deploy-ftp-sync-state.json
        #state-name: deployment/.deploy-ftp-sync-state.json   ## same error
        #state-name: /.deployment/.deploy-ftp-sync-state.json   ## same error
        #state-name: ./.deployment/.deploy-ftp-sync-state.json   ## same error
        
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          ./README.md
        log-level: verbose
        #dangerous-clean-slate: true
        #dry-run: true
```
