### ISSUE TITLE
LFS not working

### ISSUE THREAD

**Issue by Robert01101101** [SamKirkland/FTP-Deploy-Action#482]
**Bug Description**
All deploys that include files tracked with LFS seem to fail, it appears to me like LFS is just not supported. If I'm not just doing something wrong here, but LFS isn't supported, it would be great if LFS support could be added, or adding documentation to clarify it's not supported.

**My Action Config**
```yaml
name: Deploy to Hostinger via FTPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Deploy files to Hostinger via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTINGER_FTPS_SERVER }}
          username: ${{ secrets.HOSTINGER_FTPS_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTPS_PASSWORD }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/_PreAssets/**
            **/scss/**
            **/subdomains/amae/**
            **/subdomains/harbingersofdeath/**
            **/subdomains/understandingClimateChange/**
            **/nopublicaccess/**
            **/backup/**
            **/encryptedDrive*
            **/prepros.config*
            **/_DATABASE_SETUP_*
            **/_TRANSLATION_SETUP_*
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@v4.3.5
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
Last published on 📅 Wednesday, October 9, 20[24](https://github.com/Robert01101101/Portfolio-RMichels/actions/runs/11302917104/job/31439412945#step:3:25) at 6:07 PM
----------------------------------------------------------------
Local Files:	444
Server Files:	440
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
📁 Create: subdomains/tourguide/img
📄 Upload: subdomains/tourguide/img/mockup.png
📄 Upload: subdomains/tourguide/img/stephan-valentin-rwFQP0L2Xl4-unsplash-sml-crp.png
📄 Upload: subdomains/tourguide/img/stephan-valentin-rwFQP0L2Xl4-unsplash-sml.jpg
🔁 File replace: subdomains/tourguide/css/main.css
🔁 File replace: subdomains/tourguide/index.php
⚖️  File content is the same, doing nothing (a bunch of files...)
----------------------------------------------------------------
Making changes to 6 files/folders to sync server state
Uploading: 393 B -- Deleting: 0 B -- Replacing: 6.36 kB
----------------------------------------------------------------
creating folder "subdomains/tourguide/img/"
uploading "subdomains/tourguide/img/mockup.png"
uploading "subdomains/tourguide/img/stephan-valentin-rwFQP0L2Xl4-unsplash-sml-crp.png"
uploading "subdomains/tourguide/img/stephan-valentin-rwFQP0L2Xl4-unsplash-sml.jpg"
replacing "subdomains/tourguide/css/main.css"
replacing "subdomains/tourguide/index.php"
----------------------------------------------------------------
🎉 Sync complete. Saving current server state to "./.ftp-deploy-sync-state.json"
----------------------------------------------------------------
Time spent hashing: 204 milliseconds
Time spent connecting to server: 453 milliseconds
Time spent deploying: 699 milliseconds (9.66 kB/second)
  - changing dirs: 163 milliseconds
  - logging: 17 milliseconds
----------------------------------------------------------------
Total time: 1.6 seconds
----------------------------------------------------------------
```
