### ISSUE TITLE
Push latest commit

### ISSUE THREAD

**Issue by peterrentz** [SamKirkland/FTP-Deploy-Action#484]
**Bug Description**
Is there a way to push only the files that were changed in the commit that triggered the action?
(Action works great otherwise, thanks!)

**My Action Config**
```yaml
on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Push files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ****
        username: ****
        password: ****
        server-dir: ****
        protocol: ftp
        port: 21
```

**My Action Log**
```
   # Paste Log here
   # you may want enable verbose logging with   log-level: verbose
```
