### ISSUE TITLE
550 The system cannot find the path specified

### ISSUE THREAD

**Issue by sebastiandammark** [SamKirkland/FTP-Deploy-Action#487]
**Bug Description**
When uploading, the action is trying to access a folder that doesn't exist.
In line 82-85 of the log I can see that it creates 4 folder under `uSync/V9` but when I publish it locally there are 11 folders under `uSync/V9`.
There are also 11 folders on GitHub.

So when it fails with the `550 The system cannot find the path specified` I can understand why, since the folders doesn't exists.
But why doesn't it create the missing folders ?

If I create the folders manually, it's all smooth sailing :) 

**My Action Config**
```yaml
name: Build, publish and deploy project to Curanet

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    working-directory: './something.Web/src/projectfolder'

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.302'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish 'projectfile.csproj' --configuration Release --output '${{env.DOTNET_ROOT}}/build' --runtime win-x64 --self-contained true -p:PublishTrimmed=false -p:PublishSingleFile=false

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: '${{env.DOTNET_ROOT}}/build/'
          server-dir: 'www/'
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
```

**My Action Log**
I've attached the log as a file since it's too long.

[action_log.txt](https://github.com/user-attachments/files/17816567/action_log.txt)
