### ISSUE TITLE
Exclude option not working when i deploy  on my FTP

### ISSUE THREAD

**Issue by OlivPi** [SamKirkland/FTP-Deploy-Action#488]
**Bug Description**
I have to configure my file with some folder and file to exclude during my deploy. But there are no effect. I have toi test a lot of options but nothing happen...

**My Action Config**
```yaml
name: Deploy to O2Switch via FTP

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    name: Deploy to O2Switch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, zip, opcache

      - name: Install Composer dependencies
        working-directory: ./bedrock
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js and build assets
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          yarn install
          yarn build:production
        working-directory: ./bedrock/web/app/themes/outa-theme

      - name: Validate deployment files
        run: ls -R ./bedrock/

      - name: Deploy to O2Switch
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./bedrock/
          log-level: verbose
          dry-run: true
          exclude: |
            **/vendor/**
            **/*.log
            **/.env
            **/*.lock
            **/.DS_Store
            **/.idea/
            **/.git*
            **/.git*/**
            **/node_modules/**
```

**My Action Log**
```
Creating local state at ./.ftp-deploy-sync-state.json
Local state created
Connected to 109.234.162.158:21 (No encryption)
< [22](https://github.com/OlivPi/hotel-outa/actions/runs/11976778450/job/33393202498#step:8:22)0---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 250 allowed.
220-Local time is now 17:55. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
> OPTS UTF8 ON
< 504 Unknown command
Login security: No encryption
> USER ***
< 331 User *** OK. Password required
> PASS ###
< [23](https://github.com/OlivPi/hotel-outa/actions/runs/11976778450/job/33393202498#step:8:23)0-Your bandwidth usage is restricted
230 OK. Current restricted directory is /
> FEAT
< 211-Extensions supported:
 UTF8
 EPRT
 IDLE
 MDTM
 SIZE
 MFMT
 REST STREAM
 MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
 MLSD
 PRET
 AUTH TLS
 PBSZ
 PROT
 TVFS
 ESTA
 PASV
 EPSV
 ESTP
211 End.
> TYPE I
< 200 TYPE is now 8-bit binary
> STRU F
< 200 F OK
> OPTS UTF8 ON
< 504 Unknown command
> OPTS MLST type;size;modify;unique;unix.mode;unix.owner;unix.group;unix.ownername;unix.groupname;
< 200  MLST OPTS type;size;sizd;modify;UNIX.mode;UNIX.uid;UNIX.gid;unique;
  changing dir to ./
> MKD .
< 550 Can't create directory: File exists
> CWD .
📁 Create: bedrock/vendor/guzzlehttp/guzzle/src/Exception
📁 Create: bedrock/vendor/guzzlehttp/guzzle/src/Handler
📁 Create: bedrock/vendor/guzzlehttp/promises
📁 Create: bedrock/vendor/guzzlehttp/promises/src
📁 Create: bedrock/vendor/guzzlehttp/psr7
📁 Create: bedrock/vendor/guzzlehttp/psr7/src
📁 Create: bedrock/vendor/guzzlehttp/psr7/src/Exception
📁 Create: bedrock/vendor/guzzlehttp/uri-template
📁 Create: bedrock/vendor/guzzlehttp/uri-template/src
📁 Create: bedrock/vendor/illuminate
📁 Create: bedrock/vendor/illuminate/bus
📁 Create: bedrock/vendor/illuminate/bus/Events
📁 Create: bedrock/vendor/illuminate/cache
📁 Create: bedrock/vendor/illuminate/cache/Console
📁 Create: bedrock/vendor/illuminate/cache/Console/stubs
📁 Create: bedrock/vendor/illuminate/cache/Events
📁 Create: bedrock/vendor/illuminate/cache/RateLimiting
📁 Create: bedrock/vendor/illuminate/collections
📁 Create: bedrock/vendor/illuminate/collections/Traits
📁 Create: bedrock/vendor/illuminate/conditionable
📁 Create: bedrock/vendor/illuminate/conditionable/Traits
📁 Create: bedrock/vendor/illuminate/config
📁 Create: bedrock/vendor/illuminate/console
📁 Create: bedrock/vendor/illuminate/console/Concerns
📁 Create: bedrock/vendor/illuminate/console/Contracts
📁 Create: bedrock/vendor/illuminate/console/Events
📁 Create: bedrock/vendor/illuminate/console/resources
📁 Create: bedrock/vendor/illuminate/console/resources/views
📁 Create: bedrock/vendor/illuminate/console/resources/views/components

...
```
Thank a lot for your help
