### ISSUE TITLE
Dirty repository when uploading build product

### ISSUE THREAD

**Issue by jb-roa** [SamKirkland/FTP-Deploy-Action#49]
**Bug Description**
I'm experiencing the error _**fatal: Dirty repository: Having uncommitted changes. Exiting...**_ when trying to upload my build product to an FTP server. The build is an Angular build using webpack. 

The upload worked _**once**_ and now I cannot make it work again. Not even with the exact same commit. 

**My Action Config**
```yaml
name: Deploy app

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
              with:
                  fetch-depth: 2

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --prod

            - name: 'Deploy to website'
              uses: SamKirkland/FTP-Deploy-Action@3.0.0
              with:
                  ftp-server: ${{ secrets.FTP_SERVER }}
                  ftp-username: ${{ secrets.FTP_USER }}
                  ftp-password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: dist/
```

**My Action Log**
```
   git ftp push --force --auto-init --verbose --syncroot dist/ --user [REMOVED] --passwd *** ftp://[REMOVED]/public_html
  Thu Mar 19 08:10:52 UTC 2020: git-ftp version 1.5.1 running on Linux 3c5c2018866a 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 GNU/Linux
  Thu Mar 19 08:10:52 UTC 2020: Forced mode enabled.
  Thu Mar 19 08:10:52 UTC 2020: Auto init if needed.
  Thu Mar 19 08:10:52 UTC 2020: Using syncroot dist/ if exists.
  Thu Mar 19 08:10:52 UTC 2020: fatal: Dirty repository: Having uncommitted changes. Exiting...
```
