### ISSUE TITLE
Next Js In Cpanel Error: FTPError: 553 Can't open that file: No such file or directory

### ISSUE THREAD

**Issue by Kitsuzune** [SamKirkland/FTP-Deploy-Action#490]
**Bug Description**
Im not able to deploy my website code built with NextJS 15.1.1-canary.2.
I always get the error 553 Can't open that file: No such file or directory
Im not sure, is the problem my hosting or not

Thanks for your help!

**My Action Config**

```
on:
  push:
    branches: 
      - main
name: Auto Deploy V1


jobs:
  web-deploy:
    name: AK Deploy V1
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build Project
      run: |
        npm install
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.GIT_CPANEL_NEXT_FE_SERVER }}
        username: ${{ secrets.GIT_CPANEL_NEXT_FE_USERNAME }}
        password: ${{ secrets.GIT_CPANEL_NEXT_FE_PASSWORD }}
        protocol: ftp
        port: ${{ secrets.GIT_CPANEL_NEXT_FE_PORT }}
        local-dir: ./
        server-dir: ./
```

**My Action Log**
```

----------------------------------------------------------------
Making changes to 66 files/folders to sync server state
Uploading: 1.13 kB -- Deleting: 1.13 kB -- Replacing: 590 MB
----------------------------------------------------------------
creating folder ".next/static/UMpyyJ8YUcLQyaBtgp8h0/"
uploading ".next/static/UMpyyJ8YUcLQyaBtgp8h0/_buildManifest.js"
uploading ".next/static/UMpyyJ8YUcLQyaBtgp8h0/_ssgManifest.js"
replacing ".next/app-build-manifest.json"
replacing ".next/app-path-routes-manifest.json"
replacing ".next/BUILD_ID"
replacing ".next/build-manifest.json"
replacing ".next/cache/.rscinfo"
replacing ".next/cache/config.json"
replacing ".next/cache/webpack/client-production/0.pack"
replacing ".next/cache/webpack/client-production/index.pack"
replacing ".next/cache/webpack/edge-server-production/index.pack"
replacing ".next/cache/webpack/server-production/0.pack"
replacing ".next/cache/webpack/server-production/index.pack"
replacing ".next/next-minimal-server.js.nft.json"
replacing ".next/next-server.js.nft.json"
replacing ".next/prerender-manifest.json"
replacing ".next/server/app-paths-manifest.json"
replacing ".next/server/app/_not-found.html"
replacing ".next/server/app/_not-found.rsc"
replacing ".next/server/app/_not-found/page_client-reference-manifest.js"
replacing ".next/server/app/(webIndex)/about-us/detail/page_client-reference-manifest.js"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 553 Can't open that file: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5263:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5107:44)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:[390](https://github.com/Kitsuzune/awanKusume-fe/actions/runs/12312877937/job/34365969222#step:5:391):5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
  code: 553
}
Error: FTPError: 553 Can't open that file: No such file or directory


```

appreciate for your help
i see all the issue it have is solved with laravel but i dont see any Js so i am writing this to get some information
