### ISSUE TITLE
Can't store server name in secrets

### ISSUE THREAD

**Issue by OmarioHassan** [SamKirkland/FTP-Deploy-Action#491]
**Bug Description**
Storing user name and password in secrets very well but not for server name.

**My Action Config**
```yaml
name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main # Replace with your deployment branch if different

jobs:
  build_and_deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version compatible with your project

      # Install dependencies and build the React app
      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      # Deploy built files to SmarterASP.NET using FTP
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: something.site4now.net # Replace with your FTP server
          username: "${{ secrets.FTP_USERNAME }}" # Replace with your FTP username
          password: "${{ secrets.FTP_PASSWORD }}" # Replace with your FTP password
          local-dir: dist/ # React production build folder
          server-dir: / # Target directory on the server (adjust as needed)
```

**My Action Log**
```
   # Paste Log here
   # you may want enable verbose logging with   log-level: verbose
![image](https://github.com/user-attachments/assets/c101efb6-4337-4f67-8dd7-64cd71f80603)

```
