### ISSUE TITLE
Secret not being used: FTP_PASSWORD is not recognized (Login Failed)

### ISSUE THREAD

**Issue by jadchahine111** [SamKirkland/FTP-Deploy-Action#492]
I'm having trouble with the FTP-Deploy-Action. The workflow doesn't appear to be using the `FTP_PASSWORD` secret correctly. When I add a debugging step to check if the secret exists, it confirms availability, but the deployment fails with a `LOGIN FAILED` error.  

I tested by hardcoding the FTP password directly into the workflow file, and it worked as expected. However, when using GitHub Secrets, the authentication fails.

What I did:
1. Add the `FTP_PASSWORD` secret in the repository settings.  
2. Use it in the workflow as `${{ secrets.FTP_PASSWORD }}`.  
3. Push a commit to trigger the workflow.  
4. Observe the workflow logs.  
5. Got the error

**Workflow YAML:**  
```
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.api.jadchahine.me
        username: u812263148.jadchahine
        password: ${{ secrets.FTP_PASSWORD }}
```

**Comment by geppyz** [comment]
Does it work if you add read permissions to your job? Otherwise it might not be able to read the secret, hence it not working.

```YAML
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: xxx
        username: xxx
        password: ${{ secrets.FTP_PASSWORD }}
```
