### ISSUE TITLE
i removed it from local and the file is exists on server  -- File not found or you don't have access to the file - skipping...

### ISSUE THREAD

**Issue by ahmedbondok2019** [SamKirkland/FTP-Deploy-Action#493]
**Bug Description**
i removed it from local and the file is exists on server

**My Action Config**
```yaml
on:
  push:
    branches: [main]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
```

**My Action Log**
```
  File not found or you don't have access to the file - skipping...
removing folder "/app/Http/Livewire"
-------------- 🔥🔥🔥 an error occurred 🔥🔥🔥 --------------
---------------------- full error below ----------------------
FTPError: 550 /app/Http/Livewire: No such file or directory
at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5252:39)
at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5096:44)
at Socket.emit (node:events:519:28)
at addChunk (node:internal/streams/readable:559:12)
at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
at Readable.push (node:internal/streams/readable:390:5)
at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
code: 550
}
Error: FTPError: 550 /app/Http/Livewire: No such file or directory
```
