### ISSUE TITLE
Attempting to Remove Non-Existent Folder "/***/ _actions"

### ISSUE THREAD

**Issue by wlmccrae** [SamKirkland/FTP-Deploy-Action#496]
**Bug Description**
Running FTP-Deploy-Action successfully uploads the files via FTP, but then returns an error when it attempts to delete "/***/_actions".

**My Action Config**
```
name: Deploy Portfolio

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Super-linter
      uses: super-linter/super-linter@v7.2.1

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        local-dir: ./
        server-dir: wandamccrae.com/
        exclude: |
          **/.git*
          **/.git*/**
          .DS_Store

```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ***
    username: ***
    password: ***
    protocol: ftp
    local-dir: ./
    server-dir: ***/
    exclude: **/.git*
  **/.git*/**
  .DS_Store
  
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
Last published on 📅 Friday, October 18, 2024 at 5:35 AM
----------------------------------------------------------------
Local Files:	9
Server Files:	159
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
📁 Create: media
📄 Upload: index.css
📄 Upload: index.html
📄 Upload: media/headline-editor.png
📄 Upload: media/mod3project.png
📄 Upload: media/random-user.png
📄 Upload: media/simple-weather.png
📄 Upload: media/wanda-mccrae-resume.pdf
📄 Upload: media/wandamccrae.jpg
📁 Delete: _actions    
📁 Delete: _PipelineMapping    
📁 Delete: _temp    
📁 Delete: html-css-portfolio    
----------------------------------------------------------------
Making changes to 13 files/folders to sync server state
Uploading: 4.01 MB -- Deleting: 7.68 MB -- Replacing: 0 B
----------------------------------------------------------------
creating folder "media/"
uploading "index.css"
uploading "index.html"
uploading "media/headline-editor.png"
uploading "media/mod3project.png"
uploading "media/random-user.png"
uploading "media/simple-weather.png"
uploading "media/wanda-mccrae-resume.pdf"
uploading "media/wandamccrae.jpg"
removing folder "/***/_actions"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 /***/_actions: No such file or directory.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5263:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5107:44)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
  code: 550
}
Error: FTPError: 550 /***/_actions: No such file or directory.
```
