### ISSUE TITLE
Issue with Kirby CMS files

### ISSUE THREAD

**Issue by NahuelGerthVK** [SamKirkland/FTP-Deploy-Action#498]
**Bug Description**
When I push my website (Kirby CMS) it stops. Could it be related to the amount of files? I already tried giving it more time. Hosting server is all-inkl.com. I also tried uploading the large folders manually but the actions till crashed afterwards.

Edit: I noted it always stops on the same file:
```yaml
uploading "site/accounts/index.html"
```

Amount of files: 810
Total size: ca. 250mb

**My Action Config**
```yaml
name: 🚀 Push to FTP

# when to run the action
on:
  push:
    branches: [main]

# what it does
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: 📂 FTP Deployment
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: xyz
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          # our subdirectory on the live server
          server-dir: /live-deploy/
          timeout: 600000  # 10 minutes (600,000 ms)
          log-level: verbose
```

**My Action Log**
```
  file uploaded
uploading "site/accounts/index.html"
> EPSV
< 229 Entering Extended Passive Mode (|||50367|)

> STOR site/accounts/index.html
< 150 Opening BINARY mode data connection for site/accounts/index.html

Uploading to 85.13.164.218:50367 (TLSv1.3)
upload progress for "site/accounts/index.html". Progress: 0 bytes of 20275677 bytes
upload progress for "site/accounts/index.html". Progress: 0 bytes of 20275677 bytes
> QUIT

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

[Error: 80ACB195447F0000:error:0A00041A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 50
 (data socket)] {
  library: 'SSL routines',
  reason: 'tlsv1 alert decode error',
  code: 'ERR_SSL_TLSV1_ALERT_DECODE_ERROR'
}
Error: Error: 80ACB195447F0000:error:0A00041A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 50
 (data socket)
```
