### ISSUE TITLE
Can not find build directory.

### ISSUE THREAD

**Issue by bledar** [SamKirkland/FTP-Deploy-Action#5]
I am trying to make a react app build and deploy with FTP to another server.
The connection is working correctly with server but the build directory can not be found.
I have create a LOCAL_DIR secret variable but not working.
My _deploy.yml_ file looks like this:
```yml on: push
name: Build and Publish Website
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Project setup
      run: npm install
    - name: Compile javascript
      run: npm run build
    - name: List files
      run: ls -al
    - name: Location
      run: pwd
    - name : FTP-Deploy
      uses: SamKirkland/FTP-Deploy-Action@master
      env: 
        FTP_SERVER :  ${{ secrets.FTP_SERVER }}
        FTP_PASSWORD :  ${{ secrets.FTP_PASSWORD }}
        FTP_USERNAME :  ${{ secrets.FTP_USERNAME }}
        LOCAL_DIR : ${{ secrets.LOCAL_DIR }}
```

LOCAL_DIR secret value is: `/build`
