### ISSUE TITLE
Secret ftp-password name is invalid

### ISSUE THREAD

**Issue by mattwells19** [SamKirkland/FTP-Deploy-Action#50]
**Bug Description**
Cannot upload using SFTP because the yaml script requires a Secret named 'ftp-password' and Github will not let me add a Secret named 'ftp-password' as it is an invalid name.

**My Action Config**
```yaml
on: push
name: Publish Website over SFTP
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://webpages.uncc.edu:22/
        ftp-username: mwells21
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
```

**My Action Log**
```
(node:1) UnhandledPromiseRejectionWarning: Error: Input required and not supplied: ftp-password
```
![image](https://user-images.githubusercontent.com/36650048/77194942-39d45e80-6ab7-11ea-97c5-c559f67ed576.png)
