### ISSUE TITLE
Error: Missing download info for SamKirkland/FTP-Deploy-Action@4.3.5

### ISSUE THREAD

**Issue by mikeda37** [SamKirkland/FTP-Deploy-Action#502]
**Bug Description**
I got the error as the title.  This is the first time to use GitHub Actions for me.  
Any help would be appreciated!

**My Action Config**
```yaml
name: ftp upload
on:
  push:
    branches:
      - dev
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /www/dir-name/
```

**My Action Log**
```
Current runner version: '2.323.0'
Operating System
  Ubuntu
  24.04.2
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20250413.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250413.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250413.1
Runner Image Provisioner
  2.0.422.1
GITHUB_TOKEN Permissions
  Contents: read
  Metadata: read
  Packages: read
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download immutable action package 'actions/checkout@v4'
  Version: 4.2.2
  Digest: sha256:ccb2698953eaebd21c7bf6268a94f9c26518a7e38e27e0b83c1fe1ad049819b1
  Source commit SHA: 11bd71901bbe5b1630ceea73d27597364c9af683
Error: Missing download info for SamKirkland/FTP-Deploy-Action@4.3.5
```
