### ISSUE TITLE
ECONNREFUSED after long running job

### ISSUE THREAD

**Issue by LukeSavefrogs** [SamKirkland/FTP-Deploy-Action#503]
**Bug Description**

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          extensions: ${{ env.php_extensions }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          fail-fast: true

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

      - name: FTP Deploy (vendor)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftp
          server: ${{ secrets.FTP_SERVER_TEST }}
          username: ${{ secrets.FTP_USERNAME_TEST }}
          password: ${{ secrets.FTP_PASSWORD_TEST }}
          local-dir: ./vendor/
          server-dir: ./vendor/
          state-name: ../.ftp-deploy-sync-state__vendor.json
          log-level: minimal
```

**My Action Log**
```
| uploading "nesbot/carbon/src/Carbon/Lang/unm_US.php"
| uploading "nesbot/carbon/src/Carbon/Lang/unm.php"
| uploading "nesbot/carbon/src/Carbon/Lang/ur_IN.php"
| uploading "nesbot/carbon/src/Carbon/Lang/ur_PK.php"
|
| ----------------------------------------------------------------
| --------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
| ----------------------------------------------------------------
|
| ----------------------------------------------------------------
| ----------------------  full error below  ----------------------
| ----------------------------------------------------------------
|
| Error: connect ECONNREFUSED 148.251.51.73:3306
|     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
|   errno: -111,
|   code: 'ECONNREFUSED',
|   syscall: 'connect',
|   address: '148.251.51.73',
|   port: 3306
| }
```
