### ISSUE TITLE
Issue while deployment

### ISSUE THREAD

**Issue by vipuljain28** [SamKirkland/FTP-Deploy-Action#505]
**Bug Description**
It was running perfectly some time back, but now it is givingan  error in the sync process.

**My Action Config**
```yaml
# This is a basic workflow to help you get started with Actions
 
name: CI Development
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

 
      # Runs a set of commands using the runners shell
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST_TEST }}
          username: ${{ secrets.FTP_USERNAME_TEST }}
          password: ${{ secrets.FTP_PASSWORD_TEST }}
          server-dir: ${{ secrets.FTP_SERVER_DIRECTORY_TEST }}
          exclude: |
            **/calibrationdata/**
            **/uploads/**
            **/nbproject/**
            **/vendor/**
            **/calibrationdata/**
            **/composer.lock*
            **/.git/**
            **/conn.php*
            **/viewPublicCertificate.php*
    # !!!!!!! TODO Fill Out !!!!!!!
```

**My Action Log**
```
  
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 553 Can't open that file: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5263:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5107:44)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
  code: 553
}
Error: FTPError: 553 Can't open that file: No such file or directory
```
