### ISSUE TITLE
How to use --key

### ISSUE THREAD

**Issue by Aeris1One** [SamKirkland/FTP-Deploy-Action#51]
How to use --key to connect to a SSH server without using password ? It seems that we have to provide a SSH key **file name**, does that means to upload the SSH key on the repo ? Is it possible to save SSH key on Secrets ?

**Comment by SamKirkland** [comment]
I haven't tested/documented the usage of `--key` yet.
You have the right idea. If we store the SSH private key inside a secrets we can create a file at run-time and pass that into the action.

**Note: The following config is untested**
```yaml
  
on: push
name: Build and Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Create SSH deploy key
      run: echo ${{ secrets.SSH_KEY }} >> "$HOME/.ssh/ftp_publish_key"
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://ftp.samkirkland.com/
        ftp-username: react-deploy-example@ftp-deploy-action-example-react.samkirkland.com
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        git-ftp-args: --key "$HOME/.ssh/ftp_publish_key"
```

Please report back with your results, I'd love to add this to the documentation. One note is ftp-password will no longer be required, but I haven't accounted for that in the action so you'll have to pass in filler data until I change that to optional.
