### ISSUE TITLE
Make auto-init optional

### ISSUE THREAD

**Issue by radeksimko** [SamKirkland/FTP-Deploy-Action#56]
While `--auto-init` flag can be useful given the lack of integrity guarantees in FTP, it can also be burden for bigger projects as re-uploading everything for every deploy can take a lot of time.

Also `git-ftp` stores the latest git SHA on the server to keep track of files which were/weren't uploaded - so re-uploading the whole hierarchy seems to be defeating the purpose of using that tool (as opposed to some generic FTP client).

Is there any chance of making the auto-init optional?

**Comment by SamKirkland** [comment]
Hey Radek!

In my testing I only see diffs uploading, it looks like [that's the intention of auto-init](https://github.com/git-ftp/git-ftp/pull/331/files).
Have you been able to recreate this issue after the initial deployment? If so can you please copy your deployment config here and I can take a look. I have seen similar issues when using `.git-ftp-include`


Thanks!

**Comment by radeksimko** [comment]
Hey Sam,
Good question. I just looked into the log and I can see this on closer inspection:

```
Sun Mar 29 10:11:29 UTC 2020: Retrieving last commit from ftp://***:***@***/xyz/.
  #=#=#                                                                         
  ##O#- #                                                                       
  ##O=#  #                                                                      
  #=#=-#  #                                                                     
  -#O#- #   #                                                                   
  -=#=#   #   #                                                                 
  
  ######################################################################## 100.0%
  Sun Mar 29 10:11:31 UTC 2020: Unknown SHA1 object, could not determine changed files, taking all files.
```
I'm unsure what "Unknown SHA1 object" means, but it's 100% reproducible for me and it does behave the way I described - probably as a result of this error.

**Comment by vaibhavar** [comment]
I'm facing this issue too.
I tried running `git diff  --diff-filter "AM" --name-only --no-renames  -z <sha from remote server>` locally and it does detect the changed files correctly.
Not sure why it's not able to do the same while running in Github actions. 🤔

**Comment by cmc-git** [comment]
I'm having a similar problem where all files are being uploaded from the /public directory in a Hugo build. I'm not sure if this is the same issue as above, but you mention above this problem happening when using `.git-ftp-include`

My `.git-ftp-include` file just has the line:
`!public/`

The deploy code is as follows
```
steps:
    - name: git checkout
      uses: actions/checkout@v2
      # use last two commits to determine diffs
      with: 
        fetch-depth: 2

    # initialise hugo
    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.58.3'
        extended: true
    
    # build hugo
    - name: build hugo
      run: hugo
    
    # ftp site  
    - name: deploy to nicemachine
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public/
```
When running the job, the following output happens:

```
Sat May 23 08:57:53 UTC 2020: Syncroot is 'public/'.
  Sat May 23 08:57:53 UTC 2020: The remote sha1 is saved in file '.git-ftp.log'.
  Sat May 23 08:57:53 UTC 2020: Check if curl is functional.
  Sat May 23 08:57:53 UTC 2020: Retrieving last commit from ftp://***:***@ftp.x.y/z/.
  #=#=#
  ############### 100.0%
  Sat May 23 08:57:56 UTC 2020: No changed files, but different commit ID. Changed files ignored or commit amended.
  Sat May 23 08:57:56 UTC 2020: Including all files in public/ for upload.
  Sat May 23 08:57:56 UTC 2020: Having files to sync.
  Sat May 23 08:57:56 UTC 2020: 106 files to sync:

``` 
All the files are transferred rather than just the diffs. Is this a limitation of using an folder that is not committed to github, or is there something else going wrong? 

(Apologies if this should be in a new issue thread but it seemed related).
