### ISSUE TITLE
local-dir default is not the same as specifying ./ explicitly

### ISSUE THREAD

**Issue by jorenbroekema** [SamKirkland/FTP-Deploy-Action#57]
**Bug Description**
When not setting local-dir, the default should be ./ 
https://github.com/SamKirkland/FTP-Deploy-Action/blob/master/src/main.ts#L27

However, I get different results from:
- Not specifying the local-dir arg
- Specifying it as `./`

When not specifying it, it will only upload main.yml to the server, so my suspicion is that the local dir is set to the .github/workflows folder, rather than the root of the repository.

**My Action Config**
```yaml
on:
  push:
    branches:
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: <ip>
        ftp-username: joren
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure --remote-root home/joren
```

**My Action Log**
```
  Sun Mar 29 22:13:47 UTC 2020: Having files to sync.
  Sun Mar 29 22:13:47 UTC 2020: 1 file to sync:
  Sun Mar 29 22:13:47 UTC 2020: [1 of 1] Buffered for upload '.github/workflows/main.yml'.
  Sun Mar 29 22:13:47 UTC 2020: Uploading ...
  #=#=#                                                                         
  ##O#- #                                                                       
  ##O=#  #                                                                      
  #=#=-#  #                                                                     
  -#O#- #   #                                                                   
  -=#=#   #   #                                                                 
  -=O#- #  #    #                                                               
  -=O=#  #   #   #                                                              
  -=O=-#  #    #   #                                                            
  -=O=- #   #   #     #                                                         
  
  ######################################################################## 100.0%
  Sun Mar 29 22:13:50 UTC 2020: Uploading commit log to sftp://joren:***@<ip>/home/joren/.git-ftp.log.
  #=#=#                                                                         
  ##O#- #                                                                       
  ##O=#  #                                                                      
  #=#=-#  #                                                                     
  -#O#- #   #                                                                   
  -=#=#   #   #                                                                 
  -=O#- #  #    #                                                               
  -=O=#  #   #   #                                                              
  -=O=-#  #    #   #                                                            
  Sun Mar 29 22:13:52 UTC 2020: Last deployment changed from 016dd33d406fb2cbe1b424190f989635f1f82925 to 1a208e77f30e594cbf2e86c5b670f73b7d33bb63.
✅ Deploy Complete
```

Setting local-dir explicitly to `./` works for me, uploads everything as I expected.
