### ISSUE TITLE
Looks like the URL server isn't reconize

### ISSUE THREAD

**Issue by alexis35115** [SamKirkland/FTP-Deploy-Action#61]
**Bug Description**
Looks like the URL server isn't reconize

**My Action Config**
  deploy:
    # le nom de la tâche affiché dans l'interface de Github
    name: 'Déploiement sur le serveur FTP du cégep'
    # S'exécute sur la dernière version d'Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Utilisation de la tâche pour pour obtenir la dernière version de la branche 'master' par défaut
      # Voici la documentation https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/ftp-deploy
      - uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          # Le port 21 est pour FTP
          ftp-server: ${{ secrets.FTP_SERVER }}
          # Utilisation d'une variable "secrète" pour l'identifiant
          ftp-username: ${{ secrets.FTP_LOGIN }}
          # Utilisation d'une variable "secrète" pour contenir le mot de passe (n'est pas le mot de passe du cégep)
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          # Spécifier le répertoire à déployer
          local-dir: src/
          git-ftp-args: --ssl --insecure --remote-root "Enseignants/Informatique/Alexis Garon-Michaud/Public/DemoGithub"
          # Prendre note que tout sera synchronisé à moins de fournir les deux dernières version pour faire la comparaison
          # Dois-je garder insecure?

**My Action Log**
/usr/bin/docker run --name c1a88daf09549dd40f794e08fdfc0802ba2_b5c42c --label 430c1a --workdir /github/workspace --rm -e INPUT_FTP-SERVER -e INPUT_FTP-USERNAME -e INPUT_FTP-PASSWORD -e INPUT_LOCAL-DIR -e INPUT_GIT-FTP-ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/demoGithubActions/demoGithubActions":"/github/workspace" 430c1a:88daf09549dd40f794e08fdfc0802ba2
Uploading files
  git ftp push --force --auto-init --verbose --syncroot src/ --user *** --passwd *** --ssl --insecure --remote-root Enseignants/Informatique/Alexis Garon-Michaud/Public/DemoGithub ***

**Comment by SamKirkland** [comment]
Is that your full action log? I don't see an error in the log file posted.

**Comment by alexis35115** [comment]
ftp://nt-enseignement.cgmatane.qc.ca

**Comment by SamKirkland** [comment]
Can you attach the full action log so I can see the error?

```yaml
on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: 'Déploiement sur le serveur FTP du cégep'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://nt-enseignement.cgmatane.qc.ca/Enseignants/Informatique/Alexis Garon-Michaud/Public/DemoGithub/
        ftp-username: ${{ secrets.FTP_LOGIN }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: src/
        git-ftp-args: --insecure
```

Please test out your ftp server, username, and password in a ftp client (FileZilla, CyberDuck, etc) and verify you can login successfully. You should be able to navigate to the path `Enseignants/Informatique/Alexis Garon-Michaud/Public/DemoGithub/` directly from your ftp servers default folder on login, if the path is not correct the upload will not work.
