### ISSUE TITLE
First time deploy is expensive - can we avoid that?

### ISSUE THREAD

**Issue by jesperordrup** [SamKirkland/FTP-Deploy-Action#62]
The first deploy takes a lot more time than the following. Example, it takes around 30 minutes in transfer time alone and typically that drops to seconds for the following deploys. 

We could save the initial expensive github action minutes if we could prep the destination with an intial upload by transferring manually using whatever ftp client for instance. 

Is it possible to run FTP-Deploy and not upload what is already deployed based on files already existing in deploy destination?

```
on: push
name: Publish Website to prod
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}

```

![image](https://user-images.githubusercontent.com/3120151/80081738-a1b51380-8553-11ea-9887-0a1078ac873e.png)

**Comment by jesperordrup** [comment]
https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md 

Omg - I guess that catchup is the solution. Havent tried but I assume this is the solution and close this for now.

**Comment by arpit-uno** [comment]
Hi,
Can you tell me how to specify/write the `catchup` option in the `.yml` file. I guess it should be under `with:` but what should be the value, a boolean `true` or the last commit SHA-1. for e.g:

```
with:
        server: myftpserver.xyz.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /domains/xyz.com/public_html/github-actions/
        catchup: true or 4543ssd2d2534332d221321325xzsa
```

Also, should a `.git-ftp-log` with the (last SHA-1) be already present on server, before the action is triggered/runs.

Any help is appreciated. 
Thanks
