### ISSUE TITLE
[FEATURE REQUEST]: Add an option to set private key from Secrets

### ISSUE THREAD

**Issue by edgarchinchilla** [SamKirkland/FTP-Deploy-Action#63]
**Bug Description**
This isn't a bug, but involves a security risk, right know to get SFPT working, you need to specify a privatekey file path in **git-ftp-args**. Uploading the privatekey file to use it for the Action is dangerous.

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  # https://github.com/SamKirkland/FTP-Deploy-Action
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://${{ secrets.FTP_HOSTNAME }}/
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        git-ftp-args: --key ./utils/do_rsa --insecure --all
```

**My Action Log**
```
   # Paste Log here
```

This less popular action does the job:
>[sftp-deploy](https://github.com/marketplace/actions/sftp-deploy)
