### ISSUE TITLE
fatal: Dirty repository: Having uncommitted changes. Exiting...

### ISSUE THREAD

**Issue by MahefaAbel** [SamKirkland/FTP-Deploy-Action#68]
In my github project, i have used the config below : 

```
- name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://${{ secrets.HOST }}${{ secrets.PATH_PROJECT }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure
```

But on the step  `FTP-Deploy-Action`, i get this error :

> fatal: Dirty repository: Having uncommitted changes. Exiting...

**NB :** 
- Yes, i'm sure that my change is commited and pushed
- Because of this is runned by github action, `git status` make no sense (cause github actions clone the repo to a **new env** before `git ftp push`, which produce the error)

[Stackoverflow link](https://stackoverflow.com/questions/61516256/ftp-deploy-action-fatal-dirty-repository-having-uncommitted-changes-exiting)

**Comment by SamKirkland** [comment]
Is that your entire action config?
I believe this issue only occurs when attempting to upload a folder that doesn't exist in source control. Are you trying to upload a built file (ex: `local-dir: build`)?

If you are attempting to upload a file that isn't in git you must add it to `.git-ftp-include` or use this workaround https://github.com/SamKirkland/FTP-Deploy-Action/issues/47#issuecomment-599746975

**Comment by MahefaAbel** [comment]
@SamKirkland 
Thanks for speed response.
Other config, just :
```
- name: Setup .env file
      run: php -r "copy('.env.prod', '.env');"
```

I try this. Thanks

**Comment by timyboy12345** [comment]
For me this solution worked, but I don't know what caused the problem, since it suddenly occurred. But the following config file fixed the issue:

```yml
      - name: Angular Production build
        run: |
          npm i
          npm run build:prod

      - name: Reset Git
        run: git reset --hard

      - name: List output files
        run: ls

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}${{ secrets.FTP_EXTERNAL_LOCATION }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/MUSI-Angular # This folder is NOT going to upload by default unless you add it to .git-ftp-include
```

**Comment by Rowin206** [comment]
I have the same problem:

`on: push
name: Build and Publish Front End Framework Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build Project
      run: |
        npm install
        npm run build --if-present
        
    - name: List output files
      run: ls
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public
        git-ftp-args: --insecure
`

local-dir is the local build folder, right?

**Comment by ceifa** [comment]
It is happening randomly in my workflow, I have tried all the described workarounds. In the past it worked well 100% of the time.

https://github.com/ceifa/lory-gmod-servers/actions

**Comment by AntonioKoB** [comment]
I am having the same issue after a variable substitution on my appsettings.json
```
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: microsoft/variable-substitution@v1
      with:
        files: 'appsettings.json'
      env:
        ConnectionStrings.ToBudget: 'This is just a test'
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: <my server>
        # FTP account username
        ftp-username: <My Username>
        ftp-password: ${{ secrets.FtpPassword }}
```
