### ISSUE TITLE
Dry run does not work as described

### ISSUE THREAD

**Issue by Philzen** [SamKirkland/FTP-Deploy-Action#70]
**Bug Description**
While setting up my deployment workflow, i came across the [dry run flag in the documentation](https://github.com/SamKirkland/FTP-Deploy-Action#log-only-dry-run-use-this-mode-for-testing) and thought it might be wise to use it before finally firing the data at my server.

Surprisingly, everything worked out fine on first try *but* the build files also were successfully pushed up to the server. 

Either i'm understanding the purpose of this flag wrong, applied it incorrectly, or it's broken.

**My Action Config**
```yaml
name: Jekyll to FTP CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: 🛎 Check out master
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: 🎩 Install Jekyll
      run: |
        sudo gem install bundler jekyll
        sudo bundle install
    - name: 🧹 Clean site
      run: |
        if [ -d "_site" ]; then
          rm -rf _site/*
        fi
    - name: 🔨 Build site
      run: bundle exec jekyll build --config _config.yml,_config_production.yml
    - name: 🚀 Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_SERVER}}
        FTP_USERNAME: ${{secrets.FTP_USERNAME}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        LOCAL_DIR: _site
        git-ftp-args: --dry-run
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@2.0.0
  with:
    method: ftp
    port: 21
  env:
    FTP_SERVER: ***
    FTP_USERNAME: ***
    FTP_PASSWORD: ***
    LOCAL_DIR: _site
    git-ftp-args: --dry-run
/usr/bin/docker run --name c27d3178f8afeaef9e484e826ea7d487a60282_826e40 --label c27d31 --workdir /github/workspace --rm -e FTP_SERVER -e FTP_USERNAME -e FTP_PASSWORD -e LOCAL_DIR -e git-ftp-args -e INPUT_FTP_SERVER -e INPUT_FTP_USERNAME -e INPUT_FTP_PASSWORD -e INPUT_METHOD -e INPUT_PORT -e INPUT_LOCAL_DIR -e INPUT_REMOTE_DIR -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/stadtwerk-mit-zukunft/stadtwerk-mit-zukunft":"/github/workspace" c27d31:78f8afeaef9e484e826ea7d487a60282  "" "" "" "ftp" "21" "" ""
Starting FTP Deploy
Using ftp to connect to port 21
Uploading files...
FTP Deploy Complete
```

**Comment by SamKirkland** [comment]
It appears you are using version `2.0.0` of the action but referring to the documentation from version `3.0.0`. You can switch over to version 3 ([see migration guide](https://github.com/SamKirkland/FTP-Deploy-Action/blob/master/v2-v3-migration.md)) or update your settings to use `ARGS` instead of `git-ftp-args` (see example below)

[Version 2 of the documentation can be found here](https://github.com/SamKirkland/FTP-Deploy-Action/tree/2.0.0)
```yaml
      uses: SamKirkland/FTP-Deploy-Action@2.0.0 # <----- using version 2.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_SERVER}}
        FTP_USERNAME: ${{secrets.FTP_USERNAME}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        LOCAL_DIR: _site
        ARGS: --dry-run # <----- version 2 called this "ARGS" instead of "git-ftp-args"
```
