### ISSUE TITLE
.htaccess not uploading

### ISSUE THREAD

**Issue by RALMAZ** [SamKirkland/FTP-Deploy-Action#73]
**Bug Description**
.htaccess not uploading
I don't use `exclude` and other options like this
All other files uploading well

**My Action Config**
```yaml
 - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.SFTP_SERVER }}
        ftp-username: ${{ secrets.SFTP_USERNAME }}
        ftp-password: ${{ secrets.SFTP_PASS }}
        local-dir: dist/
```
