### ISSUE TITLE
Doesn't automatically run build, but will deploy

### ISSUE THREAD

**Issue by Rowin206** [SamKirkland/FTP-Deploy-Action#74]
**Bug Description**
After every push, the project will deploy but without build process. It's a gatsby + reactjs project. 

As soon as I run the build process by hand (in my code editor), and then push. The changes are visible. No problems with deploying, it takes the files from the 'public' folder. 

**My Action Config**
```
on: push
name: Build and Publish Front End Framework Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build Project
      run: |
        npm install
        npm run build --if-present
        
    - name: Reset Git
      run: git reset --hard

    - name: List output files
      run: ls
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ${{ secrets.FTP_SUBDOMAIN }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public
        git-ftp-args: --insecure
```

**My Action Log**
```
   FTP-Deploy-Action5s
  Fri May 15 18:45:39 UTC 2020: Last deployment changed from 7edeef99894c85c564f395d3bf9f1a939bbf8333 to 5c4e6d0511c4299441ea1311d8995ddbae6bdf4d.
Run SamKirkland/FTP-Deploy-Action@3.1.0
/usr/bin/docker run --name be76db4ff436c974fa48acaa847f4f70e4bcd2_0b68e3 --label be76db --workdir /github/workspace --rm -e INPUT_FTP-SERVER -e INPUT_FTP-USERNAME -e INPUT_FTP-PASSWORD -e INPUT_LOCAL-DIR -e INPUT_GIT-FTP-ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/storybook.rva-services/storybook.rva-services":"/github/workspace" be76db:4ff436c974fa48acaa847f4f70e4bcd2
Uploading files
  /usr/bin/git ftp push --force --auto-init --verbose --syncroot public --user *** --passwd *** --insecure ***
  Fri May 15 18:45:36 UTC 2020: git-ftp version 1.5.1 running on Linux f542dab0c087 5.3.0-1020-azure #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020 x86_64 GNU/Linux
  Fri May 15 18:45:36 UTC 2020: Forced mode enabled.
  Fri May 15 18:45:36 UTC 2020: Auto init if needed.
  Fri May 15 18:45:36 UTC 2020: Using syncroot public if exists.
  Fri May 15 18:45:36 UTC 2020: Insecure SSL/TLS connection allowed
  Fri May 15 18:45:36 UTC 2020: Host is '***.transurl.nl'.
  Fri May 15 18:45:36 UTC 2020: User is '***'.
  Fri May 15 18:45:36 UTC 2020: Password is set.
  Fri May 15 18:45:36 UTC 2020: CACert is ''.

```
