### ISSUE TITLE
##[error]The process '/usr/bin/git' failed with exit code 8

### ISSUE THREAD

**Issue by felixhaeberle** [SamKirkland/FTP-Deploy-Action#77]
**Bug Description**
Deploy does not work because of 'dirty reository', but repository and working tree is clean for sure. Thanks very much in advance for your help.

**My Action Config**
```yaml
name: Build and deploy website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and deploy the website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        tools: composer
    - run: composer install
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install yarn
    - run: yarn install
    - run: yarn build
    
    - name: Deploy website with FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_URL }} # configure .git-ftp-include
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        git-ftp-args: --dry-run
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@3.1.1
/usr/bin/docker run --name be76dbd73d8ce7b6394db59118b3d4c1ca3832_9ed31a --label be76db --workdir /github/workspace --rm -e INPUT_FTP-SERVER -e INPUT_FTP-USERNAME -e INPUT_FTP-PASSWORD -e INPUT_LOCAL-DIR -e INPUT_GIT-FTP-ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/talanja/talanja":"/github/workspace" be76db:d73d8ce7b6394db59118b3d4c1ca3832
Uploading files
  /usr/bin/git ftp push --force --auto-init --verbose --syncroot=./ --user=*** --passwd=*** --dry-run ***
  Sun May 24 22:36:21 UTC 2020: git-ftp version 1.5.1 running on Linux 6aa8086bd3cf 5.3.0-1020-azure #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020 x86_64 GNU/Linux
  Sun May 24 22:36:21 UTC 2020: Forced mode enabled.
  Sun May 24 22:36:21 UTC 2020: Auto init if needed.
  Sun May 24 22:36:21 UTC 2020: Using syncroot ./ if exists.
  Sun May 24 22:36:21 UTC 2020: Running dry, won't do anything.
  Sun May 24 22:36:21 UTC 2020: fatal: Dirty repository: Having uncommitted changes. Exiting...
##[error]The process '/usr/bin/git' failed with exit code 8
```
