### ISSUE TITLE
 FTP-Deploy-Action keeps running forever

### ISSUE THREAD

**Issue by nhatnx** [SamKirkland/FTP-Deploy-Action#78]
**Bug Description**
It keeps running forever after files are uploaded to FTP successfully. Below log-text is printed continuously.

**My Action Config**
```yaml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure
```

**My Action Log**
```
######################################################################## 100.0%
#=#=#                                                                         
##O#- #                                                                       
##O=#  #                                                                      
#=#=-#  #                                                                     
-#O#- #   #                                                                   
-=#=#   #   #                                                                 
-=O#- #  #    #                                                               
-=O=#  #   #   #
```
