### ISSUE TITLE
##[error]The process '/usr/bin/git' failed with exit code 3

### ISSUE THREAD

**Issue by suehiro-snsh** [SamKirkland/FTP-Deploy-Action#80]
I setup FTP-Deploy-Action as document, but I got `##[error]The process '/usr/bin/git' failed with exit code 3` error.
dist/ is ignored by .gitignore, but should be sent by .git-ftp-include.

Thanks a lot.

**directories**
```
.github/
  workflows/
    main.yml
.git
.git-ftp-include
.gitignore
dist/
src/
```
**main.yml**
```
name: master

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --remote-root ${{ secrets.FTP_REMOTE_ROOT }}
        local-dir: dist

```

**Error on Github Actions**
```
  Set up job3s
  Build SamKirkland/FTP-Deploy-Action@3.1.134s
  Run actions/checkout@v2.1.01s
  FTP-Deploy-Action1s
  Wed Jun  3 06:38:46 UTC 2020: fatal: Unrecognised option: ***
Run SamKirkland/FTP-Deploy-Action@3.1.1
/usr/bin/docker run --name d31fee01885b40415290db48c087766e52_4b989b --label 3888d3 --workdir /github/workspace --rm -e INPUT_FTP-SERVER -e INPUT_FTP-USERNAME -e INPUT_FTP-PASSWORD -e INPUT_GIT-FTP-ARGS -e INPUT_LOCAL-DIR -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/webpack-template/webpack-template":"/github/workspace" 3888d3:1fee01885b40415290db48c087766e52
Uploading files
  /usr/bin/git ftp push --force --auto-init --verbose --syncroot=dist --user=*** --passwd=*** --remote-root *** ***
  Wed Jun  3 06:38:46 UTC 2020: git-ftp version 1.5.1 running on Linux be9827024239 5.3.0-1020-azure #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020 x86_64 GNU/Linux
  Wed Jun  3 06:38:46 UTC 2020: Forced mode enabled.
  Wed Jun  3 06:38:46 UTC 2020: Auto init if needed.
  Wed Jun  3 06:38:46 UTC 2020: Using syncroot dist if exists.
  Wed Jun  3 06:38:46 UTC 2020: fatal: Unrecognised option: ***
##[error]The process '/usr/bin/git' failed with exit code 3
✅ Deploy Complete
  Post Run actions/checkout@v2.1.00s
  Complete job
```

**Comment by SamKirkland** [comment]
Does your `remote-root` happen to have spaces in it?

I recommend using `ftp-server` to specify the remote root instead. Ex: `ftp://ftp.samkirkland.com/destinationPath/` (`destinationPath/` is the remote root)

**Comment by a-popovic** [comment]
Thanks just in time, I was also struggling with the same issue right now. The recommendation of @SamKirkland works.

**Comment by chmielulu** [comment]
I have same issu

**Comment by chmielulu** [comment]
I have the same issue

**Comment by chmielulu** [comment]
I have the same issue. I don't use remote-root. I use ftp-server to specify the remote root instead. I also added `public` folder to `.git-ftp-include`

### Configuration

```     
- name: FTP Deploy
    uses: SamKirkland/FTP-Deploy-Action@3.1.1
    with:
      ftp-server: ftp://s71.linuxpl.com/public_html/
      ftp-username: ${{ secrets.FTP_USER }}
      ftp-password: ${{ secrets.FTP_PASSWORD }}
      local-dir: public
      git-ftp-args: --insecure --all
````

### .git-ftp-include

```
!public/
```

### Error in logs
```
`/usr/bin/git ftp push --force --auto-init --verbose --syncroot=public --user=*** --passwd=*** --insecure --all ftp://***/public_html/
  Tue Jul 28 09:18:41 UTC 2020: git-ftp version 1.5.1 running on Linux 86aa31b08b96 5.3.0-1032-azure #33~18.04.1-Ubuntu SMP Fri Jun 26 15:01:15 UTC 2020 x86_64 GNU/Linux
  Tue Jul 28 09:18:41 UTC 2020: Forced mode enabled.
  Tue Jul 28 09:18:41 UTC 2020: Auto init if needed.
  Tue Jul 28 09:18:41 UTC 2020: Using syncroot public if exists.
  Tue Jul 28 09:18:41 UTC 2020: fatal: Unrecognised option: ftp://***/public_html/
##[error]The process '/usr/bin/git' failed with exit code 3`
```
