### ISSUE TITLE
Unknown SHA1 object, could not determine changed files, taking all files.

### ISSUE THREAD

**Issue by aled2305** [SamKirkland/FTP-Deploy-Action#82]
**EDIT**

After reading the FAQ I've seen: _If you've had multiple git commits without deploying, all files will be uploaded to get back in sync_

Is there any fix for this?
___
**Issue Description**
Hi there, I seem to be having an issue with Unknown SHA1 object

**_Unknown SHA1 object, could not determine changed files, taking all files._** 

After doing some research it seems to only happen if I make more than one commit before pushing. I'm extremely new to git so please excuse my ignorance, but if anyone could help, that would be great.

Updating one file then takes 10+min. Does anyone know how to resolve? FTP Server is hosted on cPanel if that helps.

Many thanks 

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://******
        ftp-username: *****
        ftp-password: ${{ secrets.FTP_PASSWORD }}
```

**My Action Log**
```
     #=#=#                                                                         
  ##O#- #                                                                       
  ##O=#  #                                                                      
  #=#=-#  #                                                                     
  -#O#- #   #                                                                   
  -=#=#   #   #                                                                 
  
  ######################################################################## 100.0%
  Thu Jun 11 22:49:04 UTC 2020: Unknown SHA1 object, could not determine changed files, taking all files.
  Thu Jun 11 22:49:04 UTC 2020: Having files to sync.
  Thu Jun 11 22:49:04 UTC 2020: 1090 files to sync:
```

**Comment by bkhrupa** [comment]
hi there!

The root of evil, in my case is `fetch-depth: 2` option on the `actions/checkout@v2`

I spent a couple of days to figure out this issue :(

I will try to explain:

I delete `.git-ftp.log` on the FTP server.

then runs my workflow action

git-ftp creates a new `.git-ftp.log` and store hash SOMEHASH_1

I made 2+ commits locally and push to the repository (SOMEHASH_2, SOMEHASH_3, SOMEHASH_4)

Again runs my workflow action and see **Unknown SHA1 object, could not determine changed files, taking all files.** and git-ftp upload all 100500 files to the server.

this hapens becauseand in the `.git-ftp.log` file has SOMEHASH_1 hash, and `actions/checkout@v2` `fetch-depth: 2` recive *SOMEHASH_3*, *SOMEHASH_4*

so I increased the `fetch-depth: 40`. Everything works now! git-ftp  uploaded only files that i changed. Of course, if I make more than 40 commits, I will have this problem again.

```
name: build_and_deploy
on:
  workflow_dispatch:
jobs:
  job_php:
    .....
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 40
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        .....
```
