### ISSUE TITLE
--insecure flag stops the execution

### ISSUE THREAD

**Issue by AlexMayol** [SamKirkland/FTP-Deploy-Action#83]
**Bug Description**
Adding `--insecure` to `git-ftp-args` results on the following error:
```
 Fri Jun 19 09:49:24 UTC 2020: fatal: Unrecognised option: ftp://xxx.com:21/
##[error]The process '/usr/bin/git' failed with exit code 3
```
These two should be unrelated (I guess) so it took me a while to figure the cause was it was this flag.

**My Action Config**
```yaml
on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://xxx.com:21/
        ftp-username: xxx
        ftp-password: xxx
        git-ftp-args: --verbose --insecure
```

**My Action Log**
```
  Fri Jun 19 09:49:24 UTC 2020: git-ftp version 1.5.1 running on Linux d5c6126817f4 5.3.0-1028-azure #29~18.04.1-Ubuntu SMP Fri Jun 5 14:32:34 UTC 2020 x86_64 GNU/Linux
  Fri Jun 19 09:49:24 UTC 2020: Forced mode enabled.
  Fri Jun 19 09:49:24 UTC 2020: Auto init if needed.
  Fri Jun 19 09:49:24 UTC 2020: Using syncroot ./ if exists.
  Fri Jun 19 09:49:24 UTC 2020: fatal: Unrecognised option: ftp://xxx.com:21/
##[error]The process '/usr/bin/git' failed with exit code 3
```
