### ISSUE TITLE
How to deploy local-dir content instead of the folder itself?

### ISSUE THREAD

**Issue by enguerranws** [SamKirkland/FTP-Deploy-Action#84]
Hi,

I'm trying to deploy the content of a `build` folder.

My action set up is the following:

```
name: Build + FTP Deploy to dev
on:
  push:
    branches: [ develop ]  
jobs:    
    build:
      runs-on: ubuntu-latest      
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run-script build:staging
    FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest
      needs: build
      steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 4
      - name: FTP-Deploy-Action
      
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://xxxx.com
          ftp-username: xxxx
          ftp-password: ${{ secrets.FTP_PASSWORD_DEV }}
          local-dir: ./build/
```

My issue is that my `local-dir` is getting deployed, not just its content. So I'm having a new `build` folder on my distant server.

How can I deploy only the content of a folder?
