### ISSUE TITLE
Ignore all except `output` folder

### ISSUE THREAD

**Issue by cilerler** [SamKirkland/FTP-Deploy-Action#85]
How can I upload only a folder/file and nothing else?

**Comment by SamKirkland** [comment]
You can use the `local-dir` option to specify what folder you want to upload. In the example below I'm uploading anything in the `build` folder.
Then you can use `.git-ftp-include` and `.git-ftp-ignore` to limit the script down to publish only one file.

```yaml
...
      with:
        ftp-server: ftp://ftp.samkirkland.com/
        ftp-username: myFTPUsername
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build
```
