### ISSUE TITLE
curl: (67) Access denied: 530 - The process '/usr/bin/git' failed with exit code 5

### ISSUE THREAD

**Issue by ErikFisherGitHub** [SamKirkland/FTP-Deploy-Action#87]
**Bug Description**

I'm Erik, a novice web developer. I want to get GitHub to upload my changed files to the FTP server after every push. I created this issue because, after the push, I get this error message under the action tab. May I have a hand?

**My Action Config**
```yaml
on: push
name: FTP feltöltés
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
```

**My Action Log**
```
   Check failure on line 1 in .github

@github-actions
github-actions
/ FTP-Deploy-Action

.github#L1
The process '/usr/bin/git' failed with exit code 5


 #=#=-#  #                                                                     
  -#O#- #   #                                                                   
  -=#=#   #   #                                                                 
  -=O#- #  #    #                                                               
  -=O=#  #   #   #                                                              
  -=O=-#  #    #   #                                                            
  -=O=- #   #   #     #                                                         
  -=O=-   #   #   #     #                                                       
  curl: (67) Access denied: 530
  Wed Jul  1 12:21:04 UTC 2020: Check if ftp://***:***@ftpx.forpsi.com is accessible.
  #=#=#                                                                         
  ##O#- #                                                                       
  ##O=#  #                                                                      
  #=#=-#  #                                                                     
  -#O#- #   #                                                                   
  -=#=#   #   #                                                                 
  -=O#- #  #    #                                                               
  -=O=#  #   #   #                                                              
  -=O=-#  #    #   #                                                            
  -=O=- #   #   #     #                                                         
  curl: (67) Access denied: 530
  Wed Jul  1 12:21:10 UTC 2020: fatal: Can't access remote 'ftp://***:***@ftpx.forpsi.com', exiting...
##[error]The process '/usr/bin/git' failed with exit code 5

```
