### ISSUE TITLE
ARGS: parameter not set - make ARGS optional

### ISSUE THREAD

**Issue by Misiu** [SamKirkland/FTP-Deploy-Action#9]
Hi there,
recent version adds support for ARGS parameter, but if someone isn't using it then the deploy won't work.
I get this error:

> Starting FTP Deploy
> Uploading files...
> /entrypoint.sh: line 12: ARGS: parameter not set

I use Your action like so:

```
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@master
      env: 
       FTP_SERVER: ${{ secrets.FTP_SERVER }}
       FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
       FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
       REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
       LOCAL_DIR: ${{ secrets.LOCAL_DIR }}
```

Can ARGS be optional?
