### ISSUE TITLE
Upload maven build

### ISSUE THREAD

**Issue by Olzie-12** [SamKirkland/FTP-Deploy-Action#90]
**Bug Description**
When i am putting my directory as /target. it doesn't upload anything to my FTP server apart from the log. I've also confirmed there are files in that folder by executing ```is target/```

**My Action Config**
```yaml

name: Maven
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          local-dir: target
          ftp-server: sftp://URL:PORT/bots
          git-ftp-args: --insecure
          ftp-username: ${{secrets.FTP_USERNAME}}
          ftp-password: ${{secrets.FTP_PASSWORD}}
```
