### ISSUE TITLE
Composer taking a very long time

### ISSUE THREAD

**Issue by CHEWX** [SamKirkland/FTP-Deploy-Action#91]
Hi,

I'm assuming my setup is wrong, but my repo is taking around 25 minutes on each push to upload. I'm assuming this is to do with composer?

```
on: push
name: Publish Website
jobs:
  build:
    name: Build and deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: composer
      - run: composer install
      - name: Deploy website with FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.0
        with:
          ftp-server: ${{ secrets.FTP_ADDRESS }}
          ftp-username: ${{ secrets.FTP_UNAME }}
          ftp-password: ${{ secrets.FTP_PWORD }}
          local-dir: ./
```

Couldn't find any info anywhere.

Thanks,
Tom
