### ISSUE TITLE
Unexpected input(s) 'known-hosts'

### ISSUE THREAD

**Issue by surjithctly** [SamKirkland/FTP-Deploy-Action#98]
**Bug Description**
The Action Ran Successfully, but github throws the following warning. 

`Unexpected input(s) 'known-hosts', valid inputs are ['entryPoint', 'args', 'ftp-server', 'ftp-username', 'ftp-password', 'local-dir', 'git-ftp-args']`

`knwon-hosts` are mentioned in the docs, but not sure why it showing the warning. Can remove this warning if safe?

**My Action Config**
```yaml
      with:
        ftp-server: sftp://ftp.samkirkland.com:7280/
        ftp-username: mySFTPUsername
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        known-hosts: [samkirkland.com]:7822 ssh-rsa AAAA...5Spw==
```
